-- RNDM Chat v25 — referrals + expanded Admin Center
-- Run AFTER v24.2. Safe to run more than once.

-- =====================
-- REFERRALS (REAL CLOUD)
-- =====================
alter table public.profiles add column if not exists referral_code text;
alter table public.profiles add column if not exists referred_by uuid references public.profiles(id) on delete set null;
alter table public.profiles add column if not exists referral_count integer not null default 0;
alter table public.profiles add column if not exists referral_stars_earned bigint not null default 0;
alter table public.profiles add column if not exists referral_coins_earned bigint not null default 0;

create unique index if not exists profiles_referral_code_uq on public.profiles(referral_code) where referral_code is not null;

create or replace function public.referral_code_for(uid uuid)
returns text language sql immutable as $$
  select 'R' || upper(substr(replace(uid::text,'-',''),1,11));
$$;

update public.profiles
set referral_code=public.referral_code_for(id)
where referral_code is null or referral_code='';

create or replace function public.assign_referral_code()
returns trigger language plpgsql as $$
begin
  if new.referral_code is null or new.referral_code='' then
    new.referral_code := public.referral_code_for(new.id);
  end if;
  return new;
end $$;

drop trigger if exists trg_profile_referral_code on public.profiles;
create trigger trg_profile_referral_code
before insert on public.profiles
for each row execute function public.assign_referral_code();

create table if not exists public.referrals (
  id bigint generated by default as identity primary key,
  referrer_id uuid not null references public.profiles(id) on delete cascade,
  referred_id uuid not null unique references public.profiles(id) on delete cascade,
  referral_code text not null,
  referrer_stars bigint not null default 50,
  referred_stars bigint not null default 25,
  referrer_coins bigint not null default 1000,
  referred_coins bigint not null default 250,
  created_at timestamptz not null default now()
);

alter table public.referrals enable row level security;
drop policy if exists referrals_read_own on public.referrals;
create policy referrals_read_own on public.referrals for select to authenticated
using(referrer_id=auth.uid() or referred_id=auth.uid() or public.is_staff());
grant select on public.referrals to authenticated;

create or replace function public.add_cat_coins(target uuid, delta bigint)
returns void language plpgsql security definer set search_path=public as $$
declare oldv jsonb; nc bigint; nt bigint;
begin
  select value into oldv from public.user_state where user_id=target and key='ls:rndmCatV2' for update;
  oldv := coalesce(oldv,'{}'::jsonb);
  begin nc := coalesce((oldv->>'coins')::bigint,0)+delta; exception when others then nc:=delta; end;
  begin nt := coalesce((oldv->>'totalCoins')::bigint,0)+delta; exception when others then nt:=delta; end;
  oldv := jsonb_set(oldv,'{coins}',to_jsonb(greatest(0,nc)),true);
  oldv := jsonb_set(oldv,'{totalCoins}',to_jsonb(greatest(0,nt)),true);
  oldv := jsonb_set(oldv,'{lastSeen}',to_jsonb((extract(epoch from now())*1000)::bigint),true);
  insert into public.user_state(user_id,key,value,updated_at)
  values(target,'ls:rndmCatV2',oldv,now())
  on conflict(user_id,key) do update set value=excluded.value,updated_at=now();
end $$;
revoke all on function public.add_cat_coins(uuid,bigint) from public;

create or replace function public.ensure_referral_code()
returns text language plpgsql security definer set search_path=public as $$
declare c text;
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  update public.profiles set referral_code=public.referral_code_for(id)
  where id=auth.uid() and (referral_code is null or referral_code='');
  select referral_code into c from public.profiles where id=auth.uid();
  return c;
end $$;
grant execute on function public.ensure_referral_code() to authenticated;

create or replace function public.claim_referral(ref_code text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare
  me uuid:=auth.uid(); ref uuid; current_ref uuid; inserted integer:=0; ref_name text;
  code text:=upper(trim(coalesce(ref_code,'')));
begin
  if me is null then raise exception 'not authenticated'; end if;
  if code='' then raise exception 'empty referral code'; end if;
  select referred_by into current_ref from public.profiles where id=me for update;
  select id,username into ref,ref_name from public.profiles where upper(referral_code)=code limit 1;
  if ref is null then raise exception 'referral code not found'; end if;
  if ref=me then raise exception 'cannot refer yourself'; end if;
  if current_ref is not null then
    return jsonb_build_object('ok',true,'status','already_claimed','referrer_id',current_ref);
  end if;

  insert into public.referrals(referrer_id,referred_id,referral_code)
  values(ref,me,code) on conflict(referred_id) do nothing;
  get diagnostics inserted = row_count;
  if inserted=0 then
    select referrer_id into current_ref from public.referrals where referred_id=me;
    update public.profiles set referred_by=current_ref where id=me and referred_by is null;
    return jsonb_build_object('ok',true,'status','already_claimed','referrer_id',current_ref);
  end if;

  update public.profiles set
    referred_by=ref,
    stars=stars+25,
    xp=xp+100
  where id=me;

  update public.profiles set
    stars=stars+50,
    xp=xp+250,
    referral_count=referral_count+1,
    referral_stars_earned=referral_stars_earned+50,
    referral_coins_earned=referral_coins_earned+1000
  where id=ref;

  perform public.add_cat_coins(ref,1000);
  perform public.add_cat_coins(me,250);

  insert into public.notifications(user_id,kind,title,body,link)
  values
    (ref,'referral','🎉 Новый реферал','Кто-то зарегистрировался по вашей ссылке. +50 ⭐, +250 XP, +1000 🪙','cat.html'),
    (me,'referral','🎁 Реферальный бонус','Бонус за регистрацию по ссылке: +25 ⭐, +100 XP, +250 🪙','cat.html');

  return jsonb_build_object('ok',true,'status','claimed','referrer_id',ref,'referrer_username',ref_name,'stars',25,'coins',250,'xp',100);
end $$;
grant execute on function public.claim_referral(text) to authenticated;

-- =====================
-- ADMIN CONTENT MANAGER
-- =====================
create or replace function public.admin_list_content(content_kind text, search_text text default '', max_rows integer default 50)
returns setof jsonb language plpgsql security definer set search_path=public as $$
declare k text:=lower(coalesce(content_kind,'')); q text:='%'||coalesce(search_text,'')||'%'; lim integer:=least(greatest(coalesce(max_rows,50),1),100);
begin
  if not public.is_staff() then raise exception 'staff required'; end if;
  case k
    when 'conversations' then return query select jsonb_build_object('id',c.id::text,'title',coalesce(nullif(c.title,''),case when c.kind='direct' then 'Личный чат' else 'Группа' end),'subtitle',c.kind||' • '||c.created_at::text,'created_at',c.created_at,'payload',to_jsonb(c)) from public.conversations c where coalesce(c.title,'') ilike q or c.id::text ilike q order by c.created_at desc limit lim;
    when 'messages' then return query select jsonb_build_object('id',m.id::text,'title',left(coalesce(m.body,'[вложение]'),100),'subtitle','chat '||m.conversation_id::text||' • sender '||m.sender_id::text,'created_at',m.created_at,'payload',to_jsonb(m)) from public.messages m where coalesce(m.body,'') ilike q or m.id::text ilike q order by m.created_at desc limit lim;
    when 'channels' then return query select jsonb_build_object('id',c.id::text,'title',c.name,'subtitle','@'||coalesce(c.handle,'—')||' • owner '||c.owner_id::text,'created_at',c.created_at,'payload',to_jsonb(c)) from public.rndm_channels c where c.name ilike q or coalesce(c.handle,'') ilike q or coalesce(c.description,'') ilike q order by c.created_at desc limit lim;
    when 'channel_posts' then return query select jsonb_build_object('id',p.id::text,'title',left(coalesce(p.body,'[вложение]'),100),'subtitle','channel '||p.channel_id::text,'created_at',p.created_at,'payload',to_jsonb(p)) from public.rndm_channel_posts p where coalesce(p.body,'') ilike q order by p.created_at desc limit lim;
    when 'channel_comments' then return query select jsonb_build_object('id',x.id::text,'title',left(x.body,100),'subtitle','post '||x.post_id::text,'created_at',x.created_at,'payload',to_jsonb(x)) from public.rndm_channel_comments x where x.body ilike q order by x.created_at desc limit lim;
    when 'clips' then return query select jsonb_build_object('id',x.id::text,'title',left(coalesce(x.caption,'Clip'),100),'subtitle','author '||x.user_id::text,'created_at',x.created_at,'payload',to_jsonb(x)) from public.clips x where coalesce(x.caption,'') ilike q or x.id::text ilike q order by x.created_at desc limit lim;
    when 'clip_comments' then return query select jsonb_build_object('id',x.id::text,'title',left(x.body,100),'subtitle','clip '||x.clip_id::text,'created_at',x.created_at,'payload',to_jsonb(x)) from public.clip_comments x where x.body ilike q order by x.created_at desc limit lim;
    when 'videos' then return query select jsonb_build_object('id',x.id::text,'title',x.title,'subtitle','views '||x.view_count::text||' • author '||x.user_id::text,'created_at',x.created_at,'payload',to_jsonb(x)) from public.rndm_videos x where x.title ilike q or coalesce(x.description,'') ilike q order by x.created_at desc limit lim;
    when 'video_comments' then return query select jsonb_build_object('id',x.id::text,'title',left(x.body,100),'subtitle','video '||x.video_id::text,'created_at',x.created_at,'payload',to_jsonb(x)) from public.rndm_video_comments x where x.body ilike q order by x.created_at desc limit lim;
    when 'market' then return query select jsonb_build_object('id',x.id::text,'title',x.title,'subtitle',x.price::text||' • '||x.city||' • '||x.status,'created_at',x.created_at,'payload',to_jsonb(x)) from public.marketplace_listings x where x.title ilike q or x.description ilike q or x.city ilike q order by x.created_at desc limit lim;
    when 'stories' then return query select jsonb_build_object('id',x.id::text,'title',left(coalesce(x.body,'Story'),100),'subtitle',x.media_type||' • user '||x.user_id::text,'created_at',x.created_at,'payload',to_jsonb(x)) from public.stories x where coalesce(x.body,'') ilike q order by x.created_at desc limit lim;
    when 'events' then return query select jsonb_build_object('id',x.id::text,'title',x.title,'subtitle',x.location_text||' • '||x.starts_at::text,'created_at',x.created_at,'payload',to_jsonb(x)) from public.rndm_events x where x.title ilike q or x.description ilike q or x.location_text ilike q order by x.created_at desc limit lim;
    when 'loans' then return query select jsonb_build_object('id',x.id::text,'title','Кредит '||x.principal::text,'subtitle','remaining '||x.remaining::text||' • '||x.status||' • user '||x.user_id::text,'created_at',x.created_at,'payload',to_jsonb(x)) from public.game_loans x where x.id::text ilike q or x.user_id::text ilike q order by x.created_at desc limit lim;
    when 'properties' then return query select jsonb_build_object('id',x.id::text,'title',x.title,'subtitle',x.city||' • '||x.price::text,'created_at',null,'payload',to_jsonb(x)) from public.demo_properties x where x.title ilike q or x.city ilike q or x.district ilike q order by x.title limit lim;
    when 'friendships' then return query select jsonb_build_object('id',x.id::text,'title',x.status,'subtitle',x.requester::text||' → '||x.addressee::text,'created_at',x.created_at,'payload',to_jsonb(x)) from public.friendships x where x.id::text ilike q or x.requester::text ilike q or x.addressee::text ilike q order by x.created_at desc limit lim;
    when 'notifications' then return query select jsonb_build_object('id',x.id::text,'title',x.title,'subtitle',left(x.body,120),'created_at',x.created_at,'payload',to_jsonb(x)) from public.notifications x where x.title ilike q or x.body ilike q order by x.created_at desc limit lim;
    when 'cloud_state' then return query select jsonb_build_object('id',x.user_id::text||'|'||x.key,'title',x.key,'subtitle','user '||x.user_id::text,'created_at',x.updated_at,'payload',to_jsonb(x)) from public.user_state x where x.key ilike q or x.user_id::text ilike q order by x.updated_at desc limit lim;
    when 'owned_properties' then return query select jsonb_build_object('id',x.user_id::text||'|'||x.property_id::text,'title','Купленная квартира','subtitle','user '||x.user_id::text||' • property '||x.property_id::text||' • '||x.bought_price::text,'created_at',x.bought_at,'payload',to_jsonb(x)) from public.owned_properties x where x.user_id::text ilike q or x.property_id::text ilike q order by x.bought_at desc limit lim;
    when 'daily_claims' then return query select jsonb_build_object('id',x.user_id::text||'|'||x.claim_date::text,'title','Daily '||x.claim_date::text,'subtitle','user '||x.user_id::text||' • ⭐'||x.reward_stars::text||' • XP '||x.reward_xp::text,'created_at',x.created_at,'payload',to_jsonb(x)) from public.daily_claims x where x.user_id::text ilike q or x.claim_date::text ilike q order by x.created_at desc limit lim;
    when 'interests' then return query select jsonb_build_object('id',x.user_id::text||'|'||x.interest,'title',x.interest,'subtitle','user '||x.user_id::text,'created_at',null,'payload',to_jsonb(x)) from public.profile_interests x where x.interest ilike q or x.user_id::text ilike q order by x.interest limit lim;
    when 'follows' then return query select jsonb_build_object('id',x.follower_id::text||'|'||x.followee_id::text,'title','Подписка','subtitle',x.follower_id::text||' → '||x.followee_id::text,'created_at',x.created_at,'payload',to_jsonb(x)) from public.rndm_follows x where x.follower_id::text ilike q or x.followee_id::text ilike q order by x.created_at desc limit lim;
    when 'referrals' then return query select jsonb_build_object('id',x.id::text,'title',x.referral_code,'subtitle',x.referrer_id::text||' → '||x.referred_id::text,'created_at',x.created_at,'payload',to_jsonb(x)) from public.referrals x where x.referral_code ilike q or x.referrer_id::text ilike q or x.referred_id::text ilike q order by x.created_at desc limit lim;
    else raise exception 'unsupported content kind: %',content_kind;
  end case;
end $$;
grant execute on function public.admin_list_content(text,text,integer) to authenticated;

create or replace function public.admin_update_content(content_kind text, content_id text, patch jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare k text:=lower(coalesce(content_kind,'')); affected integer:=0;
begin
  if not public.is_admin() then raise exception 'owner/admin required'; end if;
  patch:=coalesce(patch,'{}'::jsonb);
  case k
    when 'conversations' then update public.conversations set title=case when patch?'title' then nullif(patch->>'title','') else title end, avatar_url=case when patch?'avatar_url' then nullif(patch->>'avatar_url','') else avatar_url end where id=content_id::uuid;
    when 'messages' then update public.messages set body=case when patch?'body' then coalesce(patch->>'body','') else body end, edited_at=now() where id=content_id::bigint;
    when 'channels' then update public.rndm_channels set name=case when patch?'name' then left(patch->>'name',80) else name end, handle=case when patch?'handle' then nullif(lower(patch->>'handle'),'') else handle end, description=case when patch?'description' then patch->>'description' else description end, emoji=case when patch?'emoji' then left(patch->>'emoji',16) else emoji end, promo_subscribers=case when patch?'promo_subscribers' then greatest(0,(patch->>'promo_subscribers')::integer) else promo_subscribers end where id=content_id::uuid;
    when 'channel_posts' then update public.rndm_channel_posts set body=case when patch?'body' then patch->>'body' else body end where id=content_id::uuid;
    when 'channel_comments' then update public.rndm_channel_comments set body=case when patch?'body' then left(patch->>'body',1000) else body end where id=content_id::bigint;
    when 'clips' then update public.clips set caption=case when patch?'caption' then patch->>'caption' else caption end where id=content_id::uuid;
    when 'clip_comments' then update public.clip_comments set body=case when patch?'body' then left(patch->>'body',1000) else body end where id=content_id::bigint;
    when 'videos' then update public.rndm_videos set title=case when patch?'title' then left(patch->>'title',120) else title end, description=case when patch?'description' then patch->>'description' else description end, view_count=case when patch?'view_count' then greatest(0,(patch->>'view_count')::bigint) else view_count end where id=content_id::uuid;
    when 'video_comments' then update public.rndm_video_comments set body=case when patch?'body' then left(patch->>'body',2000) else body end where id=content_id::bigint;
    when 'market' then update public.marketplace_listings set title=case when patch?'title' then left(patch->>'title',120) else title end, description=case when patch?'description' then patch->>'description' else description end, category=case when patch?'category' then patch->>'category' else category end, price=case when patch?'price' then greatest(0,(patch->>'price')::bigint) else price end, city=case when patch?'city' then patch->>'city' else city end, status=case when patch?'status' and patch->>'status' in ('active','sold','hidden') then patch->>'status' else status end where id=content_id::uuid;
    when 'stories' then update public.stories set body=case when patch?'body' then patch->>'body' else body end, expires_at=case when patch?'expires_at' then (patch->>'expires_at')::timestamptz else expires_at end where id=content_id::uuid;
    when 'events' then update public.rndm_events set title=case when patch?'title' then patch->>'title' else title end, description=case when patch?'description' then patch->>'description' else description end, location_text=case when patch?'location_text' then patch->>'location_text' else location_text end, max_people=case when patch?'max_people' then nullif(patch->>'max_people','')::integer else max_people end, starts_at=case when patch?'starts_at' then (patch->>'starts_at')::timestamptz else starts_at end where id=content_id::uuid;
    when 'loans' then update public.game_loans set remaining=case when patch?'remaining' then greatest(0,(patch->>'remaining')::bigint) else remaining end, status=case when patch?'status' and patch->>'status' in ('active','paid') then patch->>'status' else status end where id=content_id::uuid;
    when 'properties' then update public.demo_properties set title=case when patch?'title' then patch->>'title' else title end, city=case when patch?'city' then patch->>'city' else city end, district=case when patch?'district' then patch->>'district' else district end, price=case when patch?'price' then greatest(1,(patch->>'price')::bigint) else price end, rooms=case when patch?'rooms' then greatest(1,(patch->>'rooms')::integer) else rooms end, area=case when patch?'area' then greatest(1,(patch->>'area')::numeric) else area end, emoji=case when patch?'emoji' then patch->>'emoji' else emoji end, description=case when patch?'description' then patch->>'description' else description end where id=content_id::uuid;
    when 'friendships' then update public.friendships set status=case when patch?'status' and patch->>'status' in ('pending','accepted','blocked') then patch->>'status' else status end where id=content_id::bigint;
    when 'notifications' then update public.notifications set title=case when patch?'title' then patch->>'title' else title end, body=case when patch?'body' then patch->>'body' else body end, is_read=case when patch?'is_read' then (patch->>'is_read')::boolean else is_read end where id=content_id::bigint;
    when 'cloud_state' then update public.user_state set value=case when patch?'value' then (patch->>'value')::jsonb else value end,updated_at=now() where user_id=split_part(content_id,'|',1)::uuid and key=split_part(content_id,'|',2);
    when 'owned_properties' then update public.owned_properties set bought_price=case when patch?'bought_price' then greatest(0,(patch->>'bought_price')::bigint) else bought_price end where user_id=split_part(content_id,'|',1)::uuid and property_id=split_part(content_id,'|',2)::uuid;
    when 'daily_claims' then update public.daily_claims set reward_stars=case when patch?'reward_stars' then (patch->>'reward_stars')::integer else reward_stars end,reward_xp=case when patch?'reward_xp' then (patch->>'reward_xp')::integer else reward_xp end,reward_cash=case when patch?'reward_cash' then (patch->>'reward_cash')::bigint else reward_cash end where user_id=split_part(content_id,'|',1)::uuid and claim_date=split_part(content_id,'|',2)::date;
    else raise exception 'editing not supported for %',content_kind;
  end case;
  get diagnostics affected=row_count;
  perform public.admin_log('content_update',null,jsonb_build_object('kind',k,'id',content_id,'patch',patch,'affected',affected));
  return jsonb_build_object('ok',true,'affected',affected);
end $$;
grant execute on function public.admin_update_content(text,text,jsonb) to authenticated;

create or replace function public.admin_delete_content(content_kind text, content_id text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare k text:=lower(coalesce(content_kind,'')); affected integer:=0; role text;
begin
  select app_role into role from public.profiles where id=auth.uid();
  if role not in ('owner','admin','moderator') then raise exception 'staff required'; end if;
  if role='moderator' and k in ('conversations','channels','loans','properties','friendships','referrals') then raise exception 'owner/admin required'; end if;
  case k
    when 'conversations' then delete from public.conversations where id=content_id::uuid;
    when 'messages' then delete from public.messages where id=content_id::bigint;
    when 'channels' then delete from public.rndm_channels where id=content_id::uuid;
    when 'channel_posts' then delete from public.rndm_channel_posts where id=content_id::uuid;
    when 'channel_comments' then delete from public.rndm_channel_comments where id=content_id::bigint;
    when 'clips' then delete from public.clips where id=content_id::uuid;
    when 'clip_comments' then delete from public.clip_comments where id=content_id::bigint;
    when 'videos' then delete from public.rndm_videos where id=content_id::uuid;
    when 'video_comments' then delete from public.rndm_video_comments where id=content_id::bigint;
    when 'market' then delete from public.marketplace_listings where id=content_id::uuid;
    when 'stories' then delete from public.stories where id=content_id::uuid;
    when 'events' then delete from public.rndm_events where id=content_id::uuid;
    when 'loans' then delete from public.game_loans where id=content_id::uuid;
    when 'properties' then delete from public.demo_properties where id=content_id::uuid;
    when 'friendships' then delete from public.friendships where id=content_id::bigint;
    when 'notifications' then delete from public.notifications where id=content_id::bigint;
    when 'cloud_state' then delete from public.user_state where user_id=split_part(content_id,'|',1)::uuid and key=split_part(content_id,'|',2);
    when 'owned_properties' then delete from public.owned_properties where user_id=split_part(content_id,'|',1)::uuid and property_id=split_part(content_id,'|',2)::uuid;
    when 'daily_claims' then delete from public.daily_claims where user_id=split_part(content_id,'|',1)::uuid and claim_date=split_part(content_id,'|',2)::date;
    when 'interests' then delete from public.profile_interests where user_id=split_part(content_id,'|',1)::uuid and interest=split_part(content_id,'|',2);
    when 'follows' then delete from public.rndm_follows where follower_id=split_part(content_id,'|',1)::uuid and followee_id=split_part(content_id,'|',2)::uuid;
    when 'referrals' then delete from public.referrals where id=content_id::bigint;
    else raise exception 'unsupported content kind: %',content_kind;
  end case;
  get diagnostics affected=row_count;
  perform public.admin_log('content_delete',null,jsonb_build_object('kind',k,'id',content_id,'affected',affected));
  return jsonb_build_object('ok',true,'affected',affected);
end $$;
grant execute on function public.admin_delete_content(text,text) to authenticated;

create or replace function public.admin_purge_user_content(target uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare myrole text; targetrole text;
begin
  select app_role into myrole from public.profiles where id=auth.uid();
  select app_role into targetrole from public.profiles where id=target;
  if myrole not in ('owner','admin') then raise exception 'owner/admin required'; end if;
  if public.role_rank(myrole)<=public.role_rank(targetrole) then raise exception 'cannot purge equal/higher role'; end if;
  delete from public.random_queue where user_id=target;
  delete from public.message_reactions where user_id=target;
  delete from public.messages where sender_id=target;
  delete from public.conversation_members where user_id=target;
  delete from public.friendships where requester=target or addressee=target;
  delete from public.clip_likes where user_id=target;
  delete from public.clip_comments where user_id=target;
  delete from public.clips where user_id=target;
  delete from public.marketplace_favorites where user_id=target;
  delete from public.marketplace_listings where seller_id=target;
  delete from public.rndm_channel_reactions where user_id=target;
  delete from public.rndm_channel_comments where user_id=target;
  delete from public.rndm_channel_subscriptions where user_id=target;
  delete from public.rndm_channel_posts where author_id=target;
  delete from public.rndm_channels where owner_id=target;
  delete from public.rndm_video_likes where user_id=target;
  delete from public.rndm_video_comments where user_id=target;
  delete from public.rndm_follows where follower_id=target or followee_id=target;
  delete from public.rndm_videos where user_id=target;
  delete from public.story_views where user_id=target;
  delete from public.story_reactions where user_id=target;
  delete from public.stories where user_id=target;
  delete from public.event_rsvps where user_id=target;
  delete from public.rndm_events where owner_id=target;
  delete from public.daily_claims where user_id=target;
  delete from public.profile_interests where user_id=target;
  delete from public.notifications where user_id=target;
  delete from public.user_state where user_id=target;
  delete from public.owned_properties where user_id=target;
  delete from public.game_loans where user_id=target;
  delete from public.referrals where referrer_id=target or referred_id=target;
  update public.profiles set referred_by=null where referred_by=target;
  perform public.admin_log('purge_user_content',target,'{}'::jsonb);
  return jsonb_build_object('ok',true);
end $$;
grant execute on function public.admin_purge_user_content(uuid) to authenticated;

create or replace function public.admin_delete_app_profile(target uuid)
returns jsonb language plpgsql security definer set search_path=public as $$
declare myrole text; targetrole text;
begin
  select app_role into myrole from public.profiles where id=auth.uid();
  select app_role into targetrole from public.profiles where id=target;
  if myrole<>'owner' then raise exception 'owner required'; end if;
  if target=auth.uid() then raise exception 'owner cannot delete self'; end if;
  if public.role_rank(myrole)<=public.role_rank(targetrole) then raise exception 'cannot delete equal/higher role'; end if;
  perform public.admin_log('delete_app_profile',target,jsonb_build_object('note','auth.users entry remains; app profile/content deleted'));
  delete from public.profiles where id=target;
  return jsonb_build_object('ok',true,'auth_user_deleted',false);
end $$;
grant execute on function public.admin_delete_app_profile(uuid) to authenticated;
