-- RNDM Chat v22 FULL SUPABASE SETUP
-- Can be run on a new project. It combines v18 + v20 + v22.

-- RNDM Chat v18 — real multi-user backend for Supabase
-- Run this ONCE in Supabase Dashboard -> SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  display_name text not null default 'Пользователь',
  avatar_url text,
  bio text not null default '',
  status text not null default 'online',
  last_seen timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
declare
  base text;
  candidate text;
begin
  base := lower(regexp_replace(coalesce(new.raw_user_meta_data->>'username', split_part(coalesce(new.email,'user'),'@',1), 'user'), '[^a-zA-Z0-9_]+', '', 'g'));
  if length(base) < 3 then base := 'user'; end if;
  base := left(base, 22);
  candidate := base;
  while exists(select 1 from public.profiles where username=candidate) loop
    candidate := left(base,17) || '_' || lpad((floor(random()*10000))::int::text,4,'0');
  end loop;
  insert into public.profiles(id,username,display_name,last_seen)
  values(new.id,candidate,coalesce(nullif(new.raw_user_meta_data->>'display_name',''),candidate),now())
  on conflict(id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  requester uuid not null references public.profiles(id) on delete cascade,
  addressee uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check(status in ('pending','accepted','blocked')),
  created_at timestamptz not null default now(),
  unique(requester,addressee),
  check(requester<>addressee)
);

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  kind text not null default 'direct' check(kind in ('direct','group')),
  title text,
  avatar_url text,
  direct_key text unique,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.conversation_members (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member' check(role in ('owner','admin','member')),
  joined_at timestamptz not null default now(),
  last_read_at timestamptz,
  primary key(conversation_id,user_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null default '',
  attachment_url text,
  attachment_name text,
  attachment_type text,
  reply_to bigint references public.messages(id) on delete set null,
  created_at timestamptz not null default now(),
  edited_at timestamptz,
  deleted_at timestamptz
);
create index if not exists messages_conv_created_idx on public.messages(conversation_id,created_at);

create table if not exists public.message_reactions (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  message_id bigint not null references public.messages(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  emoji text not null,
  created_at timestamptz not null default now(),
  primary key(message_id,user_id,emoji)
);

create table if not exists public.typing_states (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  updated_at timestamptz not null default now(),
  primary key(conversation_id,user_id)
);

create or replace function public.is_conversation_member(cid uuid, uid uuid default auth.uid())
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.conversation_members where conversation_id=cid and user_id=uid)
$$;

create or replace function public.send_friend_request(other uuid)
returns bigint language plpgsql security definer set search_path=public as $$
declare fid bigint; me uuid:=auth.uid();
begin
  if me is null or other=me then raise exception 'invalid user'; end if;
  select id into fid from public.friendships
   where (requester=me and addressee=other) or (requester=other and addressee=me) limit 1;
  if fid is not null then return fid; end if;
  insert into public.friendships(requester,addressee) values(me,other) returning id into fid;
  return fid;
end $$;

create or replace function public.accept_friend_request(request_id bigint)
returns void language plpgsql security definer set search_path=public as $$
begin
  update public.friendships set status='accepted' where id=request_id and addressee=auth.uid() and status='pending';
  if not found then raise exception 'request not found'; end if;
end $$;

create or replace function public.get_or_create_direct(other uuid)
returns uuid language plpgsql security definer set search_path=public as $$
declare me uuid:=auth.uid(); k text; cid uuid;
begin
  if me is null or other=me then raise exception 'invalid user'; end if;
  k := least(me::text,other::text)||':'||greatest(me::text,other::text);
  insert into public.conversations(kind,direct_key,created_by) values('direct',k,me)
  on conflict(direct_key) do update set direct_key=excluded.direct_key returning id into cid;
  insert into public.conversation_members(conversation_id,user_id,role) values(cid,me,'member') on conflict do nothing;
  insert into public.conversation_members(conversation_id,user_id,role) values(cid,other,'member') on conflict do nothing;
  return cid;
end $$;

create or replace function public.create_group(group_title text, member_ids uuid[])
returns uuid language plpgsql security definer set search_path=public as $$
declare me uuid:=auth.uid(); cid uuid; x uuid;
begin
  if me is null then raise exception 'not authenticated'; end if;
  insert into public.conversations(kind,title,created_by) values('group',left(coalesce(nullif(group_title,''),'Новая группа'),80),me) returning id into cid;
  insert into public.conversation_members(conversation_id,user_id,role) values(cid,me,'owner');
  foreach x in array coalesce(member_ids,array[]::uuid[]) loop
    if x<>me then insert into public.conversation_members(conversation_id,user_id,role) values(cid,x,'member') on conflict do nothing; end if;
  end loop;
  return cid;
end $$;

alter table public.profiles enable row level security;
alter table public.friendships enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages enable row level security;
alter table public.message_reactions enable row level security;
alter table public.typing_states enable row level security;

drop policy if exists profiles_read on public.profiles;
create policy profiles_read on public.profiles for select to authenticated using(true);
drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());

drop policy if exists friendship_read on public.friendships;
create policy friendship_read on public.friendships for select to authenticated using(requester=auth.uid() or addressee=auth.uid());
drop policy if exists friendship_delete on public.friendships;
create policy friendship_delete on public.friendships for delete to authenticated using(requester=auth.uid() or addressee=auth.uid());

drop policy if exists conversation_read on public.conversations;
create policy conversation_read on public.conversations for select to authenticated using(public.is_conversation_member(id));

drop policy if exists members_read on public.conversation_members;
create policy members_read on public.conversation_members for select to authenticated using(public.is_conversation_member(conversation_id));
drop policy if exists members_update_self on public.conversation_members;
create policy members_update_self on public.conversation_members for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

drop policy if exists messages_read on public.messages;
create policy messages_read on public.messages for select to authenticated using(public.is_conversation_member(conversation_id));
drop policy if exists messages_insert on public.messages;
create policy messages_insert on public.messages for insert to authenticated with check(sender_id=auth.uid() and public.is_conversation_member(conversation_id));
drop policy if exists messages_update_own on public.messages;
create policy messages_update_own on public.messages for update to authenticated using(sender_id=auth.uid()) with check(sender_id=auth.uid());
drop policy if exists messages_delete_own on public.messages;
create policy messages_delete_own on public.messages for delete to authenticated using(sender_id=auth.uid());

drop policy if exists reactions_read on public.message_reactions;
create policy reactions_read on public.message_reactions for select to authenticated using(public.is_conversation_member(conversation_id));
drop policy if exists reactions_insert on public.message_reactions;
create policy reactions_insert on public.message_reactions for insert to authenticated with check(user_id=auth.uid() and public.is_conversation_member(conversation_id));
drop policy if exists reactions_delete on public.message_reactions;
create policy reactions_delete on public.message_reactions for delete to authenticated using(user_id=auth.uid());

drop policy if exists typing_read on public.typing_states;
create policy typing_read on public.typing_states for select to authenticated using(public.is_conversation_member(conversation_id));
drop policy if exists typing_insert on public.typing_states;
create policy typing_insert on public.typing_states for insert to authenticated with check(user_id=auth.uid() and public.is_conversation_member(conversation_id));
drop policy if exists typing_update on public.typing_states;
create policy typing_update on public.typing_states for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

grant select,update on public.profiles to authenticated;
grant select,delete on public.friendships to authenticated;
grant select on public.conversations to authenticated;
grant select,update on public.conversation_members to authenticated;
grant select,insert,update,delete on public.messages to authenticated;
grant select,insert,delete on public.message_reactions to authenticated;
grant select,insert,update on public.typing_states to authenticated;
grant execute on function public.send_friend_request(uuid) to authenticated;
grant execute on function public.accept_friend_request(bigint) to authenticated;
grant execute on function public.get_or_create_direct(uuid) to authenticated;
grant execute on function public.create_group(text,uuid[]) to authenticated;

insert into storage.buckets(id,name,public,file_size_limit) values('chat-files','chat-files',true,52428800)
on conflict(id) do update set public=true,file_size_limit=52428800;
insert into storage.buckets(id,name,public,file_size_limit) values('avatars','avatars',true,10485760)
on conflict(id) do update set public=true,file_size_limit=10485760;

drop policy if exists chat_upload on storage.objects;
create policy chat_upload on storage.objects for insert to authenticated with check(bucket_id='chat-files' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists chat_delete on storage.objects;
create policy chat_delete on storage.objects for delete to authenticated using(bucket_id='chat-files' and owner_id=auth.uid()::text);
drop policy if exists avatar_upload on storage.objects;
create policy avatar_upload on storage.objects for insert to authenticated with check(bucket_id='avatars' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists avatar_update on storage.objects;
create policy avatar_update on storage.objects for update to authenticated using(bucket_id='avatars' and owner_id=auth.uid()::text);
drop policy if exists avatar_delete on storage.objects;
create policy avatar_delete on storage.objects for delete to authenticated using(bucket_id='avatars' and owner_id=auth.uid()::text);

-- Realtime for instant messages / requests / typing / read status
DO $$ begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='messages') then alter publication supabase_realtime add table public.messages; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='friendships') then alter publication supabase_realtime add table public.friendships; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='typing_states') then alter publication supabase_realtime add table public.typing_states; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='conversation_members') then alter publication supabase_realtime add table public.conversation_members; end if;
end $$;
-- RNDM Chat v20 upgrade
-- Run in Supabase SQL Editor AFTER the v18 schema.
-- Adds real Clips publishing, marketplace, and a DEMO/game economy.

create extension if not exists pgcrypto;

-- ---------------- REAL CLIPS ----------------
create table if not exists public.clips (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  video_url text not null,
  caption text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.clip_likes (
  clip_id uuid not null references public.clips(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (clip_id, user_id)
);

create table if not exists public.clip_comments (
  id bigint generated by default as identity primary key,
  clip_id uuid not null references public.clips(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);

create index if not exists clips_created_idx on public.clips(created_at desc);
create index if not exists clip_comments_clip_idx on public.clip_comments(clip_id, created_at);

alter table public.clips enable row level security;
alter table public.clip_likes enable row level security;
alter table public.clip_comments enable row level security;

drop policy if exists clips_read on public.clips;
create policy clips_read on public.clips for select to authenticated using (true);
drop policy if exists clips_insert on public.clips;
create policy clips_insert on public.clips for insert to authenticated with check (user_id = auth.uid());
drop policy if exists clips_delete on public.clips;
create policy clips_delete on public.clips for delete to authenticated using (user_id = auth.uid());

drop policy if exists clip_likes_read on public.clip_likes;
create policy clip_likes_read on public.clip_likes for select to authenticated using (true);
drop policy if exists clip_likes_insert on public.clip_likes;
create policy clip_likes_insert on public.clip_likes for insert to authenticated with check (user_id = auth.uid());
drop policy if exists clip_likes_delete on public.clip_likes;
create policy clip_likes_delete on public.clip_likes for delete to authenticated using (user_id = auth.uid());

drop policy if exists clip_comments_read on public.clip_comments;
create policy clip_comments_read on public.clip_comments for select to authenticated using (true);
drop policy if exists clip_comments_insert on public.clip_comments;
create policy clip_comments_insert on public.clip_comments for insert to authenticated with check (user_id = auth.uid());
drop policy if exists clip_comments_delete on public.clip_comments;
create policy clip_comments_delete on public.clip_comments for delete to authenticated using (user_id = auth.uid());

grant select,insert,delete on public.clips to authenticated;
grant select,insert,delete on public.clip_likes to authenticated;
grant select,insert,delete on public.clip_comments to authenticated;

insert into storage.buckets(id,name,public,file_size_limit)
values('clips','clips',true,104857600)
on conflict(id) do update set public=true,file_size_limit=104857600;

drop policy if exists clips_storage_upload on storage.objects;
create policy clips_storage_upload on storage.objects for insert to authenticated
with check(bucket_id='clips' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists clips_storage_delete on storage.objects;
create policy clips_storage_delete on storage.objects for delete to authenticated
using(bucket_id='clips' and owner_id=auth.uid()::text);

-- ---------------- RNDM MARKET ----------------
create table if not exists public.marketplace_listings (
  id uuid primary key default gen_random_uuid(),
  seller_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check(char_length(title) between 2 and 120),
  description text not null default '',
  category text not null default 'Другое',
  price bigint not null default 0 check(price >= 0),
  city text not null default '',
  image_url text,
  status text not null default 'active' check(status in ('active','sold','hidden')),
  created_at timestamptz not null default now()
);
create index if not exists market_created_idx on public.marketplace_listings(created_at desc);

create table if not exists public.marketplace_favorites (
  listing_id uuid not null references public.marketplace_listings(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(listing_id,user_id)
);

alter table public.marketplace_listings enable row level security;
alter table public.marketplace_favorites enable row level security;

drop policy if exists market_read on public.marketplace_listings;
create policy market_read on public.marketplace_listings for select to authenticated using(status <> 'hidden' or seller_id=auth.uid());
drop policy if exists market_insert on public.marketplace_listings;
create policy market_insert on public.marketplace_listings for insert to authenticated with check(seller_id=auth.uid());
drop policy if exists market_update on public.marketplace_listings;
create policy market_update on public.marketplace_listings for update to authenticated using(seller_id=auth.uid()) with check(seller_id=auth.uid());
drop policy if exists market_delete on public.marketplace_listings;
create policy market_delete on public.marketplace_listings for delete to authenticated using(seller_id=auth.uid());

drop policy if exists market_fav_read on public.marketplace_favorites;
create policy market_fav_read on public.marketplace_favorites for select to authenticated using(user_id=auth.uid());
drop policy if exists market_fav_insert on public.marketplace_favorites;
create policy market_fav_insert on public.marketplace_favorites for insert to authenticated with check(user_id=auth.uid());
drop policy if exists market_fav_delete on public.marketplace_favorites;
create policy market_fav_delete on public.marketplace_favorites for delete to authenticated using(user_id=auth.uid());

grant select,insert,update,delete on public.marketplace_listings to authenticated;
grant select,insert,delete on public.marketplace_favorites to authenticated;

insert into storage.buckets(id,name,public,file_size_limit)
values('market-files','market-files',true,20971520)
on conflict(id) do update set public=true,file_size_limit=20971520;

drop policy if exists market_storage_upload on storage.objects;
create policy market_storage_upload on storage.objects for insert to authenticated
with check(bucket_id='market-files' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists market_storage_delete on storage.objects;
create policy market_storage_delete on storage.objects for delete to authenticated
using(bucket_id='market-files' and owner_id=auth.uid()::text);

-- ---------------- GAME WALLET / LOANS / APARTMENTS ----------------
-- Everything in this section is virtual game currency. It is NOT a real loan or payment system.
create table if not exists public.game_wallets (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  balance bigint not null default 1500000 check(balance >= 0),
  updated_at timestamptz not null default now()
);

insert into public.game_wallets(user_id)
select id from public.profiles
on conflict(user_id) do nothing;

create or replace function public.ensure_game_wallet()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.game_wallets(user_id) values(new.id) on conflict(user_id) do nothing;
  return new;
end $$;

drop trigger if exists on_profile_game_wallet on public.profiles;
create trigger on_profile_game_wallet after insert on public.profiles
for each row execute function public.ensure_game_wallet();

create table if not exists public.game_loans (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  principal bigint not null check(principal > 0),
  rate_percent numeric(6,2) not null,
  term_months int not null,
  total_due bigint not null,
  remaining bigint not null,
  status text not null default 'active' check(status in ('active','paid')),
  created_at timestamptz not null default now()
);

create table if not exists public.demo_properties (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  city text not null,
  district text not null default '',
  price bigint not null check(price > 0),
  rooms int not null default 1,
  area numeric(7,1) not null default 30,
  emoji text not null default '🏠',
  description text not null default ''
);

create table if not exists public.owned_properties (
  user_id uuid not null references public.profiles(id) on delete cascade,
  property_id uuid not null references public.demo_properties(id) on delete cascade,
  bought_at timestamptz not null default now(),
  bought_price bigint not null,
  primary key(user_id,property_id)
);

insert into public.demo_properties(title,city,district,price,rooms,area,emoji,description)
select * from (values
 ('Студия у парка','Москва','Северное Бутово',2350000::bigint,1,24.5::numeric,'🌆','Компактная игровая квартира рядом с парком.'),
 ('Однокомнатная','Москва','Южное Бутово',3900000::bigint,1,38.2::numeric,'🏢','Светлая квартира с большой кухней.'),
 ('Двухкомнатная семейная','Москва','Чертаново',6200000::bigint,2,57.8::numeric,'🏙️','Две комнаты и игровая лоджия.'),
 ('Лофт в центре','Москва','Центр',9800000::bigint,2,71.0::numeric,'🌃','Игровой лофт с панорамными окнами.'),
 ('Загородный дом','Подольск','Волищево',12500000::bigint,4,146.0::numeric,'🏡','Дом с виртуальным участком и гаражом.'),
 ('Пентхаус RNDM','Москва','Москва-Сити',30000000::bigint,5,220.0::numeric,'✨','Самая дорогая коллекционная недвижимость RNDM.')
) as v(title,city,district,price,rooms,area,emoji,description)
where not exists(select 1 from public.demo_properties);

alter table public.game_wallets enable row level security;
alter table public.game_loans enable row level security;
alter table public.demo_properties enable row level security;
alter table public.owned_properties enable row level security;

drop policy if exists wallet_read on public.game_wallets;
create policy wallet_read on public.game_wallets for select to authenticated using(user_id=auth.uid());
drop policy if exists loans_read on public.game_loans;
create policy loans_read on public.game_loans for select to authenticated using(user_id=auth.uid());
drop policy if exists properties_read on public.demo_properties;
create policy properties_read on public.demo_properties for select to authenticated using(true);
drop policy if exists owned_read on public.owned_properties;
create policy owned_read on public.owned_properties for select to authenticated using(user_id=auth.uid());

grant select on public.game_wallets to authenticated;
grant select on public.game_loans to authenticated;
grant select on public.demo_properties to authenticated;
grant select on public.owned_properties to authenticated;

create or replace function public.take_demo_loan(amount bigint, months int)
returns uuid language plpgsql security definer set search_path=public as $$
declare
  me uuid:=auth.uid();
  rate numeric(6,2);
  total bigint;
  lid uuid;
  active_debt bigint;
begin
  if me is null then raise exception 'not authenticated'; end if;
  if amount < 10000 or amount > 5000000 then raise exception 'amount must be from 10000 to 5000000'; end if;
  if months not in (3,6,12,24) then raise exception 'term must be 3, 6, 12 or 24 months'; end if;
  select coalesce(sum(remaining),0) into active_debt from public.game_loans where user_id=me and status='active';
  if active_debt + amount > 7000000 then raise exception 'demo credit limit exceeded'; end if;
  rate := case months when 3 then 5 when 6 then 8 when 12 then 12 else 18 end;
  total := round(amount * (1 + rate/100.0));
  insert into public.game_wallets(user_id) values(me) on conflict(user_id) do nothing;
  update public.game_wallets set balance=balance+amount,updated_at=now() where user_id=me;
  insert into public.game_loans(user_id,principal,rate_percent,term_months,total_due,remaining)
  values(me,amount,rate,months,total,total) returning id into lid;
  return lid;
end $$;

create or replace function public.repay_demo_loan(loan_id uuid, amount bigint)
returns bigint language plpgsql security definer set search_path=public as $$
declare
  me uuid:=auth.uid();
  rem bigint;
  bal bigint;
  pay bigint;
begin
  if me is null then raise exception 'not authenticated'; end if;
  select remaining into rem from public.game_loans where id=loan_id and user_id=me and status='active' for update;
  if rem is null then raise exception 'active loan not found'; end if;
  select balance into bal from public.game_wallets where user_id=me for update;
  if amount <= 0 then raise exception 'invalid amount'; end if;
  pay:=least(amount,rem);
  if bal < pay then raise exception 'not enough demo balance'; end if;
  update public.game_wallets set balance=balance-pay,updated_at=now() where user_id=me;
  update public.game_loans set remaining=remaining-pay,status=case when remaining-pay<=0 then 'paid' else 'active' end where id=loan_id;
  return rem-pay;
end $$;

create or replace function public.buy_demo_property(property uuid)
returns void language plpgsql security definer set search_path=public as $$
declare
  me uuid:=auth.uid();
  p bigint;
  bal bigint;
begin
  if me is null then raise exception 'not authenticated'; end if;
  select price into p from public.demo_properties where id=property;
  if p is null then raise exception 'property not found'; end if;
  if exists(select 1 from public.owned_properties where user_id=me and property_id=property) then raise exception 'already owned'; end if;
  insert into public.game_wallets(user_id) values(me) on conflict(user_id) do nothing;
  select balance into bal from public.game_wallets where user_id=me for update;
  if bal < p then raise exception 'not enough demo balance'; end if;
  update public.game_wallets set balance=balance-p,updated_at=now() where user_id=me;
  insert into public.owned_properties(user_id,property_id,bought_price) values(me,property,p);
end $$;

grant execute on function public.take_demo_loan(bigint,int) to authenticated;
grant execute on function public.repay_demo_loan(uuid,bigint) to authenticated;
grant execute on function public.buy_demo_property(uuid) to authenticated;

-- Realtime for clips/market where useful.
do $$
begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='clips') then alter publication supabase_realtime add table public.clips; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='clip_comments') then alter publication supabase_realtime add table public.clip_comments; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='clip_likes') then alter publication supabase_realtime add table public.clip_likes; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='marketplace_listings') then alter publication supabase_realtime add table public.marketplace_listings; end if;
end $$;

-- ===== V20 UPGRADE =====

-- RNDM Chat v20 upgrade
-- Run in Supabase SQL Editor AFTER the v18 schema.
-- Adds real Clips publishing, marketplace, and a DEMO/game economy.

create extension if not exists pgcrypto;

-- ---------------- REAL CLIPS ----------------
create table if not exists public.clips (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  video_url text not null,
  caption text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.clip_likes (
  clip_id uuid not null references public.clips(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (clip_id, user_id)
);

create table if not exists public.clip_comments (
  id bigint generated by default as identity primary key,
  clip_id uuid not null references public.clips(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);

create index if not exists clips_created_idx on public.clips(created_at desc);
create index if not exists clip_comments_clip_idx on public.clip_comments(clip_id, created_at);

alter table public.clips enable row level security;
alter table public.clip_likes enable row level security;
alter table public.clip_comments enable row level security;

drop policy if exists clips_read on public.clips;
create policy clips_read on public.clips for select to authenticated using (true);
drop policy if exists clips_insert on public.clips;
create policy clips_insert on public.clips for insert to authenticated with check (user_id = auth.uid());
drop policy if exists clips_delete on public.clips;
create policy clips_delete on public.clips for delete to authenticated using (user_id = auth.uid());

drop policy if exists clip_likes_read on public.clip_likes;
create policy clip_likes_read on public.clip_likes for select to authenticated using (true);
drop policy if exists clip_likes_insert on public.clip_likes;
create policy clip_likes_insert on public.clip_likes for insert to authenticated with check (user_id = auth.uid());
drop policy if exists clip_likes_delete on public.clip_likes;
create policy clip_likes_delete on public.clip_likes for delete to authenticated using (user_id = auth.uid());

drop policy if exists clip_comments_read on public.clip_comments;
create policy clip_comments_read on public.clip_comments for select to authenticated using (true);
drop policy if exists clip_comments_insert on public.clip_comments;
create policy clip_comments_insert on public.clip_comments for insert to authenticated with check (user_id = auth.uid());
drop policy if exists clip_comments_delete on public.clip_comments;
create policy clip_comments_delete on public.clip_comments for delete to authenticated using (user_id = auth.uid());

grant select,insert,delete on public.clips to authenticated;
grant select,insert,delete on public.clip_likes to authenticated;
grant select,insert,delete on public.clip_comments to authenticated;

insert into storage.buckets(id,name,public,file_size_limit)
values('clips','clips',true,104857600)
on conflict(id) do update set public=true,file_size_limit=104857600;

drop policy if exists clips_storage_upload on storage.objects;
create policy clips_storage_upload on storage.objects for insert to authenticated
with check(bucket_id='clips' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists clips_storage_delete on storage.objects;
create policy clips_storage_delete on storage.objects for delete to authenticated
using(bucket_id='clips' and owner_id=auth.uid()::text);

-- ---------------- RNDM MARKET ----------------
create table if not exists public.marketplace_listings (
  id uuid primary key default gen_random_uuid(),
  seller_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check(char_length(title) between 2 and 120),
  description text not null default '',
  category text not null default 'Другое',
  price bigint not null default 0 check(price >= 0),
  city text not null default '',
  image_url text,
  status text not null default 'active' check(status in ('active','sold','hidden')),
  created_at timestamptz not null default now()
);
create index if not exists market_created_idx on public.marketplace_listings(created_at desc);

create table if not exists public.marketplace_favorites (
  listing_id uuid not null references public.marketplace_listings(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(listing_id,user_id)
);

alter table public.marketplace_listings enable row level security;
alter table public.marketplace_favorites enable row level security;

drop policy if exists market_read on public.marketplace_listings;
create policy market_read on public.marketplace_listings for select to authenticated using(status <> 'hidden' or seller_id=auth.uid());
drop policy if exists market_insert on public.marketplace_listings;
create policy market_insert on public.marketplace_listings for insert to authenticated with check(seller_id=auth.uid());
drop policy if exists market_update on public.marketplace_listings;
create policy market_update on public.marketplace_listings for update to authenticated using(seller_id=auth.uid()) with check(seller_id=auth.uid());
drop policy if exists market_delete on public.marketplace_listings;
create policy market_delete on public.marketplace_listings for delete to authenticated using(seller_id=auth.uid());

drop policy if exists market_fav_read on public.marketplace_favorites;
create policy market_fav_read on public.marketplace_favorites for select to authenticated using(user_id=auth.uid());
drop policy if exists market_fav_insert on public.marketplace_favorites;
create policy market_fav_insert on public.marketplace_favorites for insert to authenticated with check(user_id=auth.uid());
drop policy if exists market_fav_delete on public.marketplace_favorites;
create policy market_fav_delete on public.marketplace_favorites for delete to authenticated using(user_id=auth.uid());

grant select,insert,update,delete on public.marketplace_listings to authenticated;
grant select,insert,delete on public.marketplace_favorites to authenticated;

insert into storage.buckets(id,name,public,file_size_limit)
values('market-files','market-files',true,20971520)
on conflict(id) do update set public=true,file_size_limit=20971520;

drop policy if exists market_storage_upload on storage.objects;
create policy market_storage_upload on storage.objects for insert to authenticated
with check(bucket_id='market-files' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists market_storage_delete on storage.objects;
create policy market_storage_delete on storage.objects for delete to authenticated
using(bucket_id='market-files' and owner_id=auth.uid()::text);

-- ---------------- GAME WALLET / LOANS / APARTMENTS ----------------
-- Everything in this section is virtual game currency. It is NOT a real loan or payment system.
create table if not exists public.game_wallets (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  balance bigint not null default 1500000 check(balance >= 0),
  updated_at timestamptz not null default now()
);

insert into public.game_wallets(user_id)
select id from public.profiles
on conflict(user_id) do nothing;

create or replace function public.ensure_game_wallet()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.game_wallets(user_id) values(new.id) on conflict(user_id) do nothing;
  return new;
end $$;

drop trigger if exists on_profile_game_wallet on public.profiles;
create trigger on_profile_game_wallet after insert on public.profiles
for each row execute function public.ensure_game_wallet();

create table if not exists public.game_loans (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  principal bigint not null check(principal > 0),
  rate_percent numeric(6,2) not null,
  term_months int not null,
  total_due bigint not null,
  remaining bigint not null,
  status text not null default 'active' check(status in ('active','paid')),
  created_at timestamptz not null default now()
);

create table if not exists public.demo_properties (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  city text not null,
  district text not null default '',
  price bigint not null check(price > 0),
  rooms int not null default 1,
  area numeric(7,1) not null default 30,
  emoji text not null default '🏠',
  description text not null default ''
);

create table if not exists public.owned_properties (
  user_id uuid not null references public.profiles(id) on delete cascade,
  property_id uuid not null references public.demo_properties(id) on delete cascade,
  bought_at timestamptz not null default now(),
  bought_price bigint not null,
  primary key(user_id,property_id)
);

insert into public.demo_properties(title,city,district,price,rooms,area,emoji,description)
select * from (values
 ('Студия у парка','Москва','Северное Бутово',2350000::bigint,1,24.5::numeric,'🌆','Компактная игровая квартира рядом с парком.'),
 ('Однокомнатная','Москва','Южное Бутово',3900000::bigint,1,38.2::numeric,'🏢','Светлая квартира с большой кухней.'),
 ('Двухкомнатная семейная','Москва','Чертаново',6200000::bigint,2,57.8::numeric,'🏙️','Две комнаты и игровая лоджия.'),
 ('Лофт в центре','Москва','Центр',9800000::bigint,2,71.0::numeric,'🌃','Игровой лофт с панорамными окнами.'),
 ('Загородный дом','Подольск','Волищево',12500000::bigint,4,146.0::numeric,'🏡','Дом с виртуальным участком и гаражом.'),
 ('Пентхаус RNDM','Москва','Москва-Сити',30000000::bigint,5,220.0::numeric,'✨','Самая дорогая коллекционная недвижимость RNDM.')
) as v(title,city,district,price,rooms,area,emoji,description)
where not exists(select 1 from public.demo_properties);

alter table public.game_wallets enable row level security;
alter table public.game_loans enable row level security;
alter table public.demo_properties enable row level security;
alter table public.owned_properties enable row level security;

drop policy if exists wallet_read on public.game_wallets;
create policy wallet_read on public.game_wallets for select to authenticated using(user_id=auth.uid());
drop policy if exists loans_read on public.game_loans;
create policy loans_read on public.game_loans for select to authenticated using(user_id=auth.uid());
drop policy if exists properties_read on public.demo_properties;
create policy properties_read on public.demo_properties for select to authenticated using(true);
drop policy if exists owned_read on public.owned_properties;
create policy owned_read on public.owned_properties for select to authenticated using(user_id=auth.uid());

grant select on public.game_wallets to authenticated;
grant select on public.game_loans to authenticated;
grant select on public.demo_properties to authenticated;
grant select on public.owned_properties to authenticated;

create or replace function public.take_demo_loan(amount bigint, months int)
returns uuid language plpgsql security definer set search_path=public as $$
declare
  me uuid:=auth.uid();
  rate numeric(6,2);
  total bigint;
  lid uuid;
  active_debt bigint;
begin
  if me is null then raise exception 'not authenticated'; end if;
  if amount < 10000 or amount > 5000000 then raise exception 'amount must be from 10000 to 5000000'; end if;
  if months not in (3,6,12,24) then raise exception 'term must be 3, 6, 12 or 24 months'; end if;
  select coalesce(sum(remaining),0) into active_debt from public.game_loans where user_id=me and status='active';
  if active_debt + amount > 7000000 then raise exception 'demo credit limit exceeded'; end if;
  rate := case months when 3 then 5 when 6 then 8 when 12 then 12 else 18 end;
  total := round(amount * (1 + rate/100.0));
  insert into public.game_wallets(user_id) values(me) on conflict(user_id) do nothing;
  update public.game_wallets set balance=balance+amount,updated_at=now() where user_id=me;
  insert into public.game_loans(user_id,principal,rate_percent,term_months,total_due,remaining)
  values(me,amount,rate,months,total,total) returning id into lid;
  return lid;
end $$;

create or replace function public.repay_demo_loan(loan_id uuid, amount bigint)
returns bigint language plpgsql security definer set search_path=public as $$
declare
  me uuid:=auth.uid();
  rem bigint;
  bal bigint;
  pay bigint;
begin
  if me is null then raise exception 'not authenticated'; end if;
  select remaining into rem from public.game_loans where id=loan_id and user_id=me and status='active' for update;
  if rem is null then raise exception 'active loan not found'; end if;
  select balance into bal from public.game_wallets where user_id=me for update;
  if amount <= 0 then raise exception 'invalid amount'; end if;
  pay:=least(amount,rem);
  if bal < pay then raise exception 'not enough demo balance'; end if;
  update public.game_wallets set balance=balance-pay,updated_at=now() where user_id=me;
  update public.game_loans set remaining=remaining-pay,status=case when remaining-pay<=0 then 'paid' else 'active' end where id=loan_id;
  return rem-pay;
end $$;

create or replace function public.buy_demo_property(property uuid)
returns void language plpgsql security definer set search_path=public as $$
declare
  me uuid:=auth.uid();
  p bigint;
  bal bigint;
begin
  if me is null then raise exception 'not authenticated'; end if;
  select price into p from public.demo_properties where id=property;
  if p is null then raise exception 'property not found'; end if;
  if exists(select 1 from public.owned_properties where user_id=me and property_id=property) then raise exception 'already owned'; end if;
  insert into public.game_wallets(user_id) values(me) on conflict(user_id) do nothing;
  select balance into bal from public.game_wallets where user_id=me for update;
  if bal < p then raise exception 'not enough demo balance'; end if;
  update public.game_wallets set balance=balance-p,updated_at=now() where user_id=me;
  insert into public.owned_properties(user_id,property_id,bought_price) values(me,property,p);
end $$;

grant execute on function public.take_demo_loan(bigint,int) to authenticated;
grant execute on function public.repay_demo_loan(uuid,bigint) to authenticated;
grant execute on function public.buy_demo_property(uuid) to authenticated;

-- Realtime for clips/market where useful.
do $$
begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='clips') then alter publication supabase_realtime add table public.clips; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='clip_comments') then alter publication supabase_realtime add table public.clip_comments; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='clip_likes') then alter publication supabase_realtime add table public.clip_likes; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='marketplace_listings') then alter publication supabase_realtime add table public.marketplace_listings; end if;
end $$;

-- ===== V22 UPGRADE =====

-- RNDM Chat v22 Supabase upgrade
-- Run AFTER supabase_schema.sql and supabase_v20_upgrade.sql.
-- Adds cloud state sync, real Channels and real RNDM Video.

create extension if not exists pgcrypto;

-- =========================================================
-- 1) CROSS-DEVICE USER STATE (cat, XP, stars, settings, etc.)
-- =========================================================
create table if not exists public.user_state (
  user_id uuid not null references public.profiles(id) on delete cascade,
  key text not null,
  value jsonb not null default 'null'::jsonb,
  updated_at timestamptz not null default now(),
  primary key(user_id,key)
);

alter table public.user_state enable row level security;

drop policy if exists user_state_read_own on public.user_state;
create policy user_state_read_own on public.user_state
for select to authenticated using(user_id=auth.uid());

drop policy if exists user_state_insert_own on public.user_state;
create policy user_state_insert_own on public.user_state
for insert to authenticated with check(user_id=auth.uid());

drop policy if exists user_state_update_own on public.user_state;
create policy user_state_update_own on public.user_state
for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

drop policy if exists user_state_delete_own on public.user_state;
create policy user_state_delete_own on public.user_state
for delete to authenticated using(user_id=auth.uid());

grant select,insert,update,delete on public.user_state to authenticated;

-- =========================================================
-- 2) REAL CHANNELS
-- =========================================================
create table if not exists public.rndm_channels (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  name text not null check(char_length(name) between 2 and 80),
  handle text unique,
  description text not null default '',
  emoji text not null default '📡',
  avatar_url text,
  promo_subscribers integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.rndm_channel_subscriptions (
  channel_id uuid not null references public.rndm_channels(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(channel_id,user_id)
);

create table if not exists public.rndm_channel_posts (
  id uuid primary key default gen_random_uuid(),
  channel_id uuid not null references public.rndm_channels(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  body text not null default '',
  attachment_url text,
  attachment_type text,
  attachment_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.rndm_channel_comments (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.rndm_channel_posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check(char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);

create table if not exists public.rndm_channel_reactions (
  post_id uuid not null references public.rndm_channel_posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  emoji text not null default '❤️',
  created_at timestamptz not null default now(),
  primary key(post_id,user_id,emoji)
);

create index if not exists rndm_channels_created_idx on public.rndm_channels(created_at desc);
create index if not exists rndm_posts_channel_idx on public.rndm_channel_posts(channel_id,created_at desc);
create index if not exists rndm_comments_post_idx on public.rndm_channel_comments(post_id,created_at);

create or replace function public.is_channel_owner(cid uuid, uid uuid default auth.uid())
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.rndm_channels where id=cid and owner_id=uid)
$$;

alter table public.rndm_channels enable row level security;
alter table public.rndm_channel_subscriptions enable row level security;
alter table public.rndm_channel_posts enable row level security;
alter table public.rndm_channel_comments enable row level security;
alter table public.rndm_channel_reactions enable row level security;

drop policy if exists rndm_channels_read on public.rndm_channels;
create policy rndm_channels_read on public.rndm_channels for select to authenticated using(true);
drop policy if exists rndm_channels_insert on public.rndm_channels;
create policy rndm_channels_insert on public.rndm_channels for insert to authenticated with check(owner_id=auth.uid());
drop policy if exists rndm_channels_update on public.rndm_channels;
create policy rndm_channels_update on public.rndm_channels for update to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
drop policy if exists rndm_channels_delete on public.rndm_channels;
create policy rndm_channels_delete on public.rndm_channels for delete to authenticated using(owner_id=auth.uid());

drop policy if exists rndm_channel_sub_read on public.rndm_channel_subscriptions;
create policy rndm_channel_sub_read on public.rndm_channel_subscriptions for select to authenticated using(true);
drop policy if exists rndm_channel_sub_insert on public.rndm_channel_subscriptions;
create policy rndm_channel_sub_insert on public.rndm_channel_subscriptions for insert to authenticated with check(user_id=auth.uid());
drop policy if exists rndm_channel_sub_delete on public.rndm_channel_subscriptions;
create policy rndm_channel_sub_delete on public.rndm_channel_subscriptions for delete to authenticated using(user_id=auth.uid());

drop policy if exists rndm_posts_read on public.rndm_channel_posts;
create policy rndm_posts_read on public.rndm_channel_posts for select to authenticated using(true);
drop policy if exists rndm_posts_insert on public.rndm_channel_posts;
create policy rndm_posts_insert on public.rndm_channel_posts for insert to authenticated
with check(author_id=auth.uid() and public.is_channel_owner(channel_id));
drop policy if exists rndm_posts_update on public.rndm_channel_posts;
create policy rndm_posts_update on public.rndm_channel_posts for update to authenticated
using(author_id=auth.uid()) with check(author_id=auth.uid());
drop policy if exists rndm_posts_delete on public.rndm_channel_posts;
create policy rndm_posts_delete on public.rndm_channel_posts for delete to authenticated using(author_id=auth.uid());

drop policy if exists rndm_comments_read on public.rndm_channel_comments;
create policy rndm_comments_read on public.rndm_channel_comments for select to authenticated using(true);
drop policy if exists rndm_comments_insert on public.rndm_channel_comments;
create policy rndm_comments_insert on public.rndm_channel_comments for insert to authenticated with check(user_id=auth.uid());
drop policy if exists rndm_comments_delete on public.rndm_channel_comments;
create policy rndm_comments_delete on public.rndm_channel_comments for delete to authenticated using(user_id=auth.uid());

drop policy if exists rndm_reactions_read on public.rndm_channel_reactions;
create policy rndm_reactions_read on public.rndm_channel_reactions for select to authenticated using(true);
drop policy if exists rndm_reactions_insert on public.rndm_channel_reactions;
create policy rndm_reactions_insert on public.rndm_channel_reactions for insert to authenticated with check(user_id=auth.uid());
drop policy if exists rndm_reactions_delete on public.rndm_channel_reactions;
create policy rndm_reactions_delete on public.rndm_channel_reactions for delete to authenticated using(user_id=auth.uid());

grant select,insert,update,delete on public.rndm_channels to authenticated;
grant select,insert,delete on public.rndm_channel_subscriptions to authenticated;
grant select,insert,update,delete on public.rndm_channel_posts to authenticated;
grant select,insert,delete on public.rndm_channel_comments to authenticated;
grant select,insert,delete on public.rndm_channel_reactions to authenticated;

insert into storage.buckets(id,name,public,file_size_limit)
values('channel-files','channel-files',true,52428800)
on conflict(id) do update set public=true,file_size_limit=52428800;

drop policy if exists channel_files_upload on storage.objects;
create policy channel_files_upload on storage.objects for insert to authenticated
with check(bucket_id='channel-files' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists channel_files_delete on storage.objects;
create policy channel_files_delete on storage.objects for delete to authenticated
using(bucket_id='channel-files' and owner_id=auth.uid()::text);

-- =========================================================
-- 3) REAL RNDM VIDEO (YouTube-like section)
-- =========================================================
create table if not exists public.rndm_videos (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check(char_length(title) between 1 and 120),
  description text not null default '',
  video_url text not null,
  view_count bigint not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.rndm_video_likes (
  video_id uuid not null references public.rndm_videos(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(video_id,user_id)
);

create table if not exists public.rndm_video_comments (
  id bigint generated by default as identity primary key,
  video_id uuid not null references public.rndm_videos(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check(char_length(body) between 1 and 2000),
  created_at timestamptz not null default now()
);

create table if not exists public.rndm_follows (
  follower_id uuid not null references public.profiles(id) on delete cascade,
  followee_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(follower_id,followee_id),
  check(follower_id<>followee_id)
);

create index if not exists rndm_videos_created_idx on public.rndm_videos(created_at desc);
create index if not exists rndm_video_comments_idx on public.rndm_video_comments(video_id,created_at);

alter table public.rndm_videos enable row level security;
alter table public.rndm_video_likes enable row level security;
alter table public.rndm_video_comments enable row level security;
alter table public.rndm_follows enable row level security;

drop policy if exists rndm_videos_read on public.rndm_videos;
create policy rndm_videos_read on public.rndm_videos for select to authenticated using(true);
drop policy if exists rndm_videos_insert on public.rndm_videos;
create policy rndm_videos_insert on public.rndm_videos for insert to authenticated with check(user_id=auth.uid());
drop policy if exists rndm_videos_update on public.rndm_videos;
create policy rndm_videos_update on public.rndm_videos for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists rndm_videos_delete on public.rndm_videos;
create policy rndm_videos_delete on public.rndm_videos for delete to authenticated using(user_id=auth.uid());

drop policy if exists rndm_video_likes_read on public.rndm_video_likes;
create policy rndm_video_likes_read on public.rndm_video_likes for select to authenticated using(true);
drop policy if exists rndm_video_likes_insert on public.rndm_video_likes;
create policy rndm_video_likes_insert on public.rndm_video_likes for insert to authenticated with check(user_id=auth.uid());
drop policy if exists rndm_video_likes_delete on public.rndm_video_likes;
create policy rndm_video_likes_delete on public.rndm_video_likes for delete to authenticated using(user_id=auth.uid());

drop policy if exists rndm_video_comments_read on public.rndm_video_comments;
create policy rndm_video_comments_read on public.rndm_video_comments for select to authenticated using(true);
drop policy if exists rndm_video_comments_insert on public.rndm_video_comments;
create policy rndm_video_comments_insert on public.rndm_video_comments for insert to authenticated with check(user_id=auth.uid());
drop policy if exists rndm_video_comments_delete on public.rndm_video_comments;
create policy rndm_video_comments_delete on public.rndm_video_comments for delete to authenticated using(user_id=auth.uid());

drop policy if exists rndm_follows_read on public.rndm_follows;
create policy rndm_follows_read on public.rndm_follows for select to authenticated using(true);
drop policy if exists rndm_follows_insert on public.rndm_follows;
create policy rndm_follows_insert on public.rndm_follows for insert to authenticated with check(follower_id=auth.uid());
drop policy if exists rndm_follows_delete on public.rndm_follows;
create policy rndm_follows_delete on public.rndm_follows for delete to authenticated using(follower_id=auth.uid());

grant select,insert,update,delete on public.rndm_videos to authenticated;
grant select,insert,delete on public.rndm_video_likes to authenticated;
grant select,insert,delete on public.rndm_video_comments to authenticated;
grant select,insert,delete on public.rndm_follows to authenticated;

create or replace function public.increment_rndm_video_view(video uuid)
returns void language plpgsql security definer set search_path=public as $$
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  update public.rndm_videos set view_count=view_count+1 where id=video;
end $$;
grant execute on function public.increment_rndm_video_view(uuid) to authenticated;

insert into storage.buckets(id,name,public,file_size_limit)
values('videos','videos',true,262144000)
on conflict(id) do update set public=true,file_size_limit=262144000;

drop policy if exists rndm_videos_storage_upload on storage.objects;
create policy rndm_videos_storage_upload on storage.objects for insert to authenticated
with check(bucket_id='videos' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists rndm_videos_storage_delete on storage.objects;
create policy rndm_videos_storage_delete on storage.objects for delete to authenticated
using(bucket_id='videos' and owner_id=auth.uid()::text);

-- =========================================================
-- 4) Realtime for new social content
-- =========================================================
DO $$
begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='rndm_channel_posts') then
    alter publication supabase_realtime add table public.rndm_channel_posts;
  end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='rndm_channel_comments') then
    alter publication supabase_realtime add table public.rndm_channel_comments;
  end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='rndm_videos') then
    alter publication supabase_realtime add table public.rndm_videos;
  end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='rndm_video_comments') then
    alter publication supabase_realtime add table public.rndm_video_comments;
  end if;
end $$;


-- RNDM Chat v23 — REAL RANDOM CHAT / MATCHMAKING
-- Run AFTER v22 (or use supabase_FULL_v23.sql on a fresh database).

create table if not exists public.random_queue (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  status text not null default 'waiting' check(status in ('waiting','matched')),
  matched_user_id uuid references public.profiles(id) on delete set null,
  conversation_id uuid references public.conversations(id) on delete set null,
  joined_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists random_queue_status_idx on public.random_queue(status,updated_at);

alter table public.random_queue enable row level security;

drop policy if exists random_queue_read_own on public.random_queue;
create policy random_queue_read_own on public.random_queue
for select to authenticated using(user_id=auth.uid());

grant select on public.random_queue to authenticated;

create or replace function public.random_chat_join()
returns table(match_status text, conversation_id uuid, matched_user_id uuid)
language plpgsql
security definer
set search_path=public
as $$
declare
  me uuid := auth.uid();
  other_user uuid;
  cid uuid;
  existing public.random_queue%rowtype;
begin
  if me is null then raise exception 'not authenticated'; end if;

  -- Serialize matchmaking to avoid two users being matched twice at the same moment.
  perform pg_advisory_xact_lock(83920417);

  -- Old abandoned searches stop participating automatically.
  delete from public.random_queue
  where (status='waiting' and updated_at < now() - interval '3 minutes')
     or (status='matched' and updated_at < now() - interval '15 minutes');

  select * into existing from public.random_queue where user_id=me;
  if found and existing.status='matched' and existing.conversation_id is not null then
    return query select 'matched'::text, existing.conversation_id, existing.matched_user_id;
    return;
  end if;

  insert into public.random_queue(user_id,status,matched_user_id,conversation_id,joined_at,updated_at)
  values(me,'waiting',null,null,now(),now())
  on conflict(user_id) do update set
    status='waiting', matched_user_id=null, conversation_id=null, joined_at=now(), updated_at=now();

  select q.user_id into other_user
  from public.random_queue q
  where q.user_id<>me
    and q.status='waiting'
    and q.updated_at >= now() - interval '3 minutes'
    and not exists (
      select 1 from public.friendships f
      where f.status='blocked'
        and ((f.requester=me and f.addressee=q.user_id) or (f.requester=q.user_id and f.addressee=me))
    )
  order by q.joined_at asc
  limit 1;

  if other_user is null then
    return query select 'waiting'::text, null::uuid, null::uuid;
    return;
  end if;

  cid := public.get_or_create_direct(other_user);

  update public.random_queue set
    status='matched', matched_user_id=other_user, conversation_id=cid, updated_at=now()
  where user_id=me;

  update public.random_queue set
    status='matched', matched_user_id=me, conversation_id=cid, updated_at=now()
  where user_id=other_user;

  return query select 'matched'::text, cid, other_user;
end $$;

create or replace function public.random_chat_leave()
returns void
language plpgsql
security definer
set search_path=public
as $$
begin
  if auth.uid() is null then return; end if;
  delete from public.random_queue where user_id=auth.uid();
end $$;

create or replace function public.random_waiting_count()
returns bigint
language sql
stable
security definer
set search_path=public
as $$
  select count(*)::bigint from public.random_queue
  where status='waiting' and updated_at >= now() - interval '3 minutes';
$$;

grant execute on function public.random_chat_join() to authenticated;
grant execute on function public.random_chat_leave() to authenticated;
grant execute on function public.random_waiting_count() to authenticated;

DO $$
begin
  if not exists(
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='random_queue'
  ) then
    alter publication supabase_realtime add table public.random_queue;
  end if;
end $$;


-- RNDM Chat v24 MEGA + Admin Center
-- Run AFTER supabase_FULL_v23.sql (or after v22 + v23 upgrades).
-- Safe to run more than once.

create extension if not exists pgcrypto;

-- =========================================================
-- 1) ROLES / BADGES / MODERATION FIELDS
-- =========================================================
alter table public.profiles add column if not exists app_role text not null default 'user';
alter table public.profiles add column if not exists is_verified boolean not null default false;
alter table public.profiles add column if not exists is_premium boolean not null default false;
alter table public.profiles add column if not exists is_banned boolean not null default false;
alter table public.profiles add column if not exists ban_reason text not null default '';
alter table public.profiles add column if not exists banned_until timestamptz;
alter table public.profiles add column if not exists reputation integer not null default 100;
alter table public.profiles add column if not exists xp bigint not null default 0;
alter table public.profiles add column if not exists stars bigint not null default 0;
alter table public.profiles add column if not exists cover_url text;
alter table public.profiles add column if not exists profile_music_url text;

-- Prevent users from modifying staff/system fields directly through the browser.
revoke update on public.profiles from authenticated;
grant update(username,display_name,avatar_url,bio,status,last_seen,cover_url,profile_music_url) on public.profiles to authenticated;

create or replace function public.role_rank(r text)
returns integer language sql immutable as $$
  select case lower(coalesce(r,'user'))
    when 'owner' then 50
    when 'admin' then 40
    when 'moderator' then 30
    when 'verified' then 20
    when 'premium' then 10
    else 0 end;
$$;

create or replace function public.is_staff(uid uuid default auth.uid())
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles p where p.id=uid and p.app_role in ('owner','admin','moderator'));
$$;

create or replace function public.is_admin(uid uuid default auth.uid())
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles p where p.id=uid and p.app_role in ('owner','admin'));
$$;

grant execute on function public.is_staff(uuid) to authenticated;
grant execute on function public.is_admin(uuid) to authenticated;

create table if not exists public.admin_audit (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  target_user_id uuid references public.profiles(id) on delete set null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  target_user_id uuid references public.profiles(id) on delete set null,
  content_type text not null default 'user',
  content_id text,
  reason text not null,
  details text not null default '',
  status text not null default 'open' check(status in ('open','reviewing','resolved','rejected')),
  moderator_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

alter table public.admin_audit enable row level security;
alter table public.reports enable row level security;

drop policy if exists reports_insert on public.reports;
create policy reports_insert on public.reports for insert to authenticated with check(reporter_id=auth.uid());
drop policy if exists reports_read_self_or_staff on public.reports;
create policy reports_read_self_or_staff on public.reports for select to authenticated using(reporter_id=auth.uid() or public.is_staff());
drop policy if exists audit_read_staff on public.admin_audit;
create policy audit_read_staff on public.admin_audit for select to authenticated using(public.is_staff());

grant select on public.admin_audit to authenticated;
grant select,insert on public.reports to authenticated;

create or replace function public.admin_log(act text, target uuid, payload jsonb default '{}'::jsonb)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.is_staff() then raise exception 'admin required'; end if;
  insert into public.admin_audit(actor_id,target_user_id,action,details) values(auth.uid(),target,act,coalesce(payload,'{}'::jsonb));
end $$;

create or replace function public.admin_set_role(target uuid, new_role text)
returns void language plpgsql security definer set search_path=public as $$
declare me_role text; target_role text;
begin
  select app_role into me_role from public.profiles where id=auth.uid();
  select app_role into target_role from public.profiles where id=target;
  if me_role not in ('owner','admin') then raise exception 'admin required'; end if;
  if new_role not in ('user','premium','verified','moderator','admin','owner') then raise exception 'invalid role'; end if;
  if me_role <> 'owner' and (new_role in ('owner','admin') or target_role in ('owner','admin')) then raise exception 'owner required'; end if;
  if target=auth.uid() and me_role='owner' and new_role<>'owner' then raise exception 'owner cannot demote self'; end if;
  update public.profiles set app_role=new_role where id=target;
  perform public.admin_log('set_role',target,jsonb_build_object('role',new_role));
end $$;

create or replace function public.admin_set_badges(target uuid, verified boolean, premium boolean)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.is_admin() then raise exception 'admin required'; end if;
  update public.profiles set is_verified=verified,is_premium=premium where id=target;
  perform public.admin_log('set_badges',target,jsonb_build_object('verified',verified,'premium',premium));
end $$;

create or replace function public.admin_ban_user(target uuid, reason text, hours integer default 0)
returns void language plpgsql security definer set search_path=public as $$
declare me_role text; target_role text;
begin
  select app_role into me_role from public.profiles where id=auth.uid();
  select app_role into target_role from public.profiles where id=target;
  if me_role not in ('owner','admin','moderator') then raise exception 'staff required'; end if;
  if public.role_rank(me_role) <= public.role_rank(target_role) then raise exception 'cannot ban equal/higher role'; end if;
  update public.profiles set is_banned=true,ban_reason=left(coalesce(reason,''),500),banned_until=case when coalesce(hours,0)>0 then now()+make_interval(hours=>hours) else null end where id=target;
  perform public.admin_log('ban',target,jsonb_build_object('reason',reason,'hours',hours));
end $$;

create or replace function public.admin_unban_user(target uuid)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.is_staff() then raise exception 'staff required'; end if;
  update public.profiles set is_banned=false,ban_reason='',banned_until=null where id=target;
  perform public.admin_log('unban',target,'{}'::jsonb);
end $$;

create or replace function public.admin_adjust_stars(target uuid, delta bigint)
returns bigint language plpgsql security definer set search_path=public as $$
declare v bigint;
begin
  if not public.is_admin() then raise exception 'admin required'; end if;
  update public.profiles set stars=greatest(0,stars+delta) where id=target returning stars into v;
  perform public.admin_log('adjust_stars',target,jsonb_build_object('delta',delta,'new',v));
  return v;
end $$;

create or replace function public.admin_adjust_xp(target uuid, delta bigint)
returns bigint language plpgsql security definer set search_path=public as $$
declare v bigint;
begin
  if not public.is_admin() then raise exception 'admin required'; end if;
  update public.profiles set xp=greatest(0,xp+delta) where id=target returning xp into v;
  perform public.admin_log('adjust_xp',target,jsonb_build_object('delta',delta,'new',v));
  return v;
end $$;

create or replace function public.admin_adjust_reputation(target uuid, delta integer)
returns integer language plpgsql security definer set search_path=public as $$
declare v integer;
begin
  if not public.is_staff() then raise exception 'staff required'; end if;
  update public.profiles set reputation=greatest(0,least(1000,reputation+delta)) where id=target returning reputation into v;
  perform public.admin_log('adjust_reputation',target,jsonb_build_object('delta',delta,'new',v));
  return v;
end $$;

create or replace function public.admin_adjust_wallet(target uuid, delta bigint)
returns bigint language plpgsql security definer set search_path=public as $$
declare v bigint;
begin
  if not public.is_admin() then raise exception 'admin required'; end if;
  insert into public.game_wallets(user_id,balance) values(target,0) on conflict(user_id) do nothing;
  update public.game_wallets set balance=greatest(0,balance+delta),updated_at=now() where user_id=target returning balance into v;
  perform public.admin_log('adjust_wallet',target,jsonb_build_object('delta',delta,'new',v));
  return v;
end $$;

create or replace function public.submit_report(target uuid, kind text, item text, why text, extra text default '')
returns bigint language plpgsql security definer set search_path=public as $$
declare rid bigint;
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  insert into public.reports(reporter_id,target_user_id,content_type,content_id,reason,details)
  values(auth.uid(),target,left(coalesce(kind,'user'),40),left(item,120),left(coalesce(why,'Другое'),160),left(coalesce(extra,''),2000)) returning id into rid;
  return rid;
end $$;

create or replace function public.admin_resolve_report(report_id bigint, new_status text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.is_staff() then raise exception 'staff required'; end if;
  if new_status not in ('reviewing','resolved','rejected') then raise exception 'invalid status'; end if;
  update public.reports set status=new_status,moderator_id=auth.uid(),resolved_at=case when new_status in ('resolved','rejected') then now() else null end where id=report_id;
  perform public.admin_log('report_'||new_status,null,jsonb_build_object('report_id',report_id));
end $$;

grant execute on function public.admin_set_role(uuid,text) to authenticated;
grant execute on function public.admin_set_badges(uuid,boolean,boolean) to authenticated;
grant execute on function public.admin_ban_user(uuid,text,integer) to authenticated;
grant execute on function public.admin_unban_user(uuid) to authenticated;
grant execute on function public.admin_adjust_stars(uuid,bigint) to authenticated;
grant execute on function public.admin_adjust_xp(uuid,bigint) to authenticated;
grant execute on function public.admin_adjust_reputation(uuid,integer) to authenticated;
grant execute on function public.admin_adjust_wallet(uuid,bigint) to authenticated;
grant execute on function public.submit_report(uuid,text,text,text,text) to authenticated;
grant execute on function public.admin_resolve_report(bigint,text) to authenticated;

-- =========================================================
-- 2) INTERESTS + RANDOM 2.0 FILTERS
-- =========================================================
create table if not exists public.profile_interests (
  user_id uuid not null references public.profiles(id) on delete cascade,
  interest text not null,
  primary key(user_id,interest)
);
alter table public.profile_interests enable row level security;
drop policy if exists interests_read on public.profile_interests;
create policy interests_read on public.profile_interests for select to authenticated using(true);
drop policy if exists interests_own on public.profile_interests;
create policy interests_own on public.profile_interests for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
grant select,insert,delete on public.profile_interests to authenticated;

alter table public.random_queue add column if not exists mode text not null default 'text';
alter table public.random_queue add column if not exists language text not null default 'any';
alter table public.random_queue add column if not exists interest text not null default 'any';

create or replace function public.random_chat_join_v24(p_mode text default 'text', p_language text default 'any', p_interest text default 'any')
returns table(match_status text, conversation_id uuid, matched_user_id uuid)
language plpgsql security definer set search_path=public as $$
declare me uuid:=auth.uid(); other_user uuid; cid uuid; existing public.random_queue%rowtype;
begin
  if me is null then raise exception 'not authenticated'; end if;
  if exists(select 1 from public.profiles where id=me and is_banned and (banned_until is null or banned_until>now())) then raise exception 'account banned'; end if;
  perform pg_advisory_xact_lock(83920417);
  delete from public.random_queue where (status='waiting' and updated_at<now()-interval '3 minutes') or (status='matched' and updated_at<now()-interval '15 minutes');
  select * into existing from public.random_queue where user_id=me;
  if found and existing.status='matched' and existing.conversation_id is not null then return query select 'matched'::text,existing.conversation_id,existing.matched_user_id; return; end if;
  insert into public.random_queue(user_id,status,matched_user_id,conversation_id,joined_at,updated_at,mode,language,interest)
  values(me,'waiting',null,null,now(),now(),coalesce(nullif(p_mode,''),'text'),coalesce(nullif(p_language,''),'any'),coalesce(nullif(p_interest,''),'any'))
  on conflict(user_id) do update set status='waiting',matched_user_id=null,conversation_id=null,joined_at=now(),updated_at=now(),mode=excluded.mode,language=excluded.language,interest=excluded.interest;
  select q.user_id into other_user from public.random_queue q
  join public.profiles pp on pp.id=q.user_id
  where q.user_id<>me and q.status='waiting' and q.updated_at>=now()-interval '3 minutes'
    and not (pp.is_banned and (pp.banned_until is null or pp.banned_until>now()))
    and q.mode=coalesce(nullif(p_mode,''),'text')
    and (p_language='any' or q.language='any' or q.language=p_language)
    and (p_interest='any' or q.interest='any' or q.interest=p_interest)
    and not exists(select 1 from public.friendships f where f.status='blocked' and ((f.requester=me and f.addressee=q.user_id) or (f.requester=q.user_id and f.addressee=me)))
  order by pp.reputation desc,q.joined_at asc limit 1;
  if other_user is null then return query select 'waiting'::text,null::uuid,null::uuid; return; end if;
  cid:=public.get_or_create_direct(other_user);
  update public.random_queue set status='matched',matched_user_id=other_user,conversation_id=cid,updated_at=now() where user_id=me;
  update public.random_queue set status='matched',matched_user_id=me,conversation_id=cid,updated_at=now() where user_id=other_user;
  return query select 'matched'::text,cid,other_user;
end $$;
grant execute on function public.random_chat_join_v24(text,text,text) to authenticated;

-- =========================================================
-- 3) DAILY HUB / ACHIEVEMENTS / LEADERBOARD
-- =========================================================
create table if not exists public.daily_claims (
  user_id uuid not null references public.profiles(id) on delete cascade,
  claim_date date not null default current_date,
  reward_stars integer not null default 0,
  reward_xp integer not null default 0,
  reward_cash bigint not null default 0,
  created_at timestamptz not null default now(),
  primary key(user_id,claim_date)
);
alter table public.daily_claims enable row level security;
drop policy if exists daily_own on public.daily_claims;
create policy daily_own on public.daily_claims for select to authenticated using(user_id=auth.uid());
grant select on public.daily_claims to authenticated;

create or replace function public.claim_daily_reward()
returns table(stars integer,xp integer,cash bigint)
language plpgsql security definer set search_path=public as $$
declare s integer:=15; x integer:=40; c bigint:=750;
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  if exists(select 1 from public.daily_claims where user_id=auth.uid() and claim_date=current_date) then raise exception 'already claimed'; end if;
  insert into public.daily_claims(user_id,reward_stars,reward_xp,reward_cash) values(auth.uid(),s,x,c);
  update public.profiles set stars=stars+s,xp=xp+x where id=auth.uid();
  insert into public.game_wallets(user_id,balance) values(auth.uid(),c) on conflict(user_id) do update set balance=public.game_wallets.balance+excluded.balance,updated_at=now();
  return query select s,x,c;
end $$;
grant execute on function public.claim_daily_reward() to authenticated;

create or replace function public.rndm_leaderboard(limit_count integer default 50)
returns table(user_id uuid,username text,display_name text,avatar_url text,xp bigint,reputation integer,stars bigint,app_role text)
language sql stable security definer set search_path=public as $$
  select p.id,p.username,p.display_name,p.avatar_url,p.xp,p.reputation,p.stars,p.app_role
  from public.profiles p
  where not p.is_banned
  order by p.xp desc,p.reputation desc,p.created_at asc
  limit greatest(1,least(coalesce(limit_count,50),100));
$$;
grant execute on function public.rndm_leaderboard(integer) to authenticated;

-- =========================================================
-- 4) STORIES
-- =========================================================
create table if not exists public.stories (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  media_url text,
  media_type text not null default 'text',
  body text not null default '',
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default now()+interval '24 hours'
);
create table if not exists public.story_views (
  story_id uuid not null references public.stories(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  viewed_at timestamptz not null default now(),
  primary key(story_id,user_id)
);
create table if not exists public.story_reactions (
  story_id uuid not null references public.stories(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  emoji text not null default '❤️',
  created_at timestamptz not null default now(),
  primary key(story_id,user_id)
);
alter table public.stories enable row level security; alter table public.story_views enable row level security; alter table public.story_reactions enable row level security;
drop policy if exists stories_read on public.stories; create policy stories_read on public.stories for select to authenticated using(expires_at>now());
drop policy if exists stories_own on public.stories; create policy stories_own on public.stories for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists story_views_read on public.story_views; create policy story_views_read on public.story_views for select to authenticated using(user_id=auth.uid() or exists(select 1 from public.stories s where s.id=story_id and s.user_id=auth.uid()));
drop policy if exists story_views_insert on public.story_views; create policy story_views_insert on public.story_views for insert to authenticated with check(user_id=auth.uid());
drop policy if exists story_reactions_read on public.story_reactions; create policy story_reactions_read on public.story_reactions for select to authenticated using(true);
drop policy if exists story_reactions_own on public.story_reactions; create policy story_reactions_own on public.story_reactions for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
grant select,insert,delete on public.stories to authenticated; grant select,insert on public.story_views to authenticated; grant select,insert,update,delete on public.story_reactions to authenticated;
insert into storage.buckets(id,name,public,file_size_limit) values('stories','stories',true,52428800) on conflict(id) do update set public=true,file_size_limit=52428800;
drop policy if exists stories_upload on storage.objects; create policy stories_upload on storage.objects for insert to authenticated with check(bucket_id='stories' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists stories_delete on storage.objects; create policy stories_delete on storage.objects for delete to authenticated using(bucket_id='stories' and owner_id=auth.uid()::text);

-- =========================================================
-- 5) EVENTS / RSVP
-- =========================================================
create table if not exists public.rndm_events (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  description text not null default '',
  starts_at timestamptz not null,
  location_text text not null default 'Онлайн',
  max_people integer,
  created_at timestamptz not null default now()
);
create table if not exists public.event_rsvps (
  event_id uuid not null references public.rndm_events(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'going' check(status in ('going','maybe','no')),
  created_at timestamptz not null default now(),
  primary key(event_id,user_id)
);
alter table public.rndm_events enable row level security; alter table public.event_rsvps enable row level security;
drop policy if exists events_read on public.rndm_events; create policy events_read on public.rndm_events for select to authenticated using(true);
drop policy if exists events_own on public.rndm_events; create policy events_own on public.rndm_events for all to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
drop policy if exists rsvp_read on public.event_rsvps; create policy rsvp_read on public.event_rsvps for select to authenticated using(true);
drop policy if exists rsvp_own on public.event_rsvps; create policy rsvp_own on public.event_rsvps for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
grant select,insert,update,delete on public.rndm_events to authenticated; grant select,insert,update,delete on public.event_rsvps to authenticated;

-- =========================================================
-- 6) NOTIFICATIONS
-- =========================================================
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  kind text not null default 'system',
  title text not null,
  body text not null default '',
  link text,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);
alter table public.notifications enable row level security;
drop policy if exists notif_own_read on public.notifications; create policy notif_own_read on public.notifications for select to authenticated using(user_id=auth.uid());
drop policy if exists notif_own_update on public.notifications; create policy notif_own_update on public.notifications for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
grant select,update on public.notifications to authenticated;

create or replace function public.admin_notify_user(target uuid, ttl text, msg text, lnk text default null)
returns bigint language plpgsql security definer set search_path=public as $$
declare nid bigint;
begin
  if not public.is_staff() then raise exception 'staff required'; end if;
  insert into public.notifications(user_id,kind,title,body,link) values(target,'admin',left(ttl,120),left(coalesce(msg,''),1000),left(lnk,250)) returning id into nid;
  perform public.admin_log('notify',target,jsonb_build_object('notification_id',nid,'title',ttl));
  return nid;
end $$;
grant execute on function public.admin_notify_user(uuid,text,text,text) to authenticated;

-- Realtime additions
DO $$
begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='stories') then alter publication supabase_realtime add table public.stories; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='rndm_events') then alter publication supabase_realtime add table public.rndm_events; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='notifications') then alter publication supabase_realtime add table public.notifications; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='reports') then alter publication supabase_realtime add table public.reports; end if;
end $$;
