-- RNDM Chat v22 Supabase upgrade
-- Run AFTER supabase_schema.sql and supabase_v20_upgrade.sql.
-- Adds cloud state sync, real Channels and real RNDM Video.

create extension if not exists pgcrypto;

-- =========================================================
-- 1) CROSS-DEVICE USER STATE (cat, XP, stars, settings, etc.)
-- =========================================================
create table if not exists public.user_state (
  user_id uuid not null references public.profiles(id) on delete cascade,
  key text not null,
  value jsonb not null default 'null'::jsonb,
  updated_at timestamptz not null default now(),
  primary key(user_id,key)
);

alter table public.user_state enable row level security;

drop policy if exists user_state_read_own on public.user_state;
create policy user_state_read_own on public.user_state
for select to authenticated using(user_id=auth.uid());

drop policy if exists user_state_insert_own on public.user_state;
create policy user_state_insert_own on public.user_state
for insert to authenticated with check(user_id=auth.uid());

drop policy if exists user_state_update_own on public.user_state;
create policy user_state_update_own on public.user_state
for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

drop policy if exists user_state_delete_own on public.user_state;
create policy user_state_delete_own on public.user_state
for delete to authenticated using(user_id=auth.uid());

grant select,insert,update,delete on public.user_state to authenticated;

-- =========================================================
-- 2) REAL CHANNELS
-- =========================================================
create table if not exists public.rndm_channels (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  name text not null check(char_length(name) between 2 and 80),
  handle text unique,
  description text not null default '',
  emoji text not null default '📡',
  avatar_url text,
  promo_subscribers integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.rndm_channel_subscriptions (
  channel_id uuid not null references public.rndm_channels(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(channel_id,user_id)
);

create table if not exists public.rndm_channel_posts (
  id uuid primary key default gen_random_uuid(),
  channel_id uuid not null references public.rndm_channels(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  body text not null default '',
  attachment_url text,
  attachment_type text,
  attachment_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.rndm_channel_comments (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.rndm_channel_posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check(char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);

create table if not exists public.rndm_channel_reactions (
  post_id uuid not null references public.rndm_channel_posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  emoji text not null default '❤️',
  created_at timestamptz not null default now(),
  primary key(post_id,user_id,emoji)
);

create index if not exists rndm_channels_created_idx on public.rndm_channels(created_at desc);
create index if not exists rndm_posts_channel_idx on public.rndm_channel_posts(channel_id,created_at desc);
create index if not exists rndm_comments_post_idx on public.rndm_channel_comments(post_id,created_at);

create or replace function public.is_channel_owner(cid uuid, uid uuid default auth.uid())
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.rndm_channels where id=cid and owner_id=uid)
$$;

alter table public.rndm_channels enable row level security;
alter table public.rndm_channel_subscriptions enable row level security;
alter table public.rndm_channel_posts enable row level security;
alter table public.rndm_channel_comments enable row level security;
alter table public.rndm_channel_reactions enable row level security;

drop policy if exists rndm_channels_read on public.rndm_channels;
create policy rndm_channels_read on public.rndm_channels for select to authenticated using(true);
drop policy if exists rndm_channels_insert on public.rndm_channels;
create policy rndm_channels_insert on public.rndm_channels for insert to authenticated with check(owner_id=auth.uid());
drop policy if exists rndm_channels_update on public.rndm_channels;
create policy rndm_channels_update on public.rndm_channels for update to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
drop policy if exists rndm_channels_delete on public.rndm_channels;
create policy rndm_channels_delete on public.rndm_channels for delete to authenticated using(owner_id=auth.uid());

drop policy if exists rndm_channel_sub_read on public.rndm_channel_subscriptions;
create policy rndm_channel_sub_read on public.rndm_channel_subscriptions for select to authenticated using(true);
drop policy if exists rndm_channel_sub_insert on public.rndm_channel_subscriptions;
create policy rndm_channel_sub_insert on public.rndm_channel_subscriptions for insert to authenticated with check(user_id=auth.uid());
drop policy if exists rndm_channel_sub_delete on public.rndm_channel_subscriptions;
create policy rndm_channel_sub_delete on public.rndm_channel_subscriptions for delete to authenticated using(user_id=auth.uid());

drop policy if exists rndm_posts_read on public.rndm_channel_posts;
create policy rndm_posts_read on public.rndm_channel_posts for select to authenticated using(true);
drop policy if exists rndm_posts_insert on public.rndm_channel_posts;
create policy rndm_posts_insert on public.rndm_channel_posts for insert to authenticated
with check(author_id=auth.uid() and public.is_channel_owner(channel_id));
drop policy if exists rndm_posts_update on public.rndm_channel_posts;
create policy rndm_posts_update on public.rndm_channel_posts for update to authenticated
using(author_id=auth.uid()) with check(author_id=auth.uid());
drop policy if exists rndm_posts_delete on public.rndm_channel_posts;
create policy rndm_posts_delete on public.rndm_channel_posts for delete to authenticated using(author_id=auth.uid());

drop policy if exists rndm_comments_read on public.rndm_channel_comments;
create policy rndm_comments_read on public.rndm_channel_comments for select to authenticated using(true);
drop policy if exists rndm_comments_insert on public.rndm_channel_comments;
create policy rndm_comments_insert on public.rndm_channel_comments for insert to authenticated with check(user_id=auth.uid());
drop policy if exists rndm_comments_delete on public.rndm_channel_comments;
create policy rndm_comments_delete on public.rndm_channel_comments for delete to authenticated using(user_id=auth.uid());

drop policy if exists rndm_reactions_read on public.rndm_channel_reactions;
create policy rndm_reactions_read on public.rndm_channel_reactions for select to authenticated using(true);
drop policy if exists rndm_reactions_insert on public.rndm_channel_reactions;
create policy rndm_reactions_insert on public.rndm_channel_reactions for insert to authenticated with check(user_id=auth.uid());
drop policy if exists rndm_reactions_delete on public.rndm_channel_reactions;
create policy rndm_reactions_delete on public.rndm_channel_reactions for delete to authenticated using(user_id=auth.uid());

grant select,insert,update,delete on public.rndm_channels to authenticated;
grant select,insert,delete on public.rndm_channel_subscriptions to authenticated;
grant select,insert,update,delete on public.rndm_channel_posts to authenticated;
grant select,insert,delete on public.rndm_channel_comments to authenticated;
grant select,insert,delete on public.rndm_channel_reactions to authenticated;

insert into storage.buckets(id,name,public,file_size_limit)
values('channel-files','channel-files',true,52428800)
on conflict(id) do update set public=true,file_size_limit=52428800;

drop policy if exists channel_files_upload on storage.objects;
create policy channel_files_upload on storage.objects for insert to authenticated
with check(bucket_id='channel-files' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists channel_files_delete on storage.objects;
create policy channel_files_delete on storage.objects for delete to authenticated
using(bucket_id='channel-files' and owner_id=auth.uid()::text);

-- =========================================================
-- 3) REAL RNDM VIDEO (YouTube-like section)
-- =========================================================
create table if not exists public.rndm_videos (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check(char_length(title) between 1 and 120),
  description text not null default '',
  video_url text not null,
  view_count bigint not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.rndm_video_likes (
  video_id uuid not null references public.rndm_videos(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(video_id,user_id)
);

create table if not exists public.rndm_video_comments (
  id bigint generated by default as identity primary key,
  video_id uuid not null references public.rndm_videos(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check(char_length(body) between 1 and 2000),
  created_at timestamptz not null default now()
);

create table if not exists public.rndm_follows (
  follower_id uuid not null references public.profiles(id) on delete cascade,
  followee_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(follower_id,followee_id),
  check(follower_id<>followee_id)
);

create index if not exists rndm_videos_created_idx on public.rndm_videos(created_at desc);
create index if not exists rndm_video_comments_idx on public.rndm_video_comments(video_id,created_at);

alter table public.rndm_videos enable row level security;
alter table public.rndm_video_likes enable row level security;
alter table public.rndm_video_comments enable row level security;
alter table public.rndm_follows enable row level security;

drop policy if exists rndm_videos_read on public.rndm_videos;
create policy rndm_videos_read on public.rndm_videos for select to authenticated using(true);
drop policy if exists rndm_videos_insert on public.rndm_videos;
create policy rndm_videos_insert on public.rndm_videos for insert to authenticated with check(user_id=auth.uid());
drop policy if exists rndm_videos_update on public.rndm_videos;
create policy rndm_videos_update on public.rndm_videos for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists rndm_videos_delete on public.rndm_videos;
create policy rndm_videos_delete on public.rndm_videos for delete to authenticated using(user_id=auth.uid());

drop policy if exists rndm_video_likes_read on public.rndm_video_likes;
create policy rndm_video_likes_read on public.rndm_video_likes for select to authenticated using(true);
drop policy if exists rndm_video_likes_insert on public.rndm_video_likes;
create policy rndm_video_likes_insert on public.rndm_video_likes for insert to authenticated with check(user_id=auth.uid());
drop policy if exists rndm_video_likes_delete on public.rndm_video_likes;
create policy rndm_video_likes_delete on public.rndm_video_likes for delete to authenticated using(user_id=auth.uid());

drop policy if exists rndm_video_comments_read on public.rndm_video_comments;
create policy rndm_video_comments_read on public.rndm_video_comments for select to authenticated using(true);
drop policy if exists rndm_video_comments_insert on public.rndm_video_comments;
create policy rndm_video_comments_insert on public.rndm_video_comments for insert to authenticated with check(user_id=auth.uid());
drop policy if exists rndm_video_comments_delete on public.rndm_video_comments;
create policy rndm_video_comments_delete on public.rndm_video_comments for delete to authenticated using(user_id=auth.uid());

drop policy if exists rndm_follows_read on public.rndm_follows;
create policy rndm_follows_read on public.rndm_follows for select to authenticated using(true);
drop policy if exists rndm_follows_insert on public.rndm_follows;
create policy rndm_follows_insert on public.rndm_follows for insert to authenticated with check(follower_id=auth.uid());
drop policy if exists rndm_follows_delete on public.rndm_follows;
create policy rndm_follows_delete on public.rndm_follows for delete to authenticated using(follower_id=auth.uid());

grant select,insert,update,delete on public.rndm_videos to authenticated;
grant select,insert,delete on public.rndm_video_likes to authenticated;
grant select,insert,delete on public.rndm_video_comments to authenticated;
grant select,insert,delete on public.rndm_follows to authenticated;

create or replace function public.increment_rndm_video_view(video uuid)
returns void language plpgsql security definer set search_path=public as $$
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  update public.rndm_videos set view_count=view_count+1 where id=video;
end $$;
grant execute on function public.increment_rndm_video_view(uuid) to authenticated;

insert into storage.buckets(id,name,public,file_size_limit)
values('videos','videos',true,262144000)
on conflict(id) do update set public=true,file_size_limit=262144000;

drop policy if exists rndm_videos_storage_upload on storage.objects;
create policy rndm_videos_storage_upload on storage.objects for insert to authenticated
with check(bucket_id='videos' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists rndm_videos_storage_delete on storage.objects;
create policy rndm_videos_storage_delete on storage.objects for delete to authenticated
using(bucket_id='videos' and owner_id=auth.uid()::text);

-- =========================================================
-- 4) Realtime for new social content
-- =========================================================
DO $$
begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='rndm_channel_posts') then
    alter publication supabase_realtime add table public.rndm_channel_posts;
  end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='rndm_channel_comments') then
    alter publication supabase_realtime add table public.rndm_channel_comments;
  end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='rndm_videos') then
    alter publication supabase_realtime add table public.rndm_videos;
  end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='rndm_video_comments') then
    alter publication supabase_realtime add table public.rndm_video_comments;
  end if;
end $$;
