-- RNDM Chat v25.4 — virtual stock market
-- Already applied to the connected Rndm Supabase project.
-- Safe to run after v25 on another copy of the project.
-- This is a GAME economy only: all trades use virtual R₽ from game_wallets.

create table if not exists public.stock_assets (
  id uuid primary key default gen_random_uuid(),
  ticker text not null unique,
  name text not null,
  emoji text not null default '📈',
  description text not null default '',
  price bigint not null check(price > 0),
  previous_price bigint not null check(previous_price > 0),
  is_active boolean not null default true,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (ticker ~ '^[A-Z0-9]{1,8}$')
);

create table if not exists public.stock_price_history (
  id bigint generated by default as identity primary key,
  stock_id uuid not null references public.stock_assets(id) on delete cascade,
  price bigint not null check(price > 0),
  changed_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.stock_positions (
  user_id uuid not null references public.profiles(id) on delete cascade,
  stock_id uuid not null references public.stock_assets(id) on delete cascade,
  quantity bigint not null default 0 check(quantity >= 0),
  average_price numeric(20,2) not null default 0 check(average_price >= 0),
  updated_at timestamptz not null default now(),
  primary key(user_id, stock_id)
);

create table if not exists public.stock_trades (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  stock_id uuid not null references public.stock_assets(id) on delete restrict,
  side text not null check(side in ('buy','sell')),
  quantity bigint not null check(quantity > 0),
  price bigint not null check(price > 0),
  total bigint not null check(total > 0),
  created_at timestamptz not null default now()
);

create index if not exists profiles_referred_by_idx on public.profiles(referred_by);
create index if not exists stock_assets_created_by_idx on public.stock_assets(created_by);
create index if not exists stock_assets_active_ticker_idx on public.stock_assets(is_active,ticker);
create index if not exists stock_price_history_stock_created_idx on public.stock_price_history(stock_id,created_at desc);
create index if not exists stock_price_history_changed_by_idx on public.stock_price_history(changed_by);
create index if not exists stock_positions_stock_idx on public.stock_positions(stock_id);
create index if not exists stock_trades_user_created_idx on public.stock_trades(user_id,created_at desc);
create index if not exists stock_trades_stock_created_idx on public.stock_trades(stock_id,created_at desc);

alter table public.stock_assets enable row level security;
alter table public.stock_price_history enable row level security;
alter table public.stock_positions enable row level security;
alter table public.stock_trades enable row level security;

drop policy if exists stocks_read on public.stock_assets;
create policy stocks_read on public.stock_assets for select to authenticated using(true);

drop policy if exists stock_history_read on public.stock_price_history;
create policy stock_history_read on public.stock_price_history for select to authenticated using(true);

drop policy if exists stock_positions_own on public.stock_positions;
create policy stock_positions_own on public.stock_positions for select to authenticated
using(user_id=(select auth.uid()));

drop policy if exists stock_trades_own on public.stock_trades;
create policy stock_trades_own on public.stock_trades for select to authenticated
using(user_id=(select auth.uid()));

revoke all on public.stock_assets from anon;
revoke all on public.stock_price_history from anon;
revoke all on public.stock_positions from anon;
revoke all on public.stock_trades from anon;

grant select on public.stock_assets to authenticated;
grant select on public.stock_price_history to authenticated;
grant select on public.stock_positions to authenticated;
grant select on public.stock_trades to authenticated;

create or replace function public.admin_create_stock(
  p_ticker text,
  p_name text,
  p_price bigint,
  p_emoji text default '📈',
  p_description text default ''
)
returns uuid
language plpgsql
security definer
set search_path=public
as $$
declare
  me uuid := auth.uid();
  sid uuid;
  t text := upper(trim(coalesce(p_ticker,'')));
begin
  if me is null or not public.is_admin(me) then raise exception 'owner/admin required'; end if;
  if t !~ '^[A-Z0-9]{1,8}$' then raise exception 'ticker must be 1-8 A-Z/0-9 characters'; end if;
  if length(trim(coalesce(p_name,''))) < 2 then raise exception 'name is too short'; end if;
  if coalesce(p_price,0) <= 0 then raise exception 'price must be positive'; end if;

  insert into public.stock_assets(ticker,name,emoji,description,price,previous_price,created_by)
  values(t,left(trim(p_name),80),left(coalesce(nullif(trim(p_emoji),''),'📈'),12),left(coalesce(p_description,''),1000),p_price,p_price,me)
  returning id into sid;

  insert into public.stock_price_history(stock_id,price,changed_by) values(sid,p_price,me);
  perform public.admin_log('stock_create',null,jsonb_build_object('stock_id',sid,'ticker',t,'price',p_price));
  return sid;
end $$;

create or replace function public.admin_set_stock_price(p_stock uuid,p_price bigint)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  me uuid := auth.uid();
  old_price bigint;
begin
  if me is null or not public.is_admin(me) then raise exception 'owner/admin required'; end if;
  if coalesce(p_price,0) <= 0 then raise exception 'price must be positive'; end if;

  select price into old_price from public.stock_assets where id=p_stock for update;
  if old_price is null then raise exception 'stock not found'; end if;

  update public.stock_assets
  set previous_price=price,price=p_price,updated_at=now()
  where id=p_stock;

  insert into public.stock_price_history(stock_id,price,changed_by) values(p_stock,p_price,me);
  perform public.admin_log('stock_price',null,jsonb_build_object('stock_id',p_stock,'old_price',old_price,'new_price',p_price));
  return jsonb_build_object('ok',true,'old_price',old_price,'new_price',p_price);
end $$;

create or replace function public.admin_update_stock(
  p_stock uuid,
  p_name text default null,
  p_emoji text default null,
  p_description text default null,
  p_active boolean default null
)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare me uuid := auth.uid();
begin
  if me is null or not public.is_admin(me) then raise exception 'owner/admin required'; end if;
  update public.stock_assets
  set
    name=case when p_name is null then name else left(trim(p_name),80) end,
    emoji=case when p_emoji is null then emoji else left(coalesce(nullif(trim(p_emoji),''),'📈'),12) end,
    description=case when p_description is null then description else left(p_description,1000) end,
    is_active=coalesce(p_active,is_active),
    updated_at=now()
  where id=p_stock;
  if not found then raise exception 'stock not found'; end if;
  perform public.admin_log('stock_update',null,jsonb_build_object('stock_id',p_stock,'active',p_active));
  return jsonb_build_object('ok',true);
end $$;

create or replace function public.admin_delete_stock(p_stock uuid)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  me uuid := auth.uid();
  holders bigint;
  trade_count bigint;
begin
  if me is null or not public.is_admin(me) then raise exception 'owner/admin required'; end if;
  select count(*) into holders from public.stock_positions where stock_id=p_stock and quantity>0;
  select count(*) into trade_count from public.stock_trades where stock_id=p_stock;
  if holders>0 then raise exception 'stock has holders; pause trading instead of deleting'; end if;
  if trade_count>0 then raise exception 'stock has trade history; pause trading instead of deleting'; end if;
  delete from public.stock_assets where id=p_stock;
  if not found then raise exception 'stock not found'; end if;
  perform public.admin_log('stock_delete',null,jsonb_build_object('stock_id',p_stock));
  return jsonb_build_object('ok',true);
end $$;

create or replace function public.trade_stock(p_stock uuid,p_side text,p_quantity bigint)
returns jsonb
language plpgsql
security definer
set search_path=public
as $$
declare
  me uuid := auth.uid();
  s public.stock_assets%rowtype;
  bal bigint;
  qty bigint := coalesce(p_quantity,0);
  old_qty bigint := 0;
  old_avg numeric(20,2) := 0;
  total_cost bigint;
  new_qty bigint;
  new_avg numeric(20,2);
begin
  if me is null then raise exception 'not authenticated'; end if;
  if p_side not in ('buy','sell') then raise exception 'invalid side'; end if;
  if qty <= 0 or qty > 1000000 then raise exception 'invalid quantity'; end if;

  select * into s from public.stock_assets where id=p_stock for update;
  if s.id is null then raise exception 'stock not found'; end if;
  if not s.is_active then raise exception 'trading paused'; end if;

  insert into public.game_wallets(user_id) values(me) on conflict(user_id) do nothing;
  select balance into bal from public.game_wallets where user_id=me for update;
  select quantity,average_price into old_qty,old_avg from public.stock_positions
  where user_id=me and stock_id=p_stock for update;

  old_qty := coalesce(old_qty,0);
  old_avg := coalesce(old_avg,0);
  total_cost := s.price * qty;

  if p_side='buy' then
    if bal < total_cost then raise exception 'not enough R₽'; end if;
    new_qty := old_qty + qty;
    new_avg := round(((old_qty::numeric*old_avg)+(qty::numeric*s.price::numeric))/new_qty::numeric,2);
    update public.game_wallets set balance=balance-total_cost,updated_at=now() where user_id=me;
    insert into public.stock_positions(user_id,stock_id,quantity,average_price,updated_at)
    values(me,p_stock,new_qty,new_avg,now())
    on conflict(user_id,stock_id) do update
    set quantity=excluded.quantity,average_price=excluded.average_price,updated_at=now();
  else
    if old_qty < qty then raise exception 'not enough shares'; end if;
    new_qty := old_qty - qty;
    update public.game_wallets set balance=balance+total_cost,updated_at=now() where user_id=me;
    if new_qty=0 then
      delete from public.stock_positions where user_id=me and stock_id=p_stock;
    else
      update public.stock_positions set quantity=new_qty,updated_at=now()
      where user_id=me and stock_id=p_stock;
    end if;
  end if;

  insert into public.stock_trades(user_id,stock_id,side,quantity,price,total)
  values(me,p_stock,p_side,qty,s.price,total_cost);

  return jsonb_build_object(
    'ok',true,'side',p_side,'ticker',s.ticker,'quantity',qty,
    'price',s.price,'total',total_cost,
    'balance',case when p_side='buy' then bal-total_cost else bal+total_cost end,
    'position_quantity',new_qty
  );
end $$;

revoke all on function public.admin_create_stock(text,text,bigint,text,text) from public,anon;
revoke all on function public.admin_set_stock_price(uuid,bigint) from public,anon;
revoke all on function public.admin_update_stock(uuid,text,text,text,boolean) from public,anon;
revoke all on function public.admin_delete_stock(uuid) from public,anon;
revoke all on function public.trade_stock(uuid,text,bigint) from public,anon;

grant execute on function public.admin_create_stock(text,text,bigint,text,text) to authenticated;
grant execute on function public.admin_set_stock_price(uuid,bigint) to authenticated;
grant execute on function public.admin_update_stock(uuid,text,text,text,boolean) to authenticated;
grant execute on function public.admin_delete_stock(uuid) to authenticated;
grant execute on function public.trade_stock(uuid,text,bigint) to authenticated;

do $$
begin
  if exists(select 1 from pg_publication where pubname='supabase_realtime') then
    if not exists(
      select 1 from pg_publication_tables
      where pubname='supabase_realtime' and schemaname='public' and tablename='stock_assets'
    ) then
      execute 'alter publication supabase_realtime add table public.stock_assets';
    end if;
  end if;
end $$;

analyze public.stock_assets;
analyze public.stock_price_history;
analyze public.stock_positions;
analyze public.stock_trades;
