-- RNDM Chat v25.7
-- Calls v2 + censorship.
-- This migration has already been applied to the connected Supabase project.
-- Kept in the archive for backup/reference.

create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz not null default now(),
  updated_by uuid references public.profiles(id) on delete set null
);

insert into public.app_settings(key,value)
values('censorship_enabled','true'::jsonb)
on conflict(key) do nothing;

alter table public.app_settings enable row level security;
drop policy if exists app_settings_read on public.app_settings;
create policy app_settings_read on public.app_settings
for select to authenticated using(true);
grant select on public.app_settings to authenticated;

create or replace function public.admin_set_censorship(p_enabled boolean)
returns jsonb language plpgsql security definer set search_path=public as $$
declare me uuid:=auth.uid();
begin
  if me is null or not public.is_admin(me) then raise exception 'owner/admin required'; end if;
  insert into public.app_settings(key,value,updated_at,updated_by)
  values('censorship_enabled',to_jsonb(p_enabled),now(),me)
  on conflict(key) do update set value=excluded.value,updated_at=now(),updated_by=me;
  perform public.admin_log('censorship_toggle',null,jsonb_build_object('enabled',p_enabled));
  return jsonb_build_object('ok',true,'enabled',p_enabled);
end $$;
revoke all on function public.admin_set_censorship(boolean) from public,anon;
grant execute on function public.admin_set_censorship(boolean) to authenticated;

create table if not exists public.call_rooms (
  id uuid primary key default gen_random_uuid(),
  host_id uuid not null references public.profiles(id) on delete cascade,
  guest_id uuid references public.profiles(id) on delete set null,
  status text not null default 'waiting' check(status in ('waiting','active','ended')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz not null default (now()+interval '2 hours'),
  host_client text,
  guest_client text
);

create table if not exists public.call_signals (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.call_rooms(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  kind text not null check(kind in ('ready','offer','answer','ice','hangup')),
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  sender_client text
);

create index if not exists call_rooms_host_idx on public.call_rooms(host_id,created_at desc);
create index if not exists call_rooms_guest_idx on public.call_rooms(guest_id,created_at desc);
create index if not exists call_rooms_status_expires_idx on public.call_rooms(status,expires_at);
create index if not exists call_signals_room_id_idx on public.call_signals(room_id,id);
create index if not exists call_signals_sender_idx on public.call_signals(sender_id,created_at desc);

alter table public.call_rooms enable row level security;
alter table public.call_signals enable row level security;

drop policy if exists call_rooms_member_read on public.call_rooms;
create policy call_rooms_member_read on public.call_rooms
for select to authenticated
using(host_id=(select auth.uid()) or guest_id=(select auth.uid()));

drop policy if exists call_signals_member_read on public.call_signals;
create policy call_signals_member_read on public.call_signals
for select to authenticated
using(exists(
  select 1 from public.call_rooms r
  where r.id=call_signals.room_id
    and (r.host_id=(select auth.uid()) or r.guest_id=(select auth.uid()))
));

grant select on public.call_rooms to authenticated;
grant select on public.call_signals to authenticated;

create or replace function public.create_call_room_v2(p_client text)
returns uuid language plpgsql security definer set search_path=public as $$
declare me uuid:=auth.uid(); rid uuid; cid text:=left(trim(coalesce(p_client,'')),80);
begin
  if me is null then raise exception 'not authenticated'; end if;
  if cid='' then raise exception 'client id required'; end if;
  delete from public.call_rooms where expires_at<now() or (status='ended' and updated_at<now()-interval '1 hour');
  insert into public.call_rooms(host_id,host_client) values(me,cid) returning id into rid;
  return rid;
end $$;

create or replace function public.join_call_room_v2(p_room uuid,p_client text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare me uuid:=auth.uid(); r public.call_rooms%rowtype; cid text:=left(trim(coalesce(p_client,'')),80); my_role text;
begin
  if me is null then raise exception 'not authenticated'; end if;
  if cid='' then raise exception 'client id required'; end if;
  select * into r from public.call_rooms where id=p_room for update;
  if r.id is null then raise exception 'room not found'; end if;
  if r.expires_at<now() then raise exception 'room expired'; end if;
  if r.status='ended' then raise exception 'call ended'; end if;
  if r.host_id=me and coalesce(r.host_client,'')=cid then my_role:='host';
  elsif r.guest_id=me and coalesce(r.guest_client,'')=cid then my_role:='guest';
  elsif r.guest_id is null then
    update public.call_rooms set guest_id=me,guest_client=cid,status='active',updated_at=now() where id=p_room;
    my_role:='guest';
  elsif r.host_id=me and r.host_client is null then
    update public.call_rooms set host_client=cid,updated_at=now() where id=p_room;
    my_role:='host';
  else raise exception 'room is full';
  end if;
  return jsonb_build_object('ok',true,'role',my_role,'host_id',r.host_id,'guest_id',case when my_role='guest' then me else r.guest_id end);
end $$;

create or replace function public.send_call_signal_v2(p_room uuid,p_kind text,p_payload jsonb,p_client text)
returns bigint language plpgsql security definer set search_path=public as $$
declare me uuid:=auth.uid(); cid text:=left(trim(coalesce(p_client,'')),80); signal_id bigint;
begin
  if me is null then raise exception 'not authenticated'; end if;
  if cid='' then raise exception 'client id required'; end if;
  if p_kind not in ('ready','offer','answer','ice','hangup') then raise exception 'invalid signal'; end if;
  if not exists(
    select 1 from public.call_rooms r
    where r.id=p_room and r.status<>'ended' and r.expires_at>now()
      and ((r.host_id=me and r.host_client=cid) or (r.guest_id=me and r.guest_client=cid))
  ) then raise exception 'not a room member'; end if;
  insert into public.call_signals(room_id,sender_id,sender_client,kind,payload)
  values(p_room,me,cid,p_kind,coalesce(p_payload,'{}'::jsonb))
  returning id into signal_id;
  return signal_id;
end $$;

create or replace function public.end_call_room_v2(p_room uuid,p_client text)
returns jsonb language plpgsql security definer set search_path=public as $$
declare me uuid:=auth.uid(); cid text:=left(trim(coalesce(p_client,'')),80);
begin
  if me is null then raise exception 'not authenticated'; end if;
  update public.call_rooms set status='ended',updated_at=now()
  where id=p_room and ((host_id=me and host_client=cid) or (guest_id=me and guest_client=cid));
  if not found then raise exception 'not a room member'; end if;
  return jsonb_build_object('ok',true);
end $$;

revoke all on function public.create_call_room_v2(text) from public,anon;
revoke all on function public.join_call_room_v2(uuid,text) from public,anon;
revoke all on function public.send_call_signal_v2(uuid,text,jsonb,text) from public,anon;
revoke all on function public.end_call_room_v2(uuid,text) from public,anon;
grant execute on function public.create_call_room_v2(text) to authenticated;
grant execute on function public.join_call_room_v2(uuid,text) to authenticated;
grant execute on function public.send_call_signal_v2(uuid,text,jsonb,text) to authenticated;
grant execute on function public.end_call_room_v2(uuid,text) to authenticated;

do $$
begin
  if exists(select 1 from pg_publication where pubname='supabase_realtime') then
    if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='call_signals') then
      execute 'alter publication supabase_realtime add table public.call_signals';
    end if;
    if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='app_settings') then
      execute 'alter publication supabase_realtime add table public.app_settings';
    end if;
  end if;
end $$;
