-- RNDM Chat v22 FULL SUPABASE SETUP
-- Can be run on a new project. It combines v18 + v20 + v22.

-- RNDM Chat v18 — real multi-user backend for Supabase
-- Run this ONCE in Supabase Dashboard -> SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  display_name text not null default 'Пользователь',
  avatar_url text,
  bio text not null default '',
  status text not null default 'online',
  last_seen timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
declare
  base text;
  candidate text;
begin
  base := lower(regexp_replace(coalesce(new.raw_user_meta_data->>'username', split_part(coalesce(new.email,'user'),'@',1), 'user'), '[^a-zA-Z0-9_]+', '', 'g'));
  if length(base) < 3 then base := 'user'; end if;
  base := left(base, 22);
  candidate := base;
  while exists(select 1 from public.profiles where username=candidate) loop
    candidate := left(base,17) || '_' || lpad((floor(random()*10000))::int::text,4,'0');
  end loop;
  insert into public.profiles(id,username,display_name,last_seen)
  values(new.id,candidate,coalesce(nullif(new.raw_user_meta_data->>'display_name',''),candidate),now())
  on conflict(id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  requester uuid not null references public.profiles(id) on delete cascade,
  addressee uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check(status in ('pending','accepted','blocked')),
  created_at timestamptz not null default now(),
  unique(requester,addressee),
  check(requester<>addressee)
);

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  kind text not null default 'direct' check(kind in ('direct','group')),
  title text,
  avatar_url text,
  direct_key text unique,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.conversation_members (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member' check(role in ('owner','admin','member')),
  joined_at timestamptz not null default now(),
  last_read_at timestamptz,
  primary key(conversation_id,user_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null default '',
  attachment_url text,
  attachment_name text,
  attachment_type text,
  reply_to bigint references public.messages(id) on delete set null,
  created_at timestamptz not null default now(),
  edited_at timestamptz,
  deleted_at timestamptz
);
create index if not exists messages_conv_created_idx on public.messages(conversation_id,created_at);

create table if not exists public.message_reactions (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  message_id bigint not null references public.messages(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  emoji text not null,
  created_at timestamptz not null default now(),
  primary key(message_id,user_id,emoji)
);

create table if not exists public.typing_states (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  updated_at timestamptz not null default now(),
  primary key(conversation_id,user_id)
);

create or replace function public.is_conversation_member(cid uuid, uid uuid default auth.uid())
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.conversation_members where conversation_id=cid and user_id=uid)
$$;

create or replace function public.send_friend_request(other uuid)
returns bigint language plpgsql security definer set search_path=public as $$
declare fid bigint; me uuid:=auth.uid();
begin
  if me is null or other=me then raise exception 'invalid user'; end if;
  select id into fid from public.friendships
   where (requester=me and addressee=other) or (requester=other and addressee=me) limit 1;
  if fid is not null then return fid; end if;
  insert into public.friendships(requester,addressee) values(me,other) returning id into fid;
  return fid;
end $$;

create or replace function public.accept_friend_request(request_id bigint)
returns void language plpgsql security definer set search_path=public as $$
begin
  update public.friendships set status='accepted' where id=request_id and addressee=auth.uid() and status='pending';
  if not found then raise exception 'request not found'; end if;
end $$;

create or replace function public.get_or_create_direct(other uuid)
returns uuid language plpgsql security definer set search_path=public as $$
declare me uuid:=auth.uid(); k text; cid uuid;
begin
  if me is null or other=me then raise exception 'invalid user'; end if;
  k := least(me::text,other::text)||':'||greatest(me::text,other::text);
  insert into public.conversations(kind,direct_key,created_by) values('direct',k,me)
  on conflict(direct_key) do update set direct_key=excluded.direct_key returning id into cid;
  insert into public.conversation_members(conversation_id,user_id,role) values(cid,me,'member') on conflict do nothing;
  insert into public.conversation_members(conversation_id,user_id,role) values(cid,other,'member') on conflict do nothing;
  return cid;
end $$;

create or replace function public.create_group(group_title text, member_ids uuid[])
returns uuid language plpgsql security definer set search_path=public as $$
declare me uuid:=auth.uid(); cid uuid; x uuid;
begin
  if me is null then raise exception 'not authenticated'; end if;
  insert into public.conversations(kind,title,created_by) values('group',left(coalesce(nullif(group_title,''),'Новая группа'),80),me) returning id into cid;
  insert into public.conversation_members(conversation_id,user_id,role) values(cid,me,'owner');
  foreach x in array coalesce(member_ids,array[]::uuid[]) loop
    if x<>me then insert into public.conversation_members(conversation_id,user_id,role) values(cid,x,'member') on conflict do nothing; end if;
  end loop;
  return cid;
end $$;

alter table public.profiles enable row level security;
alter table public.friendships enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages enable row level security;
alter table public.message_reactions enable row level security;
alter table public.typing_states enable row level security;

drop policy if exists profiles_read on public.profiles;
create policy profiles_read on public.profiles for select to authenticated using(true);
drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());

drop policy if exists friendship_read on public.friendships;
create policy friendship_read on public.friendships for select to authenticated using(requester=auth.uid() or addressee=auth.uid());
drop policy if exists friendship_delete on public.friendships;
create policy friendship_delete on public.friendships for delete to authenticated using(requester=auth.uid() or addressee=auth.uid());

drop policy if exists conversation_read on public.conversations;
create policy conversation_read on public.conversations for select to authenticated using(public.is_conversation_member(id));

drop policy if exists members_read on public.conversation_members;
create policy members_read on public.conversation_members for select to authenticated using(public.is_conversation_member(conversation_id));
drop policy if exists members_update_self on public.conversation_members;
create policy members_update_self on public.conversation_members for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

drop policy if exists messages_read on public.messages;
create policy messages_read on public.messages for select to authenticated using(public.is_conversation_member(conversation_id));
drop policy if exists messages_insert on public.messages;
create policy messages_insert on public.messages for insert to authenticated with check(sender_id=auth.uid() and public.is_conversation_member(conversation_id));
drop policy if exists messages_update_own on public.messages;
create policy messages_update_own on public.messages for update to authenticated using(sender_id=auth.uid()) with check(sender_id=auth.uid());
drop policy if exists messages_delete_own on public.messages;
create policy messages_delete_own on public.messages for delete to authenticated using(sender_id=auth.uid());

drop policy if exists reactions_read on public.message_reactions;
create policy reactions_read on public.message_reactions for select to authenticated using(public.is_conversation_member(conversation_id));
drop policy if exists reactions_insert on public.message_reactions;
create policy reactions_insert on public.message_reactions for insert to authenticated with check(user_id=auth.uid() and public.is_conversation_member(conversation_id));
drop policy if exists reactions_delete on public.message_reactions;
create policy reactions_delete on public.message_reactions for delete to authenticated using(user_id=auth.uid());

drop policy if exists typing_read on public.typing_states;
create policy typing_read on public.typing_states for select to authenticated using(public.is_conversation_member(conversation_id));
drop policy if exists typing_insert on public.typing_states;
create policy typing_insert on public.typing_states for insert to authenticated with check(user_id=auth.uid() and public.is_conversation_member(conversation_id));
drop policy if exists typing_update on public.typing_states;
create policy typing_update on public.typing_states for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

grant select,update on public.profiles to authenticated;
grant select,delete on public.friendships to authenticated;
grant select on public.conversations to authenticated;
grant select,update on public.conversation_members to authenticated;
grant select,insert,update,delete on public.messages to authenticated;
grant select,insert,delete on public.message_reactions to authenticated;
grant select,insert,update on public.typing_states to authenticated;
grant execute on function public.send_friend_request(uuid) to authenticated;
grant execute on function public.accept_friend_request(bigint) to authenticated;
grant execute on function public.get_or_create_direct(uuid) to authenticated;
grant execute on function public.create_group(text,uuid[]) to authenticated;

insert into storage.buckets(id,name,public,file_size_limit) values('chat-files','chat-files',true,52428800)
on conflict(id) do update set public=true,file_size_limit=52428800;
insert into storage.buckets(id,name,public,file_size_limit) values('avatars','avatars',true,10485760)
on conflict(id) do update set public=true,file_size_limit=10485760;

drop policy if exists chat_upload on storage.objects;
create policy chat_upload on storage.objects for insert to authenticated with check(bucket_id='chat-files' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists chat_delete on storage.objects;
create policy chat_delete on storage.objects for delete to authenticated using(bucket_id='chat-files' and owner_id=auth.uid()::text);
drop policy if exists avatar_upload on storage.objects;
create policy avatar_upload on storage.objects for insert to authenticated with check(bucket_id='avatars' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists avatar_update on storage.objects;
create policy avatar_update on storage.objects for update to authenticated using(bucket_id='avatars' and owner_id=auth.uid()::text);
drop policy if exists avatar_delete on storage.objects;
create policy avatar_delete on storage.objects for delete to authenticated using(bucket_id='avatars' and owner_id=auth.uid()::text);

-- Realtime for instant messages / requests / typing / read status
DO $$ begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='messages') then alter publication supabase_realtime add table public.messages; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='friendships') then alter publication supabase_realtime add table public.friendships; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='typing_states') then alter publication supabase_realtime add table public.typing_states; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='conversation_members') then alter publication supabase_realtime add table public.conversation_members; end if;
end $$;
-- RNDM Chat v20 upgrade
-- Run in Supabase SQL Editor AFTER the v18 schema.
-- Adds real Clips publishing, marketplace, and a DEMO/game economy.

create extension if not exists pgcrypto;

-- ---------------- REAL CLIPS ----------------
create table if not exists public.clips (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  video_url text not null,
  caption text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.clip_likes (
  clip_id uuid not null references public.clips(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (clip_id, user_id)
);

create table if not exists public.clip_comments (
  id bigint generated by default as identity primary key,
  clip_id uuid not null references public.clips(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);

create index if not exists clips_created_idx on public.clips(created_at desc);
create index if not exists clip_comments_clip_idx on public.clip_comments(clip_id, created_at);

alter table public.clips enable row level security;
alter table public.clip_likes enable row level security;
alter table public.clip_comments enable row level security;

drop policy if exists clips_read on public.clips;
create policy clips_read on public.clips for select to authenticated using (true);
drop policy if exists clips_insert on public.clips;
create policy clips_insert on public.clips for insert to authenticated with check (user_id = auth.uid());
drop policy if exists clips_delete on public.clips;
create policy clips_delete on public.clips for delete to authenticated using (user_id = auth.uid());

drop policy if exists clip_likes_read on public.clip_likes;
create policy clip_likes_read on public.clip_likes for select to authenticated using (true);
drop policy if exists clip_likes_insert on public.clip_likes;
create policy clip_likes_insert on public.clip_likes for insert to authenticated with check (user_id = auth.uid());
drop policy if exists clip_likes_delete on public.clip_likes;
create policy clip_likes_delete on public.clip_likes for delete to authenticated using (user_id = auth.uid());

drop policy if exists clip_comments_read on public.clip_comments;
create policy clip_comments_read on public.clip_comments for select to authenticated using (true);
drop policy if exists clip_comments_insert on public.clip_comments;
create policy clip_comments_insert on public.clip_comments for insert to authenticated with check (user_id = auth.uid());
drop policy if exists clip_comments_delete on public.clip_comments;
create policy clip_comments_delete on public.clip_comments for delete to authenticated using (user_id = auth.uid());

grant select,insert,delete on public.clips to authenticated;
grant select,insert,delete on public.clip_likes to authenticated;
grant select,insert,delete on public.clip_comments to authenticated;

insert into storage.buckets(id,name,public,file_size_limit)
values('clips','clips',true,104857600)
on conflict(id) do update set public=true,file_size_limit=104857600;

drop policy if exists clips_storage_upload on storage.objects;
create policy clips_storage_upload on storage.objects for insert to authenticated
with check(bucket_id='clips' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists clips_storage_delete on storage.objects;
create policy clips_storage_delete on storage.objects for delete to authenticated
using(bucket_id='clips' and owner_id=auth.uid()::text);

-- ---------------- RNDM MARKET ----------------
create table if not exists public.marketplace_listings (
  id uuid primary key default gen_random_uuid(),
  seller_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check(char_length(title) between 2 and 120),
  description text not null default '',
  category text not null default 'Другое',
  price bigint not null default 0 check(price >= 0),
  city text not null default '',
  image_url text,
  status text not null default 'active' check(status in ('active','sold','hidden')),
  created_at timestamptz not null default now()
);
create index if not exists market_created_idx on public.marketplace_listings(created_at desc);

create table if not exists public.marketplace_favorites (
  listing_id uuid not null references public.marketplace_listings(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(listing_id,user_id)
);

alter table public.marketplace_listings enable row level security;
alter table public.marketplace_favorites enable row level security;

drop policy if exists market_read on public.marketplace_listings;
create policy market_read on public.marketplace_listings for select to authenticated using(status <> 'hidden' or seller_id=auth.uid());
drop policy if exists market_insert on public.marketplace_listings;
create policy market_insert on public.marketplace_listings for insert to authenticated with check(seller_id=auth.uid());
drop policy if exists market_update on public.marketplace_listings;
create policy market_update on public.marketplace_listings for update to authenticated using(seller_id=auth.uid()) with check(seller_id=auth.uid());
drop policy if exists market_delete on public.marketplace_listings;
create policy market_delete on public.marketplace_listings for delete to authenticated using(seller_id=auth.uid());

drop policy if exists market_fav_read on public.marketplace_favorites;
create policy market_fav_read on public.marketplace_favorites for select to authenticated using(user_id=auth.uid());
drop policy if exists market_fav_insert on public.marketplace_favorites;
create policy market_fav_insert on public.marketplace_favorites for insert to authenticated with check(user_id=auth.uid());
drop policy if exists market_fav_delete on public.marketplace_favorites;
create policy market_fav_delete on public.marketplace_favorites for delete to authenticated using(user_id=auth.uid());

grant select,insert,update,delete on public.marketplace_listings to authenticated;
grant select,insert,delete on public.marketplace_favorites to authenticated;

insert into storage.buckets(id,name,public,file_size_limit)
values('market-files','market-files',true,20971520)
on conflict(id) do update set public=true,file_size_limit=20971520;

drop policy if exists market_storage_upload on storage.objects;
create policy market_storage_upload on storage.objects for insert to authenticated
with check(bucket_id='market-files' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists market_storage_delete on storage.objects;
create policy market_storage_delete on storage.objects for delete to authenticated
using(bucket_id='market-files' and owner_id=auth.uid()::text);

-- ---------------- GAME WALLET / LOANS / APARTMENTS ----------------
-- Everything in this section is virtual game currency. It is NOT a real loan or payment system.
create table if not exists public.game_wallets (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  balance bigint not null default 1500000 check(balance >= 0),
  updated_at timestamptz not null default now()
);

insert into public.game_wallets(user_id)
select id from public.profiles
on conflict(user_id) do nothing;

create or replace function public.ensure_game_wallet()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.game_wallets(user_id) values(new.id) on conflict(user_id) do nothing;
  return new;
end $$;

drop trigger if exists on_profile_game_wallet on public.profiles;
create trigger on_profile_game_wallet after insert on public.profiles
for each row execute function public.ensure_game_wallet();

create table if not exists public.game_loans (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  principal bigint not null check(principal > 0),
  rate_percent numeric(6,2) not null,
  term_months int not null,
  total_due bigint not null,
  remaining bigint not null,
  status text not null default 'active' check(status in ('active','paid')),
  created_at timestamptz not null default now()
);

create table if not exists public.demo_properties (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  city text not null,
  district text not null default '',
  price bigint not null check(price > 0),
  rooms int not null default 1,
  area numeric(7,1) not null default 30,
  emoji text not null default '🏠',
  description text not null default ''
);

create table if not exists public.owned_properties (
  user_id uuid not null references public.profiles(id) on delete cascade,
  property_id uuid not null references public.demo_properties(id) on delete cascade,
  bought_at timestamptz not null default now(),
  bought_price bigint not null,
  primary key(user_id,property_id)
);

insert into public.demo_properties(title,city,district,price,rooms,area,emoji,description)
select * from (values
 ('Студия у парка','Москва','Северное Бутово',2350000::bigint,1,24.5::numeric,'🌆','Компактная игровая квартира рядом с парком.'),
 ('Однокомнатная','Москва','Южное Бутово',3900000::bigint,1,38.2::numeric,'🏢','Светлая квартира с большой кухней.'),
 ('Двухкомнатная семейная','Москва','Чертаново',6200000::bigint,2,57.8::numeric,'🏙️','Две комнаты и игровая лоджия.'),
 ('Лофт в центре','Москва','Центр',9800000::bigint,2,71.0::numeric,'🌃','Игровой лофт с панорамными окнами.'),
 ('Загородный дом','Подольск','Волищево',12500000::bigint,4,146.0::numeric,'🏡','Дом с виртуальным участком и гаражом.'),
 ('Пентхаус RNDM','Москва','Москва-Сити',30000000::bigint,5,220.0::numeric,'✨','Самая дорогая коллекционная недвижимость RNDM.')
) as v(title,city,district,price,rooms,area,emoji,description)
where not exists(select 1 from public.demo_properties);

alter table public.game_wallets enable row level security;
alter table public.game_loans enable row level security;
alter table public.demo_properties enable row level security;
alter table public.owned_properties enable row level security;

drop policy if exists wallet_read on public.game_wallets;
create policy wallet_read on public.game_wallets for select to authenticated using(user_id=auth.uid());
drop policy if exists loans_read on public.game_loans;
create policy loans_read on public.game_loans for select to authenticated using(user_id=auth.uid());
drop policy if exists properties_read on public.demo_properties;
create policy properties_read on public.demo_properties for select to authenticated using(true);
drop policy if exists owned_read on public.owned_properties;
create policy owned_read on public.owned_properties for select to authenticated using(user_id=auth.uid());

grant select on public.game_wallets to authenticated;
grant select on public.game_loans to authenticated;
grant select on public.demo_properties to authenticated;
grant select on public.owned_properties to authenticated;

create or replace function public.take_demo_loan(amount bigint, months int)
returns uuid language plpgsql security definer set search_path=public as $$
declare
  me uuid:=auth.uid();
  rate numeric(6,2);
  total bigint;
  lid uuid;
  active_debt bigint;
begin
  if me is null then raise exception 'not authenticated'; end if;
  if amount < 10000 or amount > 5000000 then raise exception 'amount must be from 10000 to 5000000'; end if;
  if months not in (3,6,12,24) then raise exception 'term must be 3, 6, 12 or 24 months'; end if;
  select coalesce(sum(remaining),0) into active_debt from public.game_loans where user_id=me and status='active';
  if active_debt + amount > 7000000 then raise exception 'demo credit limit exceeded'; end if;
  rate := case months when 3 then 5 when 6 then 8 when 12 then 12 else 18 end;
  total := round(amount * (1 + rate/100.0));
  insert into public.game_wallets(user_id) values(me) on conflict(user_id) do nothing;
  update public.game_wallets set balance=balance+amount,updated_at=now() where user_id=me;
  insert into public.game_loans(user_id,principal,rate_percent,term_months,total_due,remaining)
  values(me,amount,rate,months,total,total) returning id into lid;
  return lid;
end $$;

create or replace function public.repay_demo_loan(loan_id uuid, amount bigint)
returns bigint language plpgsql security definer set search_path=public as $$
declare
  me uuid:=auth.uid();
  rem bigint;
  bal bigint;
  pay bigint;
begin
  if me is null then raise exception 'not authenticated'; end if;
  select remaining into rem from public.game_loans where id=loan_id and user_id=me and status='active' for update;
  if rem is null then raise exception 'active loan not found'; end if;
  select balance into bal from public.game_wallets where user_id=me for update;
  if amount <= 0 then raise exception 'invalid amount'; end if;
  pay:=least(amount,rem);
  if bal < pay then raise exception 'not enough demo balance'; end if;
  update public.game_wallets set balance=balance-pay,updated_at=now() where user_id=me;
  update public.game_loans set remaining=remaining-pay,status=case when remaining-pay<=0 then 'paid' else 'active' end where id=loan_id;
  return rem-pay;
end $$;

create or replace function public.buy_demo_property(property uuid)
returns void language plpgsql security definer set search_path=public as $$
declare
  me uuid:=auth.uid();
  p bigint;
  bal bigint;
begin
  if me is null then raise exception 'not authenticated'; end if;
  select price into p from public.demo_properties where id=property;
  if p is null then raise exception 'property not found'; end if;
  if exists(select 1 from public.owned_properties where user_id=me and property_id=property) then raise exception 'already owned'; end if;
  insert into public.game_wallets(user_id) values(me) on conflict(user_id) do nothing;
  select balance into bal from public.game_wallets where user_id=me for update;
  if bal < p then raise exception 'not enough demo balance'; end if;
  update public.game_wallets set balance=balance-p,updated_at=now() where user_id=me;
  insert into public.owned_properties(user_id,property_id,bought_price) values(me,property,p);
end $$;

grant execute on function public.take_demo_loan(bigint,int) to authenticated;
grant execute on function public.repay_demo_loan(uuid,bigint) to authenticated;
grant execute on function public.buy_demo_property(uuid) to authenticated;

-- Realtime for clips/market where useful.
do $$
begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='clips') then alter publication supabase_realtime add table public.clips; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='clip_comments') then alter publication supabase_realtime add table public.clip_comments; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='clip_likes') then alter publication supabase_realtime add table public.clip_likes; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='marketplace_listings') then alter publication supabase_realtime add table public.marketplace_listings; end if;
end $$;

-- ===== V20 UPGRADE =====

-- RNDM Chat v20 upgrade
-- Run in Supabase SQL Editor AFTER the v18 schema.
-- Adds real Clips publishing, marketplace, and a DEMO/game economy.

create extension if not exists pgcrypto;

-- ---------------- REAL CLIPS ----------------
create table if not exists public.clips (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  video_url text not null,
  caption text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.clip_likes (
  clip_id uuid not null references public.clips(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (clip_id, user_id)
);

create table if not exists public.clip_comments (
  id bigint generated by default as identity primary key,
  clip_id uuid not null references public.clips(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);

create index if not exists clips_created_idx on public.clips(created_at desc);
create index if not exists clip_comments_clip_idx on public.clip_comments(clip_id, created_at);

alter table public.clips enable row level security;
alter table public.clip_likes enable row level security;
alter table public.clip_comments enable row level security;

drop policy if exists clips_read on public.clips;
create policy clips_read on public.clips for select to authenticated using (true);
drop policy if exists clips_insert on public.clips;
create policy clips_insert on public.clips for insert to authenticated with check (user_id = auth.uid());
drop policy if exists clips_delete on public.clips;
create policy clips_delete on public.clips for delete to authenticated using (user_id = auth.uid());

drop policy if exists clip_likes_read on public.clip_likes;
create policy clip_likes_read on public.clip_likes for select to authenticated using (true);
drop policy if exists clip_likes_insert on public.clip_likes;
create policy clip_likes_insert on public.clip_likes for insert to authenticated with check (user_id = auth.uid());
drop policy if exists clip_likes_delete on public.clip_likes;
create policy clip_likes_delete on public.clip_likes for delete to authenticated using (user_id = auth.uid());

drop policy if exists clip_comments_read on public.clip_comments;
create policy clip_comments_read on public.clip_comments for select to authenticated using (true);
drop policy if exists clip_comments_insert on public.clip_comments;
create policy clip_comments_insert on public.clip_comments for insert to authenticated with check (user_id = auth.uid());
drop policy if exists clip_comments_delete on public.clip_comments;
create policy clip_comments_delete on public.clip_comments for delete to authenticated using (user_id = auth.uid());

grant select,insert,delete on public.clips to authenticated;
grant select,insert,delete on public.clip_likes to authenticated;
grant select,insert,delete on public.clip_comments to authenticated;

insert into storage.buckets(id,name,public,file_size_limit)
values('clips','clips',true,104857600)
on conflict(id) do update set public=true,file_size_limit=104857600;

drop policy if exists clips_storage_upload on storage.objects;
create policy clips_storage_upload on storage.objects for insert to authenticated
with check(bucket_id='clips' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists clips_storage_delete on storage.objects;
create policy clips_storage_delete on storage.objects for delete to authenticated
using(bucket_id='clips' and owner_id=auth.uid()::text);

-- ---------------- RNDM MARKET ----------------
create table if not exists public.marketplace_listings (
  id uuid primary key default gen_random_uuid(),
  seller_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check(char_length(title) between 2 and 120),
  description text not null default '',
  category text not null default 'Другое',
  price bigint not null default 0 check(price >= 0),
  city text not null default '',
  image_url text,
  status text not null default 'active' check(status in ('active','sold','hidden')),
  created_at timestamptz not null default now()
);
create index if not exists market_created_idx on public.marketplace_listings(created_at desc);

create table if not exists public.marketplace_favorites (
  listing_id uuid not null references public.marketplace_listings(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(listing_id,user_id)
);

alter table public.marketplace_listings enable row level security;
alter table public.marketplace_favorites enable row level security;

drop policy if exists market_read on public.marketplace_listings;
create policy market_read on public.marketplace_listings for select to authenticated using(status <> 'hidden' or seller_id=auth.uid());
drop policy if exists market_insert on public.marketplace_listings;
create policy market_insert on public.marketplace_listings for insert to authenticated with check(seller_id=auth.uid());
drop policy if exists market_update on public.marketplace_listings;
create policy market_update on public.marketplace_listings for update to authenticated using(seller_id=auth.uid()) with check(seller_id=auth.uid());
drop policy if exists market_delete on public.marketplace_listings;
create policy market_delete on public.marketplace_listings for delete to authenticated using(seller_id=auth.uid());

drop policy if exists market_fav_read on public.marketplace_favorites;
create policy market_fav_read on public.marketplace_favorites for select to authenticated using(user_id=auth.uid());
drop policy if exists market_fav_insert on public.marketplace_favorites;
create policy market_fav_insert on public.marketplace_favorites for insert to authenticated with check(user_id=auth.uid());
drop policy if exists market_fav_delete on public.marketplace_favorites;
create policy market_fav_delete on public.marketplace_favorites for delete to authenticated using(user_id=auth.uid());

grant select,insert,update,delete on public.marketplace_listings to authenticated;
grant select,insert,delete on public.marketplace_favorites to authenticated;

insert into storage.buckets(id,name,public,file_size_limit)
values('market-files','market-files',true,20971520)
on conflict(id) do update set public=true,file_size_limit=20971520;

drop policy if exists market_storage_upload on storage.objects;
create policy market_storage_upload on storage.objects for insert to authenticated
with check(bucket_id='market-files' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists market_storage_delete on storage.objects;
create policy market_storage_delete on storage.objects for delete to authenticated
using(bucket_id='market-files' and owner_id=auth.uid()::text);

-- ---------------- GAME WALLET / LOANS / APARTMENTS ----------------
-- Everything in this section is virtual game currency. It is NOT a real loan or payment system.
create table if not exists public.game_wallets (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  balance bigint not null default 1500000 check(balance >= 0),
  updated_at timestamptz not null default now()
);

insert into public.game_wallets(user_id)
select id from public.profiles
on conflict(user_id) do nothing;

create or replace function public.ensure_game_wallet()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.game_wallets(user_id) values(new.id) on conflict(user_id) do nothing;
  return new;
end $$;

drop trigger if exists on_profile_game_wallet on public.profiles;
create trigger on_profile_game_wallet after insert on public.profiles
for each row execute function public.ensure_game_wallet();

create table if not exists public.game_loans (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  principal bigint not null check(principal > 0),
  rate_percent numeric(6,2) not null,
  term_months int not null,
  total_due bigint not null,
  remaining bigint not null,
  status text not null default 'active' check(status in ('active','paid')),
  created_at timestamptz not null default now()
);

create table if not exists public.demo_properties (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  city text not null,
  district text not null default '',
  price bigint not null check(price > 0),
  rooms int not null default 1,
  area numeric(7,1) not null default 30,
  emoji text not null default '🏠',
  description text not null default ''
);

create table if not exists public.owned_properties (
  user_id uuid not null references public.profiles(id) on delete cascade,
  property_id uuid not null references public.demo_properties(id) on delete cascade,
  bought_at timestamptz not null default now(),
  bought_price bigint not null,
  primary key(user_id,property_id)
);

insert into public.demo_properties(title,city,district,price,rooms,area,emoji,description)
select * from (values
 ('Студия у парка','Москва','Северное Бутово',2350000::bigint,1,24.5::numeric,'🌆','Компактная игровая квартира рядом с парком.'),
 ('Однокомнатная','Москва','Южное Бутово',3900000::bigint,1,38.2::numeric,'🏢','Светлая квартира с большой кухней.'),
 ('Двухкомнатная семейная','Москва','Чертаново',6200000::bigint,2,57.8::numeric,'🏙️','Две комнаты и игровая лоджия.'),
 ('Лофт в центре','Москва','Центр',9800000::bigint,2,71.0::numeric,'🌃','Игровой лофт с панорамными окнами.'),
 ('Загородный дом','Подольск','Волищево',12500000::bigint,4,146.0::numeric,'🏡','Дом с виртуальным участком и гаражом.'),
 ('Пентхаус RNDM','Москва','Москва-Сити',30000000::bigint,5,220.0::numeric,'✨','Самая дорогая коллекционная недвижимость RNDM.')
) as v(title,city,district,price,rooms,area,emoji,description)
where not exists(select 1 from public.demo_properties);

alter table public.game_wallets enable row level security;
alter table public.game_loans enable row level security;
alter table public.demo_properties enable row level security;
alter table public.owned_properties enable row level security;

drop policy if exists wallet_read on public.game_wallets;
create policy wallet_read on public.game_wallets for select to authenticated using(user_id=auth.uid());
drop policy if exists loans_read on public.game_loans;
create policy loans_read on public.game_loans for select to authenticated using(user_id=auth.uid());
drop policy if exists properties_read on public.demo_properties;
create policy properties_read on public.demo_properties for select to authenticated using(true);
drop policy if exists owned_read on public.owned_properties;
create policy owned_read on public.owned_properties for select to authenticated using(user_id=auth.uid());

grant select on public.game_wallets to authenticated;
grant select on public.game_loans to authenticated;
grant select on public.demo_properties to authenticated;
grant select on public.owned_properties to authenticated;

create or replace function public.take_demo_loan(amount bigint, months int)
returns uuid language plpgsql security definer set search_path=public as $$
declare
  me uuid:=auth.uid();
  rate numeric(6,2);
  total bigint;
  lid uuid;
  active_debt bigint;
begin
  if me is null then raise exception 'not authenticated'; end if;
  if amount < 10000 or amount > 5000000 then raise exception 'amount must be from 10000 to 5000000'; end if;
  if months not in (3,6,12,24) then raise exception 'term must be 3, 6, 12 or 24 months'; end if;
  select coalesce(sum(remaining),0) into active_debt from public.game_loans where user_id=me and status='active';
  if active_debt + amount > 7000000 then raise exception 'demo credit limit exceeded'; end if;
  rate := case months when 3 then 5 when 6 then 8 when 12 then 12 else 18 end;
  total := round(amount * (1 + rate/100.0));
  insert into public.game_wallets(user_id) values(me) on conflict(user_id) do nothing;
  update public.game_wallets set balance=balance+amount,updated_at=now() where user_id=me;
  insert into public.game_loans(user_id,principal,rate_percent,term_months,total_due,remaining)
  values(me,amount,rate,months,total,total) returning id into lid;
  return lid;
end $$;

create or replace function public.repay_demo_loan(loan_id uuid, amount bigint)
returns bigint language plpgsql security definer set search_path=public as $$
declare
  me uuid:=auth.uid();
  rem bigint;
  bal bigint;
  pay bigint;
begin
  if me is null then raise exception 'not authenticated'; end if;
  select remaining into rem from public.game_loans where id=loan_id and user_id=me and status='active' for update;
  if rem is null then raise exception 'active loan not found'; end if;
  select balance into bal from public.game_wallets where user_id=me for update;
  if amount <= 0 then raise exception 'invalid amount'; end if;
  pay:=least(amount,rem);
  if bal < pay then raise exception 'not enough demo balance'; end if;
  update public.game_wallets set balance=balance-pay,updated_at=now() where user_id=me;
  update public.game_loans set remaining=remaining-pay,status=case when remaining-pay<=0 then 'paid' else 'active' end where id=loan_id;
  return rem-pay;
end $$;

create or replace function public.buy_demo_property(property uuid)
returns void language plpgsql security definer set search_path=public as $$
declare
  me uuid:=auth.uid();
  p bigint;
  bal bigint;
begin
  if me is null then raise exception 'not authenticated'; end if;
  select price into p from public.demo_properties where id=property;
  if p is null then raise exception 'property not found'; end if;
  if exists(select 1 from public.owned_properties where user_id=me and property_id=property) then raise exception 'already owned'; end if;
  insert into public.game_wallets(user_id) values(me) on conflict(user_id) do nothing;
  select balance into bal from public.game_wallets where user_id=me for update;
  if bal < p then raise exception 'not enough demo balance'; end if;
  update public.game_wallets set balance=balance-p,updated_at=now() where user_id=me;
  insert into public.owned_properties(user_id,property_id,bought_price) values(me,property,p);
end $$;

grant execute on function public.take_demo_loan(bigint,int) to authenticated;
grant execute on function public.repay_demo_loan(uuid,bigint) to authenticated;
grant execute on function public.buy_demo_property(uuid) to authenticated;

-- Realtime for clips/market where useful.
do $$
begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='clips') then alter publication supabase_realtime add table public.clips; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='clip_comments') then alter publication supabase_realtime add table public.clip_comments; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='clip_likes') then alter publication supabase_realtime add table public.clip_likes; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='marketplace_listings') then alter publication supabase_realtime add table public.marketplace_listings; end if;
end $$;

-- ===== V22 UPGRADE =====

-- RNDM Chat v22 Supabase upgrade
-- Run AFTER supabase_schema.sql and supabase_v20_upgrade.sql.
-- Adds cloud state sync, real Channels and real RNDM Video.

create extension if not exists pgcrypto;

-- =========================================================
-- 1) CROSS-DEVICE USER STATE (cat, XP, stars, settings, etc.)
-- =========================================================
create table if not exists public.user_state (
  user_id uuid not null references public.profiles(id) on delete cascade,
  key text not null,
  value jsonb not null default 'null'::jsonb,
  updated_at timestamptz not null default now(),
  primary key(user_id,key)
);

alter table public.user_state enable row level security;

drop policy if exists user_state_read_own on public.user_state;
create policy user_state_read_own on public.user_state
for select to authenticated using(user_id=auth.uid());

drop policy if exists user_state_insert_own on public.user_state;
create policy user_state_insert_own on public.user_state
for insert to authenticated with check(user_id=auth.uid());

drop policy if exists user_state_update_own on public.user_state;
create policy user_state_update_own on public.user_state
for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

drop policy if exists user_state_delete_own on public.user_state;
create policy user_state_delete_own on public.user_state
for delete to authenticated using(user_id=auth.uid());

grant select,insert,update,delete on public.user_state to authenticated;

-- =========================================================
-- 2) REAL CHANNELS
-- =========================================================
create table if not exists public.rndm_channels (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  name text not null check(char_length(name) between 2 and 80),
  handle text unique,
  description text not null default '',
  emoji text not null default '📡',
  avatar_url text,
  promo_subscribers integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.rndm_channel_subscriptions (
  channel_id uuid not null references public.rndm_channels(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(channel_id,user_id)
);

create table if not exists public.rndm_channel_posts (
  id uuid primary key default gen_random_uuid(),
  channel_id uuid not null references public.rndm_channels(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  body text not null default '',
  attachment_url text,
  attachment_type text,
  attachment_name text,
  created_at timestamptz not null default now()
);

create table if not exists public.rndm_channel_comments (
  id bigint generated by default as identity primary key,
  post_id uuid not null references public.rndm_channel_posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check(char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);

create table if not exists public.rndm_channel_reactions (
  post_id uuid not null references public.rndm_channel_posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  emoji text not null default '❤️',
  created_at timestamptz not null default now(),
  primary key(post_id,user_id,emoji)
);

create index if not exists rndm_channels_created_idx on public.rndm_channels(created_at desc);
create index if not exists rndm_posts_channel_idx on public.rndm_channel_posts(channel_id,created_at desc);
create index if not exists rndm_comments_post_idx on public.rndm_channel_comments(post_id,created_at);

create or replace function public.is_channel_owner(cid uuid, uid uuid default auth.uid())
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.rndm_channels where id=cid and owner_id=uid)
$$;

alter table public.rndm_channels enable row level security;
alter table public.rndm_channel_subscriptions enable row level security;
alter table public.rndm_channel_posts enable row level security;
alter table public.rndm_channel_comments enable row level security;
alter table public.rndm_channel_reactions enable row level security;

drop policy if exists rndm_channels_read on public.rndm_channels;
create policy rndm_channels_read on public.rndm_channels for select to authenticated using(true);
drop policy if exists rndm_channels_insert on public.rndm_channels;
create policy rndm_channels_insert on public.rndm_channels for insert to authenticated with check(owner_id=auth.uid());
drop policy if exists rndm_channels_update on public.rndm_channels;
create policy rndm_channels_update on public.rndm_channels for update to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
drop policy if exists rndm_channels_delete on public.rndm_channels;
create policy rndm_channels_delete on public.rndm_channels for delete to authenticated using(owner_id=auth.uid());

drop policy if exists rndm_channel_sub_read on public.rndm_channel_subscriptions;
create policy rndm_channel_sub_read on public.rndm_channel_subscriptions for select to authenticated using(true);
drop policy if exists rndm_channel_sub_insert on public.rndm_channel_subscriptions;
create policy rndm_channel_sub_insert on public.rndm_channel_subscriptions for insert to authenticated with check(user_id=auth.uid());
drop policy if exists rndm_channel_sub_delete on public.rndm_channel_subscriptions;
create policy rndm_channel_sub_delete on public.rndm_channel_subscriptions for delete to authenticated using(user_id=auth.uid());

drop policy if exists rndm_posts_read on public.rndm_channel_posts;
create policy rndm_posts_read on public.rndm_channel_posts for select to authenticated using(true);
drop policy if exists rndm_posts_insert on public.rndm_channel_posts;
create policy rndm_posts_insert on public.rndm_channel_posts for insert to authenticated
with check(author_id=auth.uid() and public.is_channel_owner(channel_id));
drop policy if exists rndm_posts_update on public.rndm_channel_posts;
create policy rndm_posts_update on public.rndm_channel_posts for update to authenticated
using(author_id=auth.uid()) with check(author_id=auth.uid());
drop policy if exists rndm_posts_delete on public.rndm_channel_posts;
create policy rndm_posts_delete on public.rndm_channel_posts for delete to authenticated using(author_id=auth.uid());

drop policy if exists rndm_comments_read on public.rndm_channel_comments;
create policy rndm_comments_read on public.rndm_channel_comments for select to authenticated using(true);
drop policy if exists rndm_comments_insert on public.rndm_channel_comments;
create policy rndm_comments_insert on public.rndm_channel_comments for insert to authenticated with check(user_id=auth.uid());
drop policy if exists rndm_comments_delete on public.rndm_channel_comments;
create policy rndm_comments_delete on public.rndm_channel_comments for delete to authenticated using(user_id=auth.uid());

drop policy if exists rndm_reactions_read on public.rndm_channel_reactions;
create policy rndm_reactions_read on public.rndm_channel_reactions for select to authenticated using(true);
drop policy if exists rndm_reactions_insert on public.rndm_channel_reactions;
create policy rndm_reactions_insert on public.rndm_channel_reactions for insert to authenticated with check(user_id=auth.uid());
drop policy if exists rndm_reactions_delete on public.rndm_channel_reactions;
create policy rndm_reactions_delete on public.rndm_channel_reactions for delete to authenticated using(user_id=auth.uid());

grant select,insert,update,delete on public.rndm_channels to authenticated;
grant select,insert,delete on public.rndm_channel_subscriptions to authenticated;
grant select,insert,update,delete on public.rndm_channel_posts to authenticated;
grant select,insert,delete on public.rndm_channel_comments to authenticated;
grant select,insert,delete on public.rndm_channel_reactions to authenticated;

insert into storage.buckets(id,name,public,file_size_limit)
values('channel-files','channel-files',true,52428800)
on conflict(id) do update set public=true,file_size_limit=52428800;

drop policy if exists channel_files_upload on storage.objects;
create policy channel_files_upload on storage.objects for insert to authenticated
with check(bucket_id='channel-files' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists channel_files_delete on storage.objects;
create policy channel_files_delete on storage.objects for delete to authenticated
using(bucket_id='channel-files' and owner_id=auth.uid()::text);

-- =========================================================
-- 3) REAL RNDM VIDEO (YouTube-like section)
-- =========================================================
create table if not exists public.rndm_videos (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check(char_length(title) between 1 and 120),
  description text not null default '',
  video_url text not null,
  view_count bigint not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.rndm_video_likes (
  video_id uuid not null references public.rndm_videos(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(video_id,user_id)
);

create table if not exists public.rndm_video_comments (
  id bigint generated by default as identity primary key,
  video_id uuid not null references public.rndm_videos(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check(char_length(body) between 1 and 2000),
  created_at timestamptz not null default now()
);

create table if not exists public.rndm_follows (
  follower_id uuid not null references public.profiles(id) on delete cascade,
  followee_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(follower_id,followee_id),
  check(follower_id<>followee_id)
);

create index if not exists rndm_videos_created_idx on public.rndm_videos(created_at desc);
create index if not exists rndm_video_comments_idx on public.rndm_video_comments(video_id,created_at);

alter table public.rndm_videos enable row level security;
alter table public.rndm_video_likes enable row level security;
alter table public.rndm_video_comments enable row level security;
alter table public.rndm_follows enable row level security;

drop policy if exists rndm_videos_read on public.rndm_videos;
create policy rndm_videos_read on public.rndm_videos for select to authenticated using(true);
drop policy if exists rndm_videos_insert on public.rndm_videos;
create policy rndm_videos_insert on public.rndm_videos for insert to authenticated with check(user_id=auth.uid());
drop policy if exists rndm_videos_update on public.rndm_videos;
create policy rndm_videos_update on public.rndm_videos for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists rndm_videos_delete on public.rndm_videos;
create policy rndm_videos_delete on public.rndm_videos for delete to authenticated using(user_id=auth.uid());

drop policy if exists rndm_video_likes_read on public.rndm_video_likes;
create policy rndm_video_likes_read on public.rndm_video_likes for select to authenticated using(true);
drop policy if exists rndm_video_likes_insert on public.rndm_video_likes;
create policy rndm_video_likes_insert on public.rndm_video_likes for insert to authenticated with check(user_id=auth.uid());
drop policy if exists rndm_video_likes_delete on public.rndm_video_likes;
create policy rndm_video_likes_delete on public.rndm_video_likes for delete to authenticated using(user_id=auth.uid());

drop policy if exists rndm_video_comments_read on public.rndm_video_comments;
create policy rndm_video_comments_read on public.rndm_video_comments for select to authenticated using(true);
drop policy if exists rndm_video_comments_insert on public.rndm_video_comments;
create policy rndm_video_comments_insert on public.rndm_video_comments for insert to authenticated with check(user_id=auth.uid());
drop policy if exists rndm_video_comments_delete on public.rndm_video_comments;
create policy rndm_video_comments_delete on public.rndm_video_comments for delete to authenticated using(user_id=auth.uid());

drop policy if exists rndm_follows_read on public.rndm_follows;
create policy rndm_follows_read on public.rndm_follows for select to authenticated using(true);
drop policy if exists rndm_follows_insert on public.rndm_follows;
create policy rndm_follows_insert on public.rndm_follows for insert to authenticated with check(follower_id=auth.uid());
drop policy if exists rndm_follows_delete on public.rndm_follows;
create policy rndm_follows_delete on public.rndm_follows for delete to authenticated using(follower_id=auth.uid());

grant select,insert,update,delete on public.rndm_videos to authenticated;
grant select,insert,delete on public.rndm_video_likes to authenticated;
grant select,insert,delete on public.rndm_video_comments to authenticated;
grant select,insert,delete on public.rndm_follows to authenticated;

create or replace function public.increment_rndm_video_view(video uuid)
returns void language plpgsql security definer set search_path=public as $$
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  update public.rndm_videos set view_count=view_count+1 where id=video;
end $$;
grant execute on function public.increment_rndm_video_view(uuid) to authenticated;

insert into storage.buckets(id,name,public,file_size_limit)
values('videos','videos',true,262144000)
on conflict(id) do update set public=true,file_size_limit=262144000;

drop policy if exists rndm_videos_storage_upload on storage.objects;
create policy rndm_videos_storage_upload on storage.objects for insert to authenticated
with check(bucket_id='videos' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists rndm_videos_storage_delete on storage.objects;
create policy rndm_videos_storage_delete on storage.objects for delete to authenticated
using(bucket_id='videos' and owner_id=auth.uid()::text);

-- =========================================================
-- 4) Realtime for new social content
-- =========================================================
DO $$
begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='rndm_channel_posts') then
    alter publication supabase_realtime add table public.rndm_channel_posts;
  end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='rndm_channel_comments') then
    alter publication supabase_realtime add table public.rndm_channel_comments;
  end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='rndm_videos') then
    alter publication supabase_realtime add table public.rndm_videos;
  end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='rndm_video_comments') then
    alter publication supabase_realtime add table public.rndm_video_comments;
  end if;
end $$;
