-- RNDM Chat v24 MEGA + Admin Center
-- Run AFTER supabase_FULL_v23.sql (or after v22 + v23 upgrades).
-- Safe to run more than once.

create extension if not exists pgcrypto;

-- =========================================================
-- 1) ROLES / BADGES / MODERATION FIELDS
-- =========================================================
alter table public.profiles add column if not exists app_role text not null default 'user';
alter table public.profiles add column if not exists is_verified boolean not null default false;
alter table public.profiles add column if not exists is_premium boolean not null default false;
alter table public.profiles add column if not exists is_banned boolean not null default false;
alter table public.profiles add column if not exists ban_reason text not null default '';
alter table public.profiles add column if not exists banned_until timestamptz;
alter table public.profiles add column if not exists reputation integer not null default 100;
alter table public.profiles add column if not exists xp bigint not null default 0;
alter table public.profiles add column if not exists stars bigint not null default 0;
alter table public.profiles add column if not exists cover_url text;
alter table public.profiles add column if not exists profile_music_url text;

-- Prevent users from modifying staff/system fields directly through the browser.
revoke update on public.profiles from authenticated;
grant update(username,display_name,avatar_url,bio,status,last_seen,cover_url,profile_music_url) on public.profiles to authenticated;

create or replace function public.role_rank(r text)
returns integer language sql immutable as $$
  select case lower(coalesce(r,'user'))
    when 'owner' then 50
    when 'admin' then 40
    when 'moderator' then 30
    when 'verified' then 20
    when 'premium' then 10
    else 0 end;
$$;

create or replace function public.is_staff(uid uuid default auth.uid())
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles p where p.id=uid and p.app_role in ('owner','admin','moderator'));
$$;

create or replace function public.is_admin(uid uuid default auth.uid())
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.profiles p where p.id=uid and p.app_role in ('owner','admin'));
$$;

grant execute on function public.is_staff(uuid) to authenticated;
grant execute on function public.is_admin(uuid) to authenticated;

create table if not exists public.admin_audit (
  id bigint generated by default as identity primary key,
  actor_id uuid references public.profiles(id) on delete set null,
  target_user_id uuid references public.profiles(id) on delete set null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.reports (
  id bigint generated by default as identity primary key,
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  target_user_id uuid references public.profiles(id) on delete set null,
  content_type text not null default 'user',
  content_id text,
  reason text not null,
  details text not null default '',
  status text not null default 'open' check(status in ('open','reviewing','resolved','rejected')),
  moderator_id uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

alter table public.admin_audit enable row level security;
alter table public.reports enable row level security;

drop policy if exists reports_insert on public.reports;
create policy reports_insert on public.reports for insert to authenticated with check(reporter_id=auth.uid());
drop policy if exists reports_read_self_or_staff on public.reports;
create policy reports_read_self_or_staff on public.reports for select to authenticated using(reporter_id=auth.uid() or public.is_staff());
drop policy if exists audit_read_staff on public.admin_audit;
create policy audit_read_staff on public.admin_audit for select to authenticated using(public.is_staff());

grant select on public.admin_audit to authenticated;
grant select,insert on public.reports to authenticated;

create or replace function public.admin_log(act text, target uuid, payload jsonb default '{}'::jsonb)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.is_staff() then raise exception 'admin required'; end if;
  insert into public.admin_audit(actor_id,target_user_id,action,details) values(auth.uid(),target,act,coalesce(payload,'{}'::jsonb));
end $$;

create or replace function public.admin_set_role(target uuid, new_role text)
returns void language plpgsql security definer set search_path=public as $$
declare me_role text; target_role text;
begin
  select app_role into me_role from public.profiles where id=auth.uid();
  select app_role into target_role from public.profiles where id=target;
  if me_role not in ('owner','admin') then raise exception 'admin required'; end if;
  if new_role not in ('user','premium','verified','moderator','admin','owner') then raise exception 'invalid role'; end if;
  if me_role <> 'owner' and (new_role in ('owner','admin') or target_role in ('owner','admin')) then raise exception 'owner required'; end if;
  if target=auth.uid() and me_role='owner' and new_role<>'owner' then raise exception 'owner cannot demote self'; end if;
  update public.profiles set app_role=new_role where id=target;
  perform public.admin_log('set_role',target,jsonb_build_object('role',new_role));
end $$;

create or replace function public.admin_set_badges(target uuid, verified boolean, premium boolean)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.is_admin() then raise exception 'admin required'; end if;
  update public.profiles set is_verified=verified,is_premium=premium where id=target;
  perform public.admin_log('set_badges',target,jsonb_build_object('verified',verified,'premium',premium));
end $$;

create or replace function public.admin_ban_user(target uuid, reason text, hours integer default 0)
returns void language plpgsql security definer set search_path=public as $$
declare me_role text; target_role text;
begin
  select app_role into me_role from public.profiles where id=auth.uid();
  select app_role into target_role from public.profiles where id=target;
  if me_role not in ('owner','admin','moderator') then raise exception 'staff required'; end if;
  if public.role_rank(me_role) <= public.role_rank(target_role) then raise exception 'cannot ban equal/higher role'; end if;
  update public.profiles set is_banned=true,ban_reason=left(coalesce(reason,''),500),banned_until=case when coalesce(hours,0)>0 then now()+make_interval(hours=>hours) else null end where id=target;
  perform public.admin_log('ban',target,jsonb_build_object('reason',reason,'hours',hours));
end $$;

create or replace function public.admin_unban_user(target uuid)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.is_staff() then raise exception 'staff required'; end if;
  update public.profiles set is_banned=false,ban_reason='',banned_until=null where id=target;
  perform public.admin_log('unban',target,'{}'::jsonb);
end $$;

create or replace function public.admin_adjust_stars(target uuid, delta bigint)
returns bigint language plpgsql security definer set search_path=public as $$
declare v bigint;
begin
  if not public.is_admin() then raise exception 'admin required'; end if;
  update public.profiles set stars=greatest(0,stars+delta) where id=target returning stars into v;
  perform public.admin_log('adjust_stars',target,jsonb_build_object('delta',delta,'new',v));
  return v;
end $$;

create or replace function public.admin_adjust_xp(target uuid, delta bigint)
returns bigint language plpgsql security definer set search_path=public as $$
declare v bigint;
begin
  if not public.is_admin() then raise exception 'admin required'; end if;
  update public.profiles set xp=greatest(0,xp+delta) where id=target returning xp into v;
  perform public.admin_log('adjust_xp',target,jsonb_build_object('delta',delta,'new',v));
  return v;
end $$;

create or replace function public.admin_adjust_reputation(target uuid, delta integer)
returns integer language plpgsql security definer set search_path=public as $$
declare v integer;
begin
  if not public.is_staff() then raise exception 'staff required'; end if;
  update public.profiles set reputation=greatest(0,least(1000,reputation+delta)) where id=target returning reputation into v;
  perform public.admin_log('adjust_reputation',target,jsonb_build_object('delta',delta,'new',v));
  return v;
end $$;

create or replace function public.admin_adjust_wallet(target uuid, delta bigint)
returns bigint language plpgsql security definer set search_path=public as $$
declare v bigint;
begin
  if not public.is_admin() then raise exception 'admin required'; end if;
  insert into public.game_wallets(user_id,balance) values(target,0) on conflict(user_id) do nothing;
  update public.game_wallets set balance=greatest(0,balance+delta),updated_at=now() where user_id=target returning balance into v;
  perform public.admin_log('adjust_wallet',target,jsonb_build_object('delta',delta,'new',v));
  return v;
end $$;

create or replace function public.submit_report(target uuid, kind text, item text, why text, extra text default '')
returns bigint language plpgsql security definer set search_path=public as $$
declare rid bigint;
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  insert into public.reports(reporter_id,target_user_id,content_type,content_id,reason,details)
  values(auth.uid(),target,left(coalesce(kind,'user'),40),left(item,120),left(coalesce(why,'Другое'),160),left(coalesce(extra,''),2000)) returning id into rid;
  return rid;
end $$;

create or replace function public.admin_resolve_report(report_id bigint, new_status text)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.is_staff() then raise exception 'staff required'; end if;
  if new_status not in ('reviewing','resolved','rejected') then raise exception 'invalid status'; end if;
  update public.reports set status=new_status,moderator_id=auth.uid(),resolved_at=case when new_status in ('resolved','rejected') then now() else null end where id=report_id;
  perform public.admin_log('report_'||new_status,null,jsonb_build_object('report_id',report_id));
end $$;

grant execute on function public.admin_set_role(uuid,text) to authenticated;
grant execute on function public.admin_set_badges(uuid,boolean,boolean) to authenticated;
grant execute on function public.admin_ban_user(uuid,text,integer) to authenticated;
grant execute on function public.admin_unban_user(uuid) to authenticated;
grant execute on function public.admin_adjust_stars(uuid,bigint) to authenticated;
grant execute on function public.admin_adjust_xp(uuid,bigint) to authenticated;
grant execute on function public.admin_adjust_reputation(uuid,integer) to authenticated;
grant execute on function public.admin_adjust_wallet(uuid,bigint) to authenticated;
grant execute on function public.submit_report(uuid,text,text,text,text) to authenticated;
grant execute on function public.admin_resolve_report(bigint,text) to authenticated;

-- =========================================================
-- 2) INTERESTS + RANDOM 2.0 FILTERS
-- =========================================================
create table if not exists public.profile_interests (
  user_id uuid not null references public.profiles(id) on delete cascade,
  interest text not null,
  primary key(user_id,interest)
);
alter table public.profile_interests enable row level security;
drop policy if exists interests_read on public.profile_interests;
create policy interests_read on public.profile_interests for select to authenticated using(true);
drop policy if exists interests_own on public.profile_interests;
create policy interests_own on public.profile_interests for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
grant select,insert,delete on public.profile_interests to authenticated;

alter table public.random_queue add column if not exists mode text not null default 'text';
alter table public.random_queue add column if not exists language text not null default 'any';
alter table public.random_queue add column if not exists interest text not null default 'any';

create or replace function public.random_chat_join_v24(p_mode text default 'text', p_language text default 'any', p_interest text default 'any')
returns table(match_status text, conversation_id uuid, matched_user_id uuid)
language plpgsql security definer set search_path=public as $$
declare me uuid:=auth.uid(); other_user uuid; cid uuid; existing public.random_queue%rowtype;
begin
  if me is null then raise exception 'not authenticated'; end if;
  if exists(select 1 from public.profiles where id=me and is_banned and (banned_until is null or banned_until>now())) then raise exception 'account banned'; end if;
  perform pg_advisory_xact_lock(83920417);
  delete from public.random_queue where (status='waiting' and updated_at<now()-interval '3 minutes') or (status='matched' and updated_at<now()-interval '15 minutes');
  select * into existing from public.random_queue where user_id=me;
  if found and existing.status='matched' and existing.conversation_id is not null then return query select 'matched'::text,existing.conversation_id,existing.matched_user_id; return; end if;
  insert into public.random_queue(user_id,status,matched_user_id,conversation_id,joined_at,updated_at,mode,language,interest)
  values(me,'waiting',null,null,now(),now(),coalesce(nullif(p_mode,''),'text'),coalesce(nullif(p_language,''),'any'),coalesce(nullif(p_interest,''),'any'))
  on conflict(user_id) do update set status='waiting',matched_user_id=null,conversation_id=null,joined_at=now(),updated_at=now(),mode=excluded.mode,language=excluded.language,interest=excluded.interest;
  select q.user_id into other_user from public.random_queue q
  join public.profiles pp on pp.id=q.user_id
  where q.user_id<>me and q.status='waiting' and q.updated_at>=now()-interval '3 minutes'
    and not (pp.is_banned and (pp.banned_until is null or pp.banned_until>now()))
    and q.mode=coalesce(nullif(p_mode,''),'text')
    and (p_language='any' or q.language='any' or q.language=p_language)
    and (p_interest='any' or q.interest='any' or q.interest=p_interest)
    and not exists(select 1 from public.friendships f where f.status='blocked' and ((f.requester=me and f.addressee=q.user_id) or (f.requester=q.user_id and f.addressee=me)))
  order by pp.reputation desc,q.joined_at asc limit 1;
  if other_user is null then return query select 'waiting'::text,null::uuid,null::uuid; return; end if;
  cid:=public.get_or_create_direct(other_user);
  update public.random_queue set status='matched',matched_user_id=other_user,conversation_id=cid,updated_at=now() where user_id=me;
  update public.random_queue set status='matched',matched_user_id=me,conversation_id=cid,updated_at=now() where user_id=other_user;
  return query select 'matched'::text,cid,other_user;
end $$;
grant execute on function public.random_chat_join_v24(text,text,text) to authenticated;

-- =========================================================
-- 3) DAILY HUB / ACHIEVEMENTS / LEADERBOARD
-- =========================================================
create table if not exists public.daily_claims (
  user_id uuid not null references public.profiles(id) on delete cascade,
  claim_date date not null default current_date,
  reward_stars integer not null default 0,
  reward_xp integer not null default 0,
  reward_cash bigint not null default 0,
  created_at timestamptz not null default now(),
  primary key(user_id,claim_date)
);
alter table public.daily_claims enable row level security;
drop policy if exists daily_own on public.daily_claims;
create policy daily_own on public.daily_claims for select to authenticated using(user_id=auth.uid());
grant select on public.daily_claims to authenticated;

create or replace function public.claim_daily_reward()
returns table(stars integer,xp integer,cash bigint)
language plpgsql security definer set search_path=public as $$
declare s integer:=15; x integer:=40; c bigint:=750;
begin
  if auth.uid() is null then raise exception 'not authenticated'; end if;
  if exists(select 1 from public.daily_claims where user_id=auth.uid() and claim_date=current_date) then raise exception 'already claimed'; end if;
  insert into public.daily_claims(user_id,reward_stars,reward_xp,reward_cash) values(auth.uid(),s,x,c);
  update public.profiles set stars=stars+s,xp=xp+x where id=auth.uid();
  insert into public.game_wallets(user_id,balance) values(auth.uid(),c) on conflict(user_id) do update set balance=public.game_wallets.balance+excluded.balance,updated_at=now();
  return query select s,x,c;
end $$;
grant execute on function public.claim_daily_reward() to authenticated;

create or replace function public.rndm_leaderboard(limit_count integer default 50)
returns table(user_id uuid,username text,display_name text,avatar_url text,xp bigint,reputation integer,stars bigint,app_role text)
language sql stable security definer set search_path=public as $$
  select p.id,p.username,p.display_name,p.avatar_url,p.xp,p.reputation,p.stars,p.app_role
  from public.profiles p
  where not p.is_banned
  order by p.xp desc,p.reputation desc,p.created_at asc
  limit greatest(1,least(coalesce(limit_count,50),100));
$$;
grant execute on function public.rndm_leaderboard(integer) to authenticated;

-- =========================================================
-- 4) STORIES
-- =========================================================
create table if not exists public.stories (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  media_url text,
  media_type text not null default 'text',
  body text not null default '',
  created_at timestamptz not null default now(),
  expires_at timestamptz not null default now()+interval '24 hours'
);
create table if not exists public.story_views (
  story_id uuid not null references public.stories(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  viewed_at timestamptz not null default now(),
  primary key(story_id,user_id)
);
create table if not exists public.story_reactions (
  story_id uuid not null references public.stories(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  emoji text not null default '❤️',
  created_at timestamptz not null default now(),
  primary key(story_id,user_id)
);
alter table public.stories enable row level security; alter table public.story_views enable row level security; alter table public.story_reactions enable row level security;
drop policy if exists stories_read on public.stories; create policy stories_read on public.stories for select to authenticated using(expires_at>now());
drop policy if exists stories_own on public.stories; create policy stories_own on public.stories for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
drop policy if exists story_views_read on public.story_views; create policy story_views_read on public.story_views for select to authenticated using(user_id=auth.uid() or exists(select 1 from public.stories s where s.id=story_id and s.user_id=auth.uid()));
drop policy if exists story_views_insert on public.story_views; create policy story_views_insert on public.story_views for insert to authenticated with check(user_id=auth.uid());
drop policy if exists story_reactions_read on public.story_reactions; create policy story_reactions_read on public.story_reactions for select to authenticated using(true);
drop policy if exists story_reactions_own on public.story_reactions; create policy story_reactions_own on public.story_reactions for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
grant select,insert,delete on public.stories to authenticated; grant select,insert on public.story_views to authenticated; grant select,insert,update,delete on public.story_reactions to authenticated;
insert into storage.buckets(id,name,public,file_size_limit) values('stories','stories',true,52428800) on conflict(id) do update set public=true,file_size_limit=52428800;
drop policy if exists stories_upload on storage.objects; create policy stories_upload on storage.objects for insert to authenticated with check(bucket_id='stories' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists stories_delete on storage.objects; create policy stories_delete on storage.objects for delete to authenticated using(bucket_id='stories' and owner_id=auth.uid()::text);

-- =========================================================
-- 5) EVENTS / RSVP
-- =========================================================
create table if not exists public.rndm_events (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  description text not null default '',
  starts_at timestamptz not null,
  location_text text not null default 'Онлайн',
  max_people integer,
  created_at timestamptz not null default now()
);
create table if not exists public.event_rsvps (
  event_id uuid not null references public.rndm_events(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'going' check(status in ('going','maybe','no')),
  created_at timestamptz not null default now(),
  primary key(event_id,user_id)
);
alter table public.rndm_events enable row level security; alter table public.event_rsvps enable row level security;
drop policy if exists events_read on public.rndm_events; create policy events_read on public.rndm_events for select to authenticated using(true);
drop policy if exists events_own on public.rndm_events; create policy events_own on public.rndm_events for all to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
drop policy if exists rsvp_read on public.event_rsvps; create policy rsvp_read on public.event_rsvps for select to authenticated using(true);
drop policy if exists rsvp_own on public.event_rsvps; create policy rsvp_own on public.event_rsvps for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
grant select,insert,update,delete on public.rndm_events to authenticated; grant select,insert,update,delete on public.event_rsvps to authenticated;

-- =========================================================
-- 6) NOTIFICATIONS
-- =========================================================
create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  kind text not null default 'system',
  title text not null,
  body text not null default '',
  link text,
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);
alter table public.notifications enable row level security;
drop policy if exists notif_own_read on public.notifications; create policy notif_own_read on public.notifications for select to authenticated using(user_id=auth.uid());
drop policy if exists notif_own_update on public.notifications; create policy notif_own_update on public.notifications for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
grant select,update on public.notifications to authenticated;

create or replace function public.admin_notify_user(target uuid, ttl text, msg text, lnk text default null)
returns bigint language plpgsql security definer set search_path=public as $$
declare nid bigint;
begin
  if not public.is_staff() then raise exception 'staff required'; end if;
  insert into public.notifications(user_id,kind,title,body,link) values(target,'admin',left(ttl,120),left(coalesce(msg,''),1000),left(lnk,250)) returning id into nid;
  perform public.admin_log('notify',target,jsonb_build_object('notification_id',nid,'title',ttl));
  return nid;
end $$;
grant execute on function public.admin_notify_user(uuid,text,text,text) to authenticated;

-- Realtime additions
DO $$
begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='stories') then alter publication supabase_realtime add table public.stories; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='rndm_events') then alter publication supabase_realtime add table public.rndm_events; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='notifications') then alter publication supabase_realtime add table public.notifications; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='reports') then alter publication supabase_realtime add table public.reports; end if;
end $$;
