-- RNDM Chat v18 — real multi-user backend for Supabase
-- Run this ONCE in Supabase Dashboard -> SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  display_name text not null default 'Пользователь',
  avatar_url text,
  bio text not null default '',
  status text not null default 'online',
  last_seen timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public as $$
declare
  base text;
  candidate text;
begin
  base := lower(regexp_replace(coalesce(new.raw_user_meta_data->>'username', split_part(coalesce(new.email,'user'),'@',1), 'user'), '[^a-zA-Z0-9_]+', '', 'g'));
  if length(base) < 3 then base := 'user'; end if;
  base := left(base, 22);
  candidate := base;
  while exists(select 1 from public.profiles where username=candidate) loop
    candidate := left(base,17) || '_' || lpad((floor(random()*10000))::int::text,4,'0');
  end loop;
  insert into public.profiles(id,username,display_name,last_seen)
  values(new.id,candidate,coalesce(nullif(new.raw_user_meta_data->>'display_name',''),candidate),now())
  on conflict(id) do nothing;
  return new;
end $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users
for each row execute function public.handle_new_user();

create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  requester uuid not null references public.profiles(id) on delete cascade,
  addressee uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check(status in ('pending','accepted','blocked')),
  created_at timestamptz not null default now(),
  unique(requester,addressee),
  check(requester<>addressee)
);

create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  kind text not null default 'direct' check(kind in ('direct','group')),
  title text,
  avatar_url text,
  direct_key text unique,
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists public.conversation_members (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  role text not null default 'member' check(role in ('owner','admin','member')),
  joined_at timestamptz not null default now(),
  last_read_at timestamptz,
  primary key(conversation_id,user_id)
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null default '',
  attachment_url text,
  attachment_name text,
  attachment_type text,
  reply_to bigint references public.messages(id) on delete set null,
  created_at timestamptz not null default now(),
  edited_at timestamptz,
  deleted_at timestamptz
);
create index if not exists messages_conv_created_idx on public.messages(conversation_id,created_at);

create table if not exists public.message_reactions (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  message_id bigint not null references public.messages(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  emoji text not null,
  created_at timestamptz not null default now(),
  primary key(message_id,user_id,emoji)
);

create table if not exists public.typing_states (
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  updated_at timestamptz not null default now(),
  primary key(conversation_id,user_id)
);

create or replace function public.is_conversation_member(cid uuid, uid uuid default auth.uid())
returns boolean language sql stable security definer set search_path=public as $$
  select exists(select 1 from public.conversation_members where conversation_id=cid and user_id=uid)
$$;

create or replace function public.send_friend_request(other uuid)
returns bigint language plpgsql security definer set search_path=public as $$
declare fid bigint; me uuid:=auth.uid();
begin
  if me is null or other=me then raise exception 'invalid user'; end if;
  select id into fid from public.friendships
   where (requester=me and addressee=other) or (requester=other and addressee=me) limit 1;
  if fid is not null then return fid; end if;
  insert into public.friendships(requester,addressee) values(me,other) returning id into fid;
  return fid;
end $$;

create or replace function public.accept_friend_request(request_id bigint)
returns void language plpgsql security definer set search_path=public as $$
begin
  update public.friendships set status='accepted' where id=request_id and addressee=auth.uid() and status='pending';
  if not found then raise exception 'request not found'; end if;
end $$;

create or replace function public.get_or_create_direct(other uuid)
returns uuid language plpgsql security definer set search_path=public as $$
declare me uuid:=auth.uid(); k text; cid uuid;
begin
  if me is null or other=me then raise exception 'invalid user'; end if;
  k := least(me::text,other::text)||':'||greatest(me::text,other::text);
  insert into public.conversations(kind,direct_key,created_by) values('direct',k,me)
  on conflict(direct_key) do update set direct_key=excluded.direct_key returning id into cid;
  insert into public.conversation_members(conversation_id,user_id,role) values(cid,me,'member') on conflict do nothing;
  insert into public.conversation_members(conversation_id,user_id,role) values(cid,other,'member') on conflict do nothing;
  return cid;
end $$;

create or replace function public.create_group(group_title text, member_ids uuid[])
returns uuid language plpgsql security definer set search_path=public as $$
declare me uuid:=auth.uid(); cid uuid; x uuid;
begin
  if me is null then raise exception 'not authenticated'; end if;
  insert into public.conversations(kind,title,created_by) values('group',left(coalesce(nullif(group_title,''),'Новая группа'),80),me) returning id into cid;
  insert into public.conversation_members(conversation_id,user_id,role) values(cid,me,'owner');
  foreach x in array coalesce(member_ids,array[]::uuid[]) loop
    if x<>me then insert into public.conversation_members(conversation_id,user_id,role) values(cid,x,'member') on conflict do nothing; end if;
  end loop;
  return cid;
end $$;

alter table public.profiles enable row level security;
alter table public.friendships enable row level security;
alter table public.conversations enable row level security;
alter table public.conversation_members enable row level security;
alter table public.messages enable row level security;
alter table public.message_reactions enable row level security;
alter table public.typing_states enable row level security;

drop policy if exists profiles_read on public.profiles;
create policy profiles_read on public.profiles for select to authenticated using(true);
drop policy if exists profiles_update_self on public.profiles;
create policy profiles_update_self on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());

drop policy if exists friendship_read on public.friendships;
create policy friendship_read on public.friendships for select to authenticated using(requester=auth.uid() or addressee=auth.uid());
drop policy if exists friendship_delete on public.friendships;
create policy friendship_delete on public.friendships for delete to authenticated using(requester=auth.uid() or addressee=auth.uid());

drop policy if exists conversation_read on public.conversations;
create policy conversation_read on public.conversations for select to authenticated using(public.is_conversation_member(id));

drop policy if exists members_read on public.conversation_members;
create policy members_read on public.conversation_members for select to authenticated using(public.is_conversation_member(conversation_id));
drop policy if exists members_update_self on public.conversation_members;
create policy members_update_self on public.conversation_members for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

drop policy if exists messages_read on public.messages;
create policy messages_read on public.messages for select to authenticated using(public.is_conversation_member(conversation_id));
drop policy if exists messages_insert on public.messages;
create policy messages_insert on public.messages for insert to authenticated with check(sender_id=auth.uid() and public.is_conversation_member(conversation_id));
drop policy if exists messages_update_own on public.messages;
create policy messages_update_own on public.messages for update to authenticated using(sender_id=auth.uid()) with check(sender_id=auth.uid());
drop policy if exists messages_delete_own on public.messages;
create policy messages_delete_own on public.messages for delete to authenticated using(sender_id=auth.uid());

drop policy if exists reactions_read on public.message_reactions;
create policy reactions_read on public.message_reactions for select to authenticated using(public.is_conversation_member(conversation_id));
drop policy if exists reactions_insert on public.message_reactions;
create policy reactions_insert on public.message_reactions for insert to authenticated with check(user_id=auth.uid() and public.is_conversation_member(conversation_id));
drop policy if exists reactions_delete on public.message_reactions;
create policy reactions_delete on public.message_reactions for delete to authenticated using(user_id=auth.uid());

drop policy if exists typing_read on public.typing_states;
create policy typing_read on public.typing_states for select to authenticated using(public.is_conversation_member(conversation_id));
drop policy if exists typing_insert on public.typing_states;
create policy typing_insert on public.typing_states for insert to authenticated with check(user_id=auth.uid() and public.is_conversation_member(conversation_id));
drop policy if exists typing_update on public.typing_states;
create policy typing_update on public.typing_states for update to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());

grant select,update on public.profiles to authenticated;
grant select,delete on public.friendships to authenticated;
grant select on public.conversations to authenticated;
grant select,update on public.conversation_members to authenticated;
grant select,insert,update,delete on public.messages to authenticated;
grant select,insert,delete on public.message_reactions to authenticated;
grant select,insert,update on public.typing_states to authenticated;
grant execute on function public.send_friend_request(uuid) to authenticated;
grant execute on function public.accept_friend_request(bigint) to authenticated;
grant execute on function public.get_or_create_direct(uuid) to authenticated;
grant execute on function public.create_group(text,uuid[]) to authenticated;

insert into storage.buckets(id,name,public,file_size_limit) values('chat-files','chat-files',true,52428800)
on conflict(id) do update set public=true,file_size_limit=52428800;
insert into storage.buckets(id,name,public,file_size_limit) values('avatars','avatars',true,10485760)
on conflict(id) do update set public=true,file_size_limit=10485760;

drop policy if exists chat_upload on storage.objects;
create policy chat_upload on storage.objects for insert to authenticated with check(bucket_id='chat-files' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists chat_delete on storage.objects;
create policy chat_delete on storage.objects for delete to authenticated using(bucket_id='chat-files' and owner_id=auth.uid()::text);
drop policy if exists avatar_upload on storage.objects;
create policy avatar_upload on storage.objects for insert to authenticated with check(bucket_id='avatars' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists avatar_update on storage.objects;
create policy avatar_update on storage.objects for update to authenticated using(bucket_id='avatars' and owner_id=auth.uid()::text);
drop policy if exists avatar_delete on storage.objects;
create policy avatar_delete on storage.objects for delete to authenticated using(bucket_id='avatars' and owner_id=auth.uid()::text);

-- Realtime for instant messages / requests / typing / read status
DO $$ begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='messages') then alter publication supabase_realtime add table public.messages; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='friendships') then alter publication supabase_realtime add table public.friendships; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='typing_states') then alter publication supabase_realtime add table public.typing_states; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='conversation_members') then alter publication supabase_realtime add table public.conversation_members; end if;
end $$;
