-- RNDM Chat v20 upgrade
-- Run in Supabase SQL Editor AFTER the v18 schema.
-- Adds real Clips publishing, marketplace, and a DEMO/game economy.

create extension if not exists pgcrypto;

-- ---------------- REAL CLIPS ----------------
create table if not exists public.clips (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  video_url text not null,
  caption text not null default '',
  created_at timestamptz not null default now()
);

create table if not exists public.clip_likes (
  clip_id uuid not null references public.clips(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (clip_id, user_id)
);

create table if not exists public.clip_comments (
  id bigint generated by default as identity primary key,
  clip_id uuid not null references public.clips(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 1000),
  created_at timestamptz not null default now()
);

create index if not exists clips_created_idx on public.clips(created_at desc);
create index if not exists clip_comments_clip_idx on public.clip_comments(clip_id, created_at);

alter table public.clips enable row level security;
alter table public.clip_likes enable row level security;
alter table public.clip_comments enable row level security;

drop policy if exists clips_read on public.clips;
create policy clips_read on public.clips for select to authenticated using (true);
drop policy if exists clips_insert on public.clips;
create policy clips_insert on public.clips for insert to authenticated with check (user_id = auth.uid());
drop policy if exists clips_delete on public.clips;
create policy clips_delete on public.clips for delete to authenticated using (user_id = auth.uid());

drop policy if exists clip_likes_read on public.clip_likes;
create policy clip_likes_read on public.clip_likes for select to authenticated using (true);
drop policy if exists clip_likes_insert on public.clip_likes;
create policy clip_likes_insert on public.clip_likes for insert to authenticated with check (user_id = auth.uid());
drop policy if exists clip_likes_delete on public.clip_likes;
create policy clip_likes_delete on public.clip_likes for delete to authenticated using (user_id = auth.uid());

drop policy if exists clip_comments_read on public.clip_comments;
create policy clip_comments_read on public.clip_comments for select to authenticated using (true);
drop policy if exists clip_comments_insert on public.clip_comments;
create policy clip_comments_insert on public.clip_comments for insert to authenticated with check (user_id = auth.uid());
drop policy if exists clip_comments_delete on public.clip_comments;
create policy clip_comments_delete on public.clip_comments for delete to authenticated using (user_id = auth.uid());

grant select,insert,delete on public.clips to authenticated;
grant select,insert,delete on public.clip_likes to authenticated;
grant select,insert,delete on public.clip_comments to authenticated;

insert into storage.buckets(id,name,public,file_size_limit)
values('clips','clips',true,104857600)
on conflict(id) do update set public=true,file_size_limit=104857600;

drop policy if exists clips_storage_upload on storage.objects;
create policy clips_storage_upload on storage.objects for insert to authenticated
with check(bucket_id='clips' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists clips_storage_delete on storage.objects;
create policy clips_storage_delete on storage.objects for delete to authenticated
using(bucket_id='clips' and owner_id=auth.uid()::text);

-- ---------------- RNDM MARKET ----------------
create table if not exists public.marketplace_listings (
  id uuid primary key default gen_random_uuid(),
  seller_id uuid not null references public.profiles(id) on delete cascade,
  title text not null check(char_length(title) between 2 and 120),
  description text not null default '',
  category text not null default 'Другое',
  price bigint not null default 0 check(price >= 0),
  city text not null default '',
  image_url text,
  status text not null default 'active' check(status in ('active','sold','hidden')),
  created_at timestamptz not null default now()
);
create index if not exists market_created_idx on public.marketplace_listings(created_at desc);

create table if not exists public.marketplace_favorites (
  listing_id uuid not null references public.marketplace_listings(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key(listing_id,user_id)
);

alter table public.marketplace_listings enable row level security;
alter table public.marketplace_favorites enable row level security;

drop policy if exists market_read on public.marketplace_listings;
create policy market_read on public.marketplace_listings for select to authenticated using(status <> 'hidden' or seller_id=auth.uid());
drop policy if exists market_insert on public.marketplace_listings;
create policy market_insert on public.marketplace_listings for insert to authenticated with check(seller_id=auth.uid());
drop policy if exists market_update on public.marketplace_listings;
create policy market_update on public.marketplace_listings for update to authenticated using(seller_id=auth.uid()) with check(seller_id=auth.uid());
drop policy if exists market_delete on public.marketplace_listings;
create policy market_delete on public.marketplace_listings for delete to authenticated using(seller_id=auth.uid());

drop policy if exists market_fav_read on public.marketplace_favorites;
create policy market_fav_read on public.marketplace_favorites for select to authenticated using(user_id=auth.uid());
drop policy if exists market_fav_insert on public.marketplace_favorites;
create policy market_fav_insert on public.marketplace_favorites for insert to authenticated with check(user_id=auth.uid());
drop policy if exists market_fav_delete on public.marketplace_favorites;
create policy market_fav_delete on public.marketplace_favorites for delete to authenticated using(user_id=auth.uid());

grant select,insert,update,delete on public.marketplace_listings to authenticated;
grant select,insert,delete on public.marketplace_favorites to authenticated;

insert into storage.buckets(id,name,public,file_size_limit)
values('market-files','market-files',true,20971520)
on conflict(id) do update set public=true,file_size_limit=20971520;

drop policy if exists market_storage_upload on storage.objects;
create policy market_storage_upload on storage.objects for insert to authenticated
with check(bucket_id='market-files' and (storage.foldername(name))[1]=auth.uid()::text);
drop policy if exists market_storage_delete on storage.objects;
create policy market_storage_delete on storage.objects for delete to authenticated
using(bucket_id='market-files' and owner_id=auth.uid()::text);

-- ---------------- GAME WALLET / LOANS / APARTMENTS ----------------
-- Everything in this section is virtual game currency. It is NOT a real loan or payment system.
create table if not exists public.game_wallets (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  balance bigint not null default 1500000 check(balance >= 0),
  updated_at timestamptz not null default now()
);

insert into public.game_wallets(user_id)
select id from public.profiles
on conflict(user_id) do nothing;

create or replace function public.ensure_game_wallet()
returns trigger language plpgsql security definer set search_path=public as $$
begin
  insert into public.game_wallets(user_id) values(new.id) on conflict(user_id) do nothing;
  return new;
end $$;

drop trigger if exists on_profile_game_wallet on public.profiles;
create trigger on_profile_game_wallet after insert on public.profiles
for each row execute function public.ensure_game_wallet();

create table if not exists public.game_loans (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  principal bigint not null check(principal > 0),
  rate_percent numeric(6,2) not null,
  term_months int not null,
  total_due bigint not null,
  remaining bigint not null,
  status text not null default 'active' check(status in ('active','paid')),
  created_at timestamptz not null default now()
);

create table if not exists public.demo_properties (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  city text not null,
  district text not null default '',
  price bigint not null check(price > 0),
  rooms int not null default 1,
  area numeric(7,1) not null default 30,
  emoji text not null default '🏠',
  description text not null default ''
);

create table if not exists public.owned_properties (
  user_id uuid not null references public.profiles(id) on delete cascade,
  property_id uuid not null references public.demo_properties(id) on delete cascade,
  bought_at timestamptz not null default now(),
  bought_price bigint not null,
  primary key(user_id,property_id)
);

insert into public.demo_properties(title,city,district,price,rooms,area,emoji,description)
select * from (values
 ('Студия у парка','Москва','Северное Бутово',2350000::bigint,1,24.5::numeric,'🌆','Компактная игровая квартира рядом с парком.'),
 ('Однокомнатная','Москва','Южное Бутово',3900000::bigint,1,38.2::numeric,'🏢','Светлая квартира с большой кухней.'),
 ('Двухкомнатная семейная','Москва','Чертаново',6200000::bigint,2,57.8::numeric,'🏙️','Две комнаты и игровая лоджия.'),
 ('Лофт в центре','Москва','Центр',9800000::bigint,2,71.0::numeric,'🌃','Игровой лофт с панорамными окнами.'),
 ('Загородный дом','Подольск','Волищево',12500000::bigint,4,146.0::numeric,'🏡','Дом с виртуальным участком и гаражом.'),
 ('Пентхаус RNDM','Москва','Москва-Сити',30000000::bigint,5,220.0::numeric,'✨','Самая дорогая коллекционная недвижимость RNDM.')
) as v(title,city,district,price,rooms,area,emoji,description)
where not exists(select 1 from public.demo_properties);

alter table public.game_wallets enable row level security;
alter table public.game_loans enable row level security;
alter table public.demo_properties enable row level security;
alter table public.owned_properties enable row level security;

drop policy if exists wallet_read on public.game_wallets;
create policy wallet_read on public.game_wallets for select to authenticated using(user_id=auth.uid());
drop policy if exists loans_read on public.game_loans;
create policy loans_read on public.game_loans for select to authenticated using(user_id=auth.uid());
drop policy if exists properties_read on public.demo_properties;
create policy properties_read on public.demo_properties for select to authenticated using(true);
drop policy if exists owned_read on public.owned_properties;
create policy owned_read on public.owned_properties for select to authenticated using(user_id=auth.uid());

grant select on public.game_wallets to authenticated;
grant select on public.game_loans to authenticated;
grant select on public.demo_properties to authenticated;
grant select on public.owned_properties to authenticated;

create or replace function public.take_demo_loan(amount bigint, months int)
returns uuid language plpgsql security definer set search_path=public as $$
declare
  me uuid:=auth.uid();
  rate numeric(6,2);
  total bigint;
  lid uuid;
  active_debt bigint;
begin
  if me is null then raise exception 'not authenticated'; end if;
  if amount < 10000 or amount > 5000000 then raise exception 'amount must be from 10000 to 5000000'; end if;
  if months not in (3,6,12,24) then raise exception 'term must be 3, 6, 12 or 24 months'; end if;
  select coalesce(sum(remaining),0) into active_debt from public.game_loans where user_id=me and status='active';
  if active_debt + amount > 7000000 then raise exception 'demo credit limit exceeded'; end if;
  rate := case months when 3 then 5 when 6 then 8 when 12 then 12 else 18 end;
  total := round(amount * (1 + rate/100.0));
  insert into public.game_wallets(user_id) values(me) on conflict(user_id) do nothing;
  update public.game_wallets set balance=balance+amount,updated_at=now() where user_id=me;
  insert into public.game_loans(user_id,principal,rate_percent,term_months,total_due,remaining)
  values(me,amount,rate,months,total,total) returning id into lid;
  return lid;
end $$;

create or replace function public.repay_demo_loan(loan_id uuid, amount bigint)
returns bigint language plpgsql security definer set search_path=public as $$
declare
  me uuid:=auth.uid();
  rem bigint;
  bal bigint;
  pay bigint;
begin
  if me is null then raise exception 'not authenticated'; end if;
  select remaining into rem from public.game_loans where id=loan_id and user_id=me and status='active' for update;
  if rem is null then raise exception 'active loan not found'; end if;
  select balance into bal from public.game_wallets where user_id=me for update;
  if amount <= 0 then raise exception 'invalid amount'; end if;
  pay:=least(amount,rem);
  if bal < pay then raise exception 'not enough demo balance'; end if;
  update public.game_wallets set balance=balance-pay,updated_at=now() where user_id=me;
  update public.game_loans set remaining=remaining-pay,status=case when remaining-pay<=0 then 'paid' else 'active' end where id=loan_id;
  return rem-pay;
end $$;

create or replace function public.buy_demo_property(property uuid)
returns void language plpgsql security definer set search_path=public as $$
declare
  me uuid:=auth.uid();
  p bigint;
  bal bigint;
begin
  if me is null then raise exception 'not authenticated'; end if;
  select price into p from public.demo_properties where id=property;
  if p is null then raise exception 'property not found'; end if;
  if exists(select 1 from public.owned_properties where user_id=me and property_id=property) then raise exception 'already owned'; end if;
  insert into public.game_wallets(user_id) values(me) on conflict(user_id) do nothing;
  select balance into bal from public.game_wallets where user_id=me for update;
  if bal < p then raise exception 'not enough demo balance'; end if;
  update public.game_wallets set balance=balance-p,updated_at=now() where user_id=me;
  insert into public.owned_properties(user_id,property_id,bought_price) values(me,property,p);
end $$;

grant execute on function public.take_demo_loan(bigint,int) to authenticated;
grant execute on function public.repay_demo_loan(uuid,bigint) to authenticated;
grant execute on function public.buy_demo_property(uuid) to authenticated;

-- Realtime for clips/market where useful.
do $$
begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='clips') then alter publication supabase_realtime add table public.clips; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='clip_comments') then alter publication supabase_realtime add table public.clip_comments; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='clip_likes') then alter publication supabase_realtime add table public.clip_likes; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='marketplace_listings') then alter publication supabase_realtime add table public.marketplace_listings; end if;
end $$;
